-- Generated from 1-Mplus_2027_每日靈修_1與2月結案版.xlsx
-- Insert-only seed: existing reviewed dates are never overwritten.
begin;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 32, '2027-02-01', '週一', '出離重圍與聖潔之印', '破土受造', 6, '羔羊寶血、紅海分開與曠野磐石', '黑暗中的亮光', '出埃及記 10:22–23', '出埃及記 10–11', '無', '約伯記 21', 3, '摩西向天伸杖，埃及遍地就烏黑了三天。三天之久，人不能相見，誰也不敢起來離開本處；惟有以色列人家中都有亮光。(出10:22-23)', '在第九災中，神使埃及全地陷入長達三天的黑暗。這黑暗不只是物理上的，更象徵著拒絕神所帶來的隔絕與恐懼。然而，在同樣的地理環境中，「惟有以色列人家中都有亮光」。這光不是因為他們的地勢特別，而是因為神與他們同在。', '觀察：埃及遍地烏黑時，唯有以色列人家中都有亮光。
在黑暗的環境中，神的同在就是我們的光。', '這段經文讓你想到最近哪件充滿不確定或恐懼的事？你如何在這件事上經歷神的同在？', '在感到焦慮或混亂時，花幾分鐘安靜，邀請神的光照進你的心思意念中。', '主啊，當周圍環境讓我感到黑暗或不知所措時，求祢與我同在，讓祢的光照亮我的心。阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 33, '2027-02-02', '週二', '出離重圍與聖潔之印', '破土受造', 6, '羔羊寶血、紅海分開與曠野磐石', '逾越節門楣上的羔羊寶血：出離死亡的拯救', '出埃及記 12:12–13', '出埃及記 12–13', '馬太福音 23', '無', 3, '因為那夜我要巡行埃及地，把埃及地一切頭生的，無論是人是牲畜，都擊殺了，又要敗壞埃及一切的神。我是耶和華。這血要在你們所住的房屋上作記號；我一見這血，就越過你們去。我擊殺埃及地頭生的時候，災殃必不臨到你們身上滅你們。(出12:12-13)', '在出埃及記第十二章中，神設立了逾越節。血是門上的記號；神應許看見血便越過那家。在原文中，「逾越（Pesach）」有「越過、保護」的意思。當審判臨到埃及時，凡門上有血記號的房屋，災殃就不臨到他們。作為新約信徒，我們常將這段經文延伸默想：基督如同我們的逾越節羔羊，祂的救贖將我們從罪惡與死亡的權勢中挽回。', '觀察：血是門上的記號，神應許看見血便越過那家。這也幫助新約信徒延伸默想基督的救贖。', 'Q1: 回想你生命的得救，是否清楚明白基督流血代贖的恩典？
Q2: 在每天的生活中，如何常常感恩並倚靠這份救贖的平安？', '今天在面對內心的控告或軟弱時，默想自己已經在基督寶血的遮蓋下，將恐懼交託給神。', '主耶穌，謝謝祢如同逾越節的羔羊為我捨命。因著祢的寶血，我得以出死入生。求祢天天洗淨我的心思意念，使我安穩在救贖的平安裡。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 34, '2027-02-03', '週三', '出離重圍與聖潔之印', '破土受造', 6, '羔羊寶血、紅海分開與曠野磐石', '不要懼怕，只管站住：看耶和華所施行的救恩', '出埃及記 14:13–14', '出埃及記 14', '馬太福音 24', '約伯記 22', 3, '摩西對百姓說：「不要懼怕，只管站住！看耶和華今天向你們所要施行的救恩。因為，你們今天所看見的埃及人必永遠不再看見了。耶和華必為你們爭戰；你們只管靜默，不要作聲。」', '面對前有紅海、後有追兵的絕境，以色列人驚恐抱怨。但摩西宣告：「不要懼怕，只管站住，看耶和華今天向你們所要施行的救恩...」在無助的絕境中，安靜與信靠是經歷神開路的重要一步。', '觀察：面對看似絕路的環境，摩西呼籲百姓勝過恐懼、安靜信靠。救恩不是單靠人的力量爭取，而是神為屬祂的百姓親自開路。', 'Q1: 當你陷入前有絕路、後有追兵的壓力時，你的第一反應是驚慌還是交託？
Q2: 「耶和華必為你們爭戰」這句話如何平息你心中的焦慮？', '今天若遇到讓你感到窒息的難題，先不要急著用自己的方法衝撞。安靜三分鐘，將主權交給神，求神陪伴、賜智慧面對下一步。', '主啊，當我面對環境的風浪與追逼而感到恐懼時，求祢按住我的心，讓我學習「只管站住」。我相信祢是為我爭戰的主，陪伴我們走每一步。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 35, '2027-02-04', '週四', '出離重圍與聖潔之印', '破土受造', 6, '羔羊寶血、紅海分開與曠野磐石', '每日新鮮的嗎哪：操練學習倚靠的功課', '出埃及記 16:4–5、14–21', '出埃及記 15–16', '無', '約伯記 23', 3, '[出埃及記 16:4-5]
耶和華對摩西說：「我要將糧食從天降給你們。百姓可以出去，每天收每天的份，我好試驗他們遵不遵我的法度。到第六天，他們要把所收進來的預備好，比每天所收的多一倍。」

[出埃及記 16:14-21 節錄]
露水上升之後，不料，野地面上有如白霜的小圓物……他們每日早晨，按著各人的飯量收取，日頭一發熱，就消化了。', '神降糧並試驗百姓是否遵行祂的指示。神吩咐每日收取每天的份，並吩咐第六日收雙份。這不僅解決了生存危機，更是教導他們仰望神的供應。神的恩典是日用日賜的，邀請我們每天去收取與經歷。', '觀察：神從天降下糧食，並藉此試驗百姓是否遵行祂的話。 每日收取的規定，教導百姓操練對神日用供應的信靠。', 'Q1: 你是否習慣靠自己的能力儲存安全感，而難以每天單純信靠神的供應？
Q2: 每天早晨來到神面前領受靈修亮光，如何成為你一天的力量來源？', '明天早晨起床後，將第一段時間留給神讀經禱告，把當天的憂慮交給這位供應的主。', '主啊，謝謝祢每天向我顯明新鮮的信實與供應。求祢賜我渴慕的心，天天領受從祢而來的話語，使我的靈命在曠野中日漸飽足。奉耶穌的名求，阿們。', true, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 36, '2027-02-05', '週五', '出離重圍與聖潔之印', '破土受造', 6, '羔羊寶血、紅海分開與曠野磐石', '爭戰中不同人的忠心與彼此扶持', '出埃及記 17:8–13', '出埃及記 17–18', '馬太福音 25', '無', 3, '那時，亞瑪力人來在利非訂，和以色列人爭戰。摩西對約書亞說：「你為我們選出人來，出去和亞瑪力人爭戰。明天我手裡要拿著神的杖，站在山頂上。」……摩西何時舉手，以色列人就得勝，何時垂手，亞瑪力人就得勝……亞倫與戶珥扶著他的手……約書亞用刀殺了亞瑪力王和他的百姓。(出17:8-13 節錄)', '以色列人在利非訂與亞瑪力人爭戰。約書亞在山下帶兵爭戰，摩西在山上舉手，而亞倫和戶珥扶住摩西的手。經文沒有直接說摩西舉手就是禱告，但這幅畫面生動地展現了：爭戰的過程中，有人在前線，有人在背後守望扶持。沒有人能獨自完成神的託付，我們都需要彼此的配搭。', '觀察：這場爭戰結合了約書亞的實際行動，以及摩西、亞倫、戶珥的彼此配搭與扶持。', '這段經文讓你想到最近哪件需要與人合作的事？你覺得自己現在的角色比較像前線還是後方？', '今天主動打通電話或傳訊息給一位正在承擔壓力的同工或朋友，告訴他：「我今天會特別為你禱告，加油！」', '主耶穌，求祢讓我看見肢體同行、互相扶持的重要。當我軟弱疲乏時，求祢差派同伴托住我的手；也賜我愛心去扶持身邊軟弱的人。奉耶穌的名求，阿們。', true, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 37, '2027-02-06', '週六', '出離重圍與聖潔之印', '破土受造', 6, '羔羊寶血、紅海分開與曠野磐石', '客西馬尼的降服：願你的旨意成就', '馬太福音 26:36–39；路加福音 22:39–44', '出埃及記 19–20', '馬太福音 26', '約伯記 24', 4, '[馬太福音 26:36-39]
耶穌同門徒來到一個地方，名叫客西馬尼……他就稍往前走，俯伏在地，禱告說：「我父啊，倘若可行，求你叫這杯離開我。然而，不要照我的意思，只要照你的意思。」

[路加福音 22:39-44]
耶穌出來，照常往橄欖山去……耶穌很傷痛，禱告更加懇切，汗珠如大血點滴在地上。', '在客西馬尼園的夜裡，耶穌面對即將到來的十架苦難。路加福音記載祂很傷痛，甚至汗珠如大血點滴在地上。祂向父神俯伏禱告：「我父啊，倘若可行，求你叫這杯離開我；然而，不要照我的意思，只要照你的意思。」在肉體的痛苦與使命的張力中，耶穌選擇了將自己的意志交融在父神的旨意裡。', '觀察：面對苦難與心靈極度痛苦時，向神坦承掙扎是真實的禱告。 「不要照我的意思，只要照你的意思」展現了極深的降服。', 'Q1: 當神的旨意與你個人的計畫或舒適圈衝突時，你內心的掙扎是什麼？
Q2: 學習耶穌在客西馬尼的禱告，如何幫助你面對生命中的苦杯？', '今天在禱告中，將一件你一直捨不得放手、希望照自己意思成就的事交給神，誠實對祂說：「主啊，願祢的旨意成就。」', '主耶穌，謝謝祢在客西馬尼園為我順服到底。當我面對苦難或不願順服的時刻，賜我力量挪去我的固執，學習祢「不要照我的意思，只要照你的意思」的完全降服。奉耶穌的名求，阿們。', true, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 38, '2027-02-07', '週日', '出離重圍與聖潔之印', '破土受造', 6, '羔羊寶血、紅海分開與曠野磐石', '幔子裂開：基督受死帶來親近神的道路', '馬太福音 27:50–51；希伯來書 4:14–16', '出埃及記 21–22', '馬太福音 27', '約伯記 25', 4, '[馬太福音 27:50-51]
耶穌又大聲喊叫，氣就斷了。忽然，殿裡的幔子從上到下裂為兩半，地也震動，磐石也崩裂。

[希伯來書 4:14-16]
我們既然有一位已經升入高天尊榮的大祭司……所以，我們只管坦然無懼地來到施恩的寶座前，為要得憐恤，蒙恩惠，作隨時的幫助。', '當耶穌在十字架上氣斷身亡的那一刻，聖殿裡的幔子從上到下裂為兩半。厚重的聖殿幔子原本隔絕了人與至聖所，象徵著神聖的界線。基督受死，親自開闢了一條又新又活的路。希伯來書的作者因此鼓勵我們，可以藉著這位大祭司，「坦然無懼地來到施恩的寶座前」。這是一份極大的恩典，我們隨時都可以親近神。', '觀察：聖殿幔子從上到下裂開，表明這是神主動的工作。 基督的死為我們開闢了親近神的新路。', 'Q1: 你在禱告時，是否常覺得自己滿身汙穢、不敢靠近神？
Q2: 「幔子已裂開」這個真理，如何改變你對禱告與神親密感的態度？', '今天無論心情如何，花三分鐘安靜，想像自己已經跨過裂開的幔子，正坐在天父的懷抱裡，對祂訴說你的感謝與需要。', '主耶穌，謝謝祢在十架上捨命，為我裂開了通往至聖所的幔子。感謝祢讓我不再是懼怕的奴僕，而是能坦然無懼呼叫阿爸父的兒女。奉耶穌的名求，阿們。', true, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 39, '2027-02-08', '週一', '出離重圍與聖潔之印', '破土受造', 7, '山上指示的樣式與至聖所的榮光', '立約的血灑在百姓身上：遵行神話語的回應', '出埃及記 24:7–8', '出埃及記 23–24', '無', '無', 2, '又將約書念給百姓聽。他們說：「耶和華所吩咐的，我們都必遵行。」摩西將血灑在百姓身上，說：「你看！這是立約的血，是耶和華按這一切話與你們立約的憑據。」', '出埃及記 24 章記載了立約、百姓回應和灑血。摩西將約書念給百姓聽，百姓同心回應必遵行，隨後摩西將血灑在百姓身上，宣告這是立約的憑據。新約信徒在領受聖餐時，常會延伸默想這段經文，記念耶穌基督用自己的血與我們所立的新約。', '觀察：神宣讀約書，百姓以「我們都必遵行」來回應。 摩西灑下立約的血，作為神與百姓立約的憑據。', 'Q1: 當你讀到神的話語時，你心裡是否也有「我必遵行」的順服心志？
Q2: 每天的靈修生活，如何幫助你堅守與神所立的聖潔約定？', '今天在讀經時，挑選一句神對你的提醒，把它當作今天與神立下的微小約定，用行動把它做出來。', '主啊，謝謝祢用厚恩與寶血與我立約。求祢賜我順服的靈，使我不僅是聽道，更是甘心樂意地遵行祢的一切話語。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 40, '2027-02-09', '週二', '出離重圍與聖潔之印', '破土受造', 7, '山上指示的樣式與至聖所的榮光', '天上地下的權柄與同行應許：大使命的差遣', '馬太福音 28:18–20', '出埃及記 25–26', '馬太福音 28', '約伯記 26', 4, '耶穌進前來，對他們說：「天上地下所有的權柄都賜給我了。所以，你們要去，使萬民作我的門徒，奉父、子、聖靈的名給他們施洗。凡我所吩咐你們的，都教訓他們遵守，我就常與你們同在，直到世界的末了。」', '在加利利的山上，復活的主向門徒發出了歷史上最偉大的差遣——大使命。耶穌開宗明義宣告：「天上地下所有的權柄都賜給我了。」因為有這宇宙大君王的權柄作後盾，所以我們可以放膽去使萬民作門徒。而這段話最溫暖的結尾是：「我就常與你們同在，直到世界的末了。」權柄給我們使命，而同在給我們勇氣。', '觀察：大使命的權柄來自復活基督的學習交託。 教會受主差遣使萬民作門徒；信徒按恩賜與處境參與。', 'Q1: 當你想到向身邊的人分享信仰時，你心中最大的擔憂是什麼？
Q2: 帶著「天上地下權柄」與「主必同在」的應許去生活，會如何改變你的眼光？', '今天為你身邊一位還沒信主的親友禱告，求主給你機會分享一點主在你身上的恩典，按你的處境參與使人作門徒的呼召。', '主耶穌，謝謝祢帶著天上地下的權柄差遣我。當我面對傳福音的挑戰時，求祢提醒我：祢不僅是差遣我的主，更是「直到世界末了」與我同在的摯友。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 41, '2027-02-10', '週三', '出離重圍與聖潔之印', '破土受造', 7, '山上指示的樣式與至聖所的榮光', '曠野晨光的禱告：在安靜深處得著前行力量', '馬可福音 1:35', '出埃及記 27–28', '馬可福音 1', '約伯記 27', 4, '次日早晨，天未亮的時候，耶穌起來，到曠野地方去，在那裡禱告。', '馬可福音記錄了耶穌在迦百農忙碌一天後，次日清晨天還未亮，就起來走到曠野地方去禱告。這是一個美好的邀請，讓我們觀察耶穌的榜樣，在生活中尋找安靜的時刻，重新對焦神的心意。', '觀察：耶穌在忙碌的服事中，仍清晨退到安靜處禱告。 這是耶穌的榜樣，邀請我們在生活中尋找親近神的時刻。', 'Q1: 你的生活是否常被忙碌塞滿，以致壓縮了與神獨處的時間？
Q2: 效法耶穌的榜樣，你如何為自己規劃每天的「晨光曠野時刻」？', '明天試著比平常早起 15 分鐘，不滑手機，安靜在桌前讀一段經文、向神說說你心裡的重擔與感恩。', '主耶穌，看見祢在忙碌中仍堅持清晨親近父神，實在是我極大的榜樣。求祢賜我自律的心，每天保留一段安靜的曠野時刻，重新得力。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 42, '2027-02-11', '週四', '出離重圍與聖潔之印', '破土受造', 7, '山上指示的樣式與至聖所的榮光', '我要住在你們中間', '出埃及記 29:45–46', '出埃及記 29', '無', '無', 1, '我要住在以色列人中間，作他們的神。他們必知道我是耶和華他們的神，是將他們從埃及地領出來的，為要住在他們中間。我是耶和華他們的神。(出29:45-46)', '出埃及記 29 章記載了祭司承接聖職的繁複禮儀。這一切的預備與潔淨，最終指向一個核心目的：神宣告祂要住在百姓中間。神將他們從埃及領出來，不僅是為了讓他們得自由，更是為了恢復神與人同住的親密關係。', '觀察：神拯救以色列人出埃及的終極目的，是為了住在他們中間。
救恩不只是脫離罪惡，更是進入與神同在的關係。', '「神渴望住在我們中間」這個真理，如何改變你對每日生活的看法？', '今天在轉換工作任務或休息時，在心裡默默對神說：「主，歡迎祢參與我現在正在做的事。」', '主，謝謝祢樂意住在我生命中。求祢幫助我更敏銳祢的同在，在日常瑣事中經歷與祢同行的喜樂。阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 43, '2027-02-12', '週五', '出離重圍與聖潔之印', '破土受造', 7, '山上指示的樣式與至聖所的榮光', '康健的人用不著醫生', '馬可福音 2:17', '出埃及記 30–31', '馬可福音 2', '約伯記 28', 4, '耶穌聽見，就對他們說：「康健的人用不著醫生，有病的人才用得著。我來本不是召義人，乃是召罪人。」(可2:17)', '耶穌在稅吏利未的家裡，與許多稅吏和罪人一同坐席。法利賽人對此感到不解甚至輕視，耶穌卻清楚宣告了祂的使命：祂來不是為了尋找自以為義的人，而是來醫治那些承認自己有病、需要救恩的罪人。', '觀察：耶穌主動靠近被社會邊緣化的罪人，並宣告祂來是為了醫治有病的人。
承認自己的軟弱與需要，是經歷主醫治的第一步。', '在你的信仰生活中，你比較常把自己當作「康健的人」還是「需要醫生的病人」？', '今天在禱告中，誠實地把一個你一直想隱藏的軟弱告訴主，求祂來醫治與幫助。', '主耶穌，我承認自己不完美，有很多軟弱和過犯。謝謝祢沒有拒絕我，求祢來醫治我，引導我走前面的路。阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 44, '2027-02-13', '週六', '出離重圍與聖潔之印', '破土受造', 7, '山上指示的樣式與至聖所的榮光', '破口之中的代求：寧願捨己也要挽回的愛', '出埃及記 32:31–32', '出埃及記 32–33', '馬可福音 3', '約伯記 29', 4, '摩西回到耶和華那裡，說：「唉！這百姓犯了大罪，為自己做了金神像。倘或你肯赦免他們的罪——不然，求你從你所寫的冊上塗抹我的名。」', '以色列人在山下造了金牛犢，犯下大罪。摩西回到神面前懇切代求：「倘或你肯赦免他們的罪……不然，求你從你所寫的冊上塗抹我的名。」摩西為百姓懇求赦免，展現了一位領袖為軟弱百姓代求的心腸。', '觀察：當百姓犯罪時，摩西回到神面前懇切代求，甚至情願自己的名被塗抹。', 'Q1: 當你看到家人或朋友陷入罪中或軟弱時，你的反應是論斷還是迫切代求？
Q2: 願意為他人代求甚至付上代價，對你的靈性生命有什麼要求？', '今天為一位你所關心、目前在屬靈上軟弱或離開神的人懇切禱告 5 分鐘，求神開恩把他領回。', '主啊，謝謝祢將代求的負擔放在我心中。求祢赦免我常帶著冷漠與論斷看人的失敗。賜我摩西般愛人的心，常站在破口處為人代求。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 45, '2027-02-14', '週日', '出離重圍與聖潔之印', '破土受造', 7, '山上指示的樣式與至聖所的榮光', '磐石縫裡的親密凝視：有憐憫有恩典的神', '出埃及記 34:6–7', '出埃及記 34–35', '馬可福音 4', '無', 3, '耶和華在他面前宣告說：「耶和華，耶和華，是有憐憫有恩典的神，不輕易發怒，並有豐盛的慈愛和誠實，為千萬人存留慈愛，赦免罪孽、過犯，和罪惡，萬不以有罪的為無罪，必追討他的罪，自父及子，直到三、四代。」(出 34:6-7)', '神向摩西宣告了自己的屬性，這包含了慈愛與公義。神宣告自己有憐憫、有恩典，為千萬人存留慈愛，赦免罪孽；同時也宣告「萬不以有罪的為無罪」，顯明祂完全的公義。恩典、赦免與公義在神身上是完全並存的。', '觀察：神親自宣告祂是有憐憫、有恩典、不輕易發怒的神。 神為千萬人存留慈愛，並赦免人的罪孽與過犯。', '經文同時呈現神的憐憫與公義，哪一面是你較容易忽略的？', '今天默想出埃及記 34:6 這段經文。當你覺得自己得罪神、灰心時，記得這位神是滿有恩典與憐憫的主，向祂敞開自己。', '主啊，謝謝祢向我顯明祢那有憐憫、有恩典、不輕易發怒的慈愛本性。每當我跌倒軟弱時，求祢用祢豐盛的慈愛把我拉回，使我安穩在祢的恩典中。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 46, '2027-02-15', '週一', '出離重圍與聖潔之印', '破土受造', 8, '山上指示的樣式與雲彩的引導', '富餘的奉獻', '出埃及記 36:5–6', '出埃及記 36–37', '無', '約伯記 30', 3, '對摩西說：「百姓為耶和華吩咐使用之工所拿來的，富富有餘。」摩西傳命，他們就在全營中宣告說：「無論男女，不必再為聖所拿什麼禮物來。」這樣才攔住百姓不再拿來。(出36:5-6)', '當摩西呼籲百姓為會幕奉獻時，百姓的反應出乎意料地熱烈。他們每天早晨甘心樂意地拿禮物來，直到工匠向摩西報告材料已經「富富有餘」，摩西甚至必須下令攔住他們。這生動地展現了當人心被神的恩典觸動時，所發出的慷慨與喜樂。', '觀察：百姓因著甘心樂意，拿來的奉獻多到富富有餘，甚至需要摩西下令停止。
出於感恩的奉獻，會帶來極大的喜樂與豐盛。', '這段經文讓你想到最近哪一次出於感恩而喜樂付出的經驗？', '今天找機會用你的時間、才幹或資源，出於感恩去幫助身邊的一個人，不求回報。', '主啊，祢賜給我的恩典何等豐富。求祢也賜給我一顆慷慨的心，讓我能甘心樂意地與人分享祢的愛。阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 47, '2027-02-16', '週二', '出離重圍與聖潔之印', '破土受造', 8, '山上指示的樣式與雲彩的引導', '不要怕，只要信：跨越絕望死蔭的信心飛躍', '馬可福音 5:36', '出埃及記 38–39', '馬可福音 5', '約伯記 31', 4, '耶穌聽見所說的話，就對管會堂的說：「不要怕，只要信！」', '管會堂的睚魯女兒瀕死，路上又傳來噩耗，旁人說「何必還勞動夫子呢？」在這樣絕望的時刻，耶穌對睚魯說：「不要怕，只要信！」耶穌鼓勵他在最壞的消息面前，依然看著祂。這不是保證事情一定會照我們的期待發展，而是在恐懼中，邀請我們與祂站在一起。', '觀察：當環境宣告「已經太遲了」時，耶穌鼓勵睚魯「不要怕，只要信」。', 'Q1: 當你面對「已經太遲了」的困境時，你的第一反應是放棄還是信靠？
Q2: 「不要怕，只要信」這六個字，如何成為你今天的力量？', '今天若有一件你覺得已經無力回天的事，把擔憂放下，在心中對自己說：「不要怕，只要信」，交給這位掌管復活的主。', '主耶穌，當周圍的聲音與環境都對我說「已經沒希望了」時，求祢對我的心說「不要怕，只要信」。賜我堅定的信心，經歷祢復活的大能與奇蹟。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 48, '2027-02-17', '週三', '出離重圍與聖潔之印', '破土受造', 8, '山上指示的樣式與雲彩的引導', '雲彩的引導：起行與安營全看主吩咐', '出埃及記 40:34–38；民數記 9:15–23', '出埃及記 40；利未記 1', '馬可福音 6', '無', 3, '[出埃及記 40:34-38]
當時，雲彩遮蓋會幕，耶和華的榮光就充滿了帳幕……

[民數記 9:15-23]
立起帳幕的那日，有雲彩遮蓋帳幕……雲彩停留在帳幕上，無論是兩天，是一月，是一年，以色列人就住營不起行；但雲彩收上去，他們就起行。(節錄)', '出埃及記記載會幕建造完成後，雲彩遮蓋會幕，神的榮光充滿帳幕。民數記則詳細描述了這雲彩的引導：雲彩收上去，以色列人就起行；雲彩停住，他們就安營。無論是一天、一月或是一年，全聽從神的吩咐。這段歷史記載了神親自住在百姓中間，並用雲彩實質地成為他們行程的引導與元帥。', '觀察：會幕落成後，神的榮光充滿帳幕，並以雲彩遮蓋。 民數記記載百姓學會順服雲彩的起行與安營。', 'Q1: 在你的人生規畫中，你習慣先衝刺再求神祝福，還是先等候「雲彩」動才起行？
Q2: 學習以色列人等候雲彩的功課，對你目前的決定有何幫助？', '今天面對一項重要的決定或工作，先不要急著行動。花五分鐘禱告：「主啊，若非祢的雲彩引領，求攔阻我；若出於祢，求祢開路。」', '主啊，謝謝祢讓榮光充滿在我們中間。求祢賜我敏銳與順服的心，不憑自己的血氣急躁衝動，而是緊緊跟隨祢雲彩的引領，起行或安營全聽祢的吩咐。奉耶穌的名求，阿們。', true, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 49, '2027-02-18', '週四', '出離重圍與聖潔之印', '破土受造', 8, '山上指示的樣式與雲彩的引導', '獻上平安祭', '利未記 3:1', '利未記 2–3', '無', '約伯記 32', 3, '人獻供物為平安祭，若是從牛群中獻，無論是公的是母的，必用沒有殘疾的獻在耶和華面前。(利3:1)', '平安祭（又稱酬恩祭）是舊約五祭中，唯一一種獻祭者可以與祭司、家人一同分享祭肉的祭。它通常是在感恩、還願或甘心獻上時舉行。這不僅是向神表達感恩，也象徵著人與神、人與人之間的和睦與團契。', '觀察：平安祭是為了表達感恩，並且能在神面前與人一同分享。
感恩與和睦是我們敬拜生活中重要的一部分。', '最近有什麼事情讓你想要向神獻上「平安祭」表達感恩？', '今天主動向一位曾幫助過你的人表達感謝，或者與家人朋友分享一件神最近為你做的事。', '主，謝謝祢賜給我平安與各種恩典。求祢幫助我常存感恩的心，也讓我能與身邊的人和睦相處，分享祢的愛。阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 50, '2027-02-19', '週五', '出離重圍與聖潔之印', '破土受造', 8, '山上指示的樣式與雲彩的引導', '從內心發出的污穢', '馬可福音 7:20–23', '利未記 4', '馬可福音 7', '約伯記 33', 3, '又說：「從人裡面出來的，那才能污穢人；因為從裡面，就是從人心裡，發出惡念、苟合、偷盜、兇殺、姦淫、貪婪、邪惡、詭詐、淫蕩、嫉妒、謗讟、驕傲、狂妄。這一切的惡都是從裡面出來，且能污穢人。」(可7:20-23)', '法利賽人拘泥於外在的潔淨，耶穌卻直指問題核心：「從人裡面出來的，那才能污穢人。」耶穌宣告真正的污穢不在於外在環境，而在於人的內心。惡念與各種惡行會從人心發出，我們更需要留意內心的狀態。', '觀察：耶穌指出，惡念與惡行會從人心發出。這提醒我們，內心的狀態比外在的儀式更需要被神鑒察。', 'Q1: 你是否常把信仰停留在外在的表現（如守主日、讀經），卻忽略了內心動機的清潔？
Q2: 當邪惡的念頭（嫉妒、計較、苦毒）冒出時，你如何交給主來對付？', '今天當你發現自己心裡浮現負面控告或嫉妒時，立刻在心裡禱告：「主啊，求祢鑒察我的心，用寶血洗淨我裏面的心思。」', '主耶穌，求祢鑑察我的內心。我知道自己裡面常有不潔的念頭與動機。求祢用十架的寶血洗淨我的心，使我的心思意念重新對齊祢的聖潔。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 51, '2027-02-20', '週六', '出離重圍與聖潔之印', '破土受造', 8, '山上指示的樣式與雲彩的引導', '祭司每日早晨的職責', '利未記 6:12–13', '利未記 5–6', '馬可福音 8', '無', 3, '壇上的火要在其上常常燒著，不可熄滅。祭司要每日早晨在上面燒柴，並要把燔祭擺在壇上，在其上燒平安祭牲的脂油。在壇上必有常常燒著的火，不可熄滅。', '在利未記的記載中，祭壇上的火要在其上常常燒著。經文描述了祭司有實際的職責去維持祭火，每天早晨在上面燒柴並獻祭。作為新約信徒，我們可將此作為持續敬拜的延伸默想，提醒自己藉著親近神來維持與祂的關係。', '觀察：祭壇上的火不可熄滅，祭司必須每日早晨燒柴維持。 這需要祭司忠心盡責地執行神的吩咐。', 'Q1: 檢視你的靈命，最近是否感到冷淡、只剩下灰燼？
Q2: 你今天可以為心中的祭壇「添上什麼新柴」（如：更多禱告、默想神話語）？', '找一個固定的時間（例如早晨或睡前），安靜讀一段神的話，作為你今天親近神的行動。', '主啊，願我能建立穩定親近祢的習慣，讓我的心常常轉向祢，在日常中保持對祢的敬拜。阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 52, '2027-02-21', '週日', '出離重圍與聖潔之印', '破土受造', 8, '山上指示的樣式與雲彩的引導', '在軟弱中真實的呼求', '馬可福音 9:23–24', '利未記 7–8', '馬可福音 9', '約伯記 34', 4, '耶穌對他說：「你若能信，在信的人，凡事都能。」孩子的父親立時喊著說：「我信！但我信不足，求主幫助。」', '一位父親帶著被鬼附的兒子來求耶穌：「你若能做什麼，求你憐憫我們，幫助我們。」耶穌對他說：「你若能信，在信的人，凡事都能。」這父親立時流淚喊著說：「我信！但我信不足，求主幫助。」面對極大的困境，這位父親誠實地帶著自己的軟弱與不足，向耶穌發出求助。重點在於他即便信心微弱，仍願意轉向耶穌尋求憐憫與醫治。', '觀察：父親帶著被鬼附的兒子求醫治，「我信不足，求主幫助」展現了誠實帶著軟弱向主求助的心。', 'Q1: 當你面對大山般的難題時，你的信心是充足，還是像那位父親一樣感到「信不足」？
Q2: 帶著軟弱與不信向主呼求「求主幫助」，為你帶來什麼釋放？', '今天若心裡對某個禱告題目感到懷疑、不敢奢求，向主坦承：「主啊，我有懷疑，但我願意信，求祢幫我挪去不信的惡心。」', '主耶穌，我帶著軟弱與信心不足來到祢面前。求祢赦免我的小信，加添我仰望祢的力量。主啊，我信！但我信不足，求祢幫助我。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 53, '2027-02-22', '週一', '出離重圍與聖潔之印', '破土受造', 9, '贖罪恩典與旋風中神的大能發問', '我在親近我的人中要顯為聖', '利未記 10:3', '利未記 9–10', '無', '約伯記 35', 3, '於是摩西對亞倫說：「這就是耶和華所說：『我在親近我的人中要顯為聖；在眾民面前，我要得榮耀。』」亞倫就默默不言。(利10:3)', '亞倫的兒子拿答、亞比戶因獻上神沒有吩咐的凡火，遭火吞滅。在這個悲痛的時刻，摩西提醒亞倫神曾說過的話：「我在親近我的人中要顯為聖」。這嚴肅地提醒我們，越是親近神、參與服事的人，越需要存著敬畏的心，尊神的名為聖。', '觀察：神要求在親近祂的人中顯為聖，在眾民面前得榮耀。
服事與親近神是一項恩典，但也需要帶著深深的敬畏。', '這段經文如何提醒你在教會服事或日常敬拜中的態度？', '在今天開始你的工作或服事之前，安靜片刻，求神幫助你以敬畏與專注的心來完成。', '主啊，祢是聖潔的。求祢赦免我有時在服事或敬拜中的隨便與輕忽。幫助我常存敬畏的心，在一切所做的事上尊祢為聖。阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 54, '2027-02-23', '週二', '出離重圍與聖潔之印', '破土受造', 9, '贖罪恩典與旋風中神的大能發問', '你們要聖潔：因為我是聖潔的', '利未記 11:44–45', '利未記 11–12', '馬可福音 10', '無', 3, '我是耶和華你們的神；所以你們要分別為聖，成為聖潔，因為我是聖潔的。你們也不可在地上的爬物污穢自己。我是把你們從埃及地領出來的耶和華，要作你們的神；所以你們要聖潔，因為我是聖潔的。', '神在利未記中頒布了飲食與潔淨的條例，並宣告：「我是把你們從埃及地領出來的耶和華，要作你們的神；所以你們要聖潔，因為我是聖潔的。」神呼召以色列人過分別為聖的生活，因為祂自己是聖潔的。新約信徒延伸反思這段經文，明白我們同樣蒙召，在日常生活中效法神的聖潔本性，活出屬神子民的生命樣式。', '觀察：神宣告祂是聖潔的，呼召以色列人過分別為聖的生活。 這是基於神將他們從埃及領出來，作他們神的救恩事實。', '這段經文讓你想到最近在工作或待人接物上的哪件事？效法神的聖潔，會如何影響你的決定？', '今天檢視自己的娛樂與眼目所接觸的事物，若有哪一樣會拉扯你的心離開神的聖潔，勇敢試著在今天拒絕它一次。', '主啊，祢是公義良善的，願我能學習聖潔。讓我在這彎曲悖謬的世代中，能活出討祢喜悅的生活。阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 55, '2027-02-24', '週三', '出離重圍與聖潔之印', '破土受造', 9, '贖罪恩典與旋風中神的大能發問', '信靠神，也學習饒恕', '馬可福音 11:22–25', '利未記 13–14', '馬可福音 11', '約伯記 36', 4, '耶穌回答說：「你們當信服神。我實在告訴你們，無論何人對這座山說：『你挪開此地，投在海裡！』他若心裡不疑惑，只信他所說的必成，就必給他成了…… 你們站著禱告的時候，若想起有人得罪你們，就當饒恕他，好叫你們在天上的父也饒恕你們的過犯。」(可11:22-25 節錄)', '耶穌教導門徒：「你們當信服神。」並用「挪開這座山」來比喻信心的禱告大有能力。緊接著，耶穌在教導禱告時特別加上了「饒恕」的條件：「若想起有人得罪你們，就當饒恕他」。這提醒我們，信心的禱告不僅是祈求困難的挪開，更包含了在人際關係中尋求神的帶領，賜下饒恕的力量。', '觀察：耶穌邀請門徒信靠神，把所求帶到祂面前；經文也提醒我們禱告時要饒恕。', '面對目前的困難，我可以如何向神祈求，也尋求祂帶領下一步？', '在禱告中把你遇到的困難告訴神，求祂賜下信心；若想起與人的摩擦，也求神幫助你慢慢學習饒恕。', '主啊，我把面前的難題交給祢，求祢帶領我。也願我能放下心中的芥蒂，學習饒恕。阿們。', true, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 56, '2027-02-25', '週四', '出離重圍與聖潔之印', '破土受造', 9, '贖罪恩典與旋風中神的大能發問', '贖罪日的潔淨：藉基督的血得以潔淨', '利未記 16:29–34；希伯來書 9:11–14', '利未記 15–16', '無', '約伯記 37', 3, '[利未記 16:29-34]
因在這日要為你們贖罪，使你們潔淨。你們要在耶和華面前得以潔淨，脫離一切的罪愆……

[希伯來書 9:11-14]
但現在基督已經來到……何況基督藉著永遠的靈，將自己無瑕無疵獻給神，他的血豈不更能洗淨你們的良心，除去你們的死行，使你們事奉那永生神嗎？(節錄)', '大贖罪日是舊約中神設立為全以色列人贖罪的日子，使百姓得以潔淨。新約的希伯來書則將此與基督的救贖連結，宣告基督藉著永遠的靈獻上自己，祂的血更能洗淨我們的良心，成就了永遠的贖罪事工。', '觀察：大贖罪日是神為以色列人設立的潔淨與贖罪之日。 贖罪的目的是使百姓得以潔淨，脫離罪愆。', 'Q1: 明白舊約的贖罪與新約基督的代贖，如何幫助你確信罪已得赦？
Q2: 基督的血洗淨我們的良心，如何激勵你事奉永生神？', '當你想起過去的過犯時，除了感謝基督已經為你贖罪，也試著帶著被洗淨的良心，去做一件服事人或敬拜神的事作為回應。', '主，謝謝祢洗淨了我的良心。讓我不只是停留在自我安慰裡，而是能帶著清潔的心去服事身邊的人。阿們。', true, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 57, '2027-02-26', '週五', '出離重圍與聖潔之印', '破土受造', 9, '贖罪恩典與旋風中神的大能發問', '竭盡心力愛神：全人傾注的最高敬拜', '馬可福音 12:29–30', '利未記 17–18', '馬可福音 12', '無', 3, '耶穌回答說：「第一要緊的就是說：『以色列啊，你要聽，主我們神是獨一的主。你要盡心、盡性、盡意、盡力愛主你的神。』」', '當文士問耶穌哪一條是第一要緊的誡命時，耶穌引述了申命記的「示瑪」：「以色列啊，你要聽：主我們神是獨一的主。你要盡心、盡性、盡意、盡力愛主你的神。」這裡用了四個「盡」，涵蓋了我們的心靈、情感、理智與體力。愛神不是零碎時間的施捨，而是毫無保留、全人傾注的最高敬拜。', '觀察：耶穌將「愛神」放在所有誡命的首位，這是信仰最核心的靈魂。 「盡心、盡性、盡意、盡力」要求我們毫無保留地將主權交給神。', 'Q1: 檢視你的生活，你是否將最好的時間、精神與熱情都給了世界，只把剩餘的給神？
Q2: 「盡力愛神」對你而言，意味著在工作或家庭中做出什麼調整？', '今天在處理任何事情前，在心裡對主說：「主啊，這件事我為祢做，這是我愛祢的一部分。」讓日常瑣事化為對神的愛慕。', '主啊，祢是獨一的真神，配得我全人的愛。求祢光照我，挪去我分心的偶像，教導我如何每天盡心、盡性、盡意、盡力地來愛祢、事奉祢。奉耶穌的名求，阿們。', false, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 58, '2027-02-27', '週六', '出離重圍與聖潔之印', '破土受造', 9, '贖罪恩典與旋風中神的大能發問', '要愛人如己：神聖誡命的終極實踐', '利未記 19:18；馬太福音 22:37–40', '利未記 19–20', '馬可福音 13', '約伯記 38', 4, '[利未記 19:18]
不可報仇，也不可埋怨你本國的子民，卻要愛人如己。我是耶和華。

[馬太福音 22:37-40]
耶穌對他說：「你要盡心、盡性、盡意愛主你的神……其次也相仿，就是要愛人如己。這兩條誡命是律法和先知一切道理的總綱。」', '利未記中宣告了「不可報仇，也不可埋怨你本國的子民，卻要愛人如己」(利19:18 節錄)。愛人如己緊接在禁止報仇與懷恨的命令之後。到了新約，耶穌將愛神與愛人如己並列，稱這是律法和先知的總綱。愛人如己是基於神是耶和華的信仰實踐，按著神的教導向身邊的人展現善意。', '觀察：經文吩咐不可報仇與懷恨，卻要愛人如己。 「愛人如己」建立在「我是耶和華」的信仰基礎上。', 'Q1: 在不報仇與愛人如己的教導中，你覺得最難實踐的是什麼？
Q2: 認識這誡命是律法總綱，如何影響你日常待人的態度？', '今天試著在適當的界線與智慧中，向一位曾有摩擦的人釋放善意，不懷怨恨。', '主啊，謝謝祢教導我要愛人如己。求祢賜我智慧與愛心，不懷恨、不報復，在生活中真實活出祢所喜悅的善意。奉耶穌的名求，阿們。', true, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
insert into public.daily_devotionals (church_id, day_number, devotional_date, weekday, month_theme, tree_stage, week_number, week_theme, devotional_title, selected_scripture_reference, roots_reading, branches_reading, fruit_reading, chapter_count, scripture_text, context_summary, key_points, reflection_questions, life_application, response_prayer, scripture_is_excerpt, scripture_version, scripture_source, scripture_license_note, review_status) values ('M+', 59, '2027-02-28', '週日', '出離重圍與聖潔之印', '破土受造', 9, '贖罪恩典與旋風中神的大能發問', '一位婦人用香膏膏耶穌', '馬可福音 14:3–9', '利未記 21', '馬可福音 14', '約伯記 39', 3, '耶穌在伯大尼長大痲瘋的西門家裡坐席的時候，有一個女人拿著一玉瓶至貴的真哪噠香膏來，打破玉瓶，把膏澆在耶穌的頭上……耶穌說：「由她吧！為什麼難為她呢？她在我身上做的是一件美事……她所做的是盡她所能的；她是為我安葬的事把香膏預先澆在我身上。我實在告訴你們，普天之下，無論在什麼地方傳這福音，也要述說這女人所做的，以為記念。」(可14:3-9 節錄)', '一位婦人拿著至貴的真哪噠香膏，澆在耶穌頭上。耶穌把旁人眼中的浪費，解釋為她為安葬所作的事；祂也說，傳福音時會記念她的行動。耶穌看重她出於愛的行動，而非世俗的價值計算。', '觀察：那位婦人將至貴的香膏傾倒在耶穌頭上，盡她所能地表達愛，而耶穌看重並記念了這行動。', '旁人不認同她的做法，耶穌卻如何看待她？這段經文帶給你什麼問題或感受？', '邀請神引導你在目前的處境中，用你所能的方式回應祂的愛。', '主耶穌，有時我做的決定別人不理解，我也會自我懷疑。求祢讓我知道祢看見了我的心，並引導我繼續用單純的心跟隨祢。阿們。', true, null, null, null, 'initial_review') on conflict (church_id, devotional_date) do nothing;
commit;
