import assert from 'node:assert/strict';import fs from 'node:fs';import {database} from './bootstrap.mjs';
const output=new URL('./results/',import.meta.url);fs.mkdirSync(output,{recursive:true});
const report=[];let db;
const owner='10000000-0000-4000-8000-000000000001',email='10000000-0000-4000-8000-000000000002',line='10000000-0000-4000-8000-000000000003',same='10000000-0000-4000-8000-000000000004',other='10000000-0000-4000-8000-000000000005';
const q=async(sql,args=[])=> (await db.query(sql,args)).rows;
const scalar=async(sql,args=[])=>Object.values((await q(sql,args))[0])[0];
const login=async(uid,role='authenticated')=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims','{}',false)",[uid]);await db.exec('set role '+role);};
async function test(name,fn){await fn();report.push({name,status:'passed'});console.log('PASS',name);}
const snapshot=uid=>{return db.exec('reset role').then(()=>scalar('select church_auth.account_snapshot($1)',[uid]));};
const accounts=()=>scalar('select public.list_admin_accounts_v4()');
const version=async uid=>(await accounts()).find(a=>a.user_id===uid)?.version;
const input={display_name:'合成同工',job_title:'測試負責人',active:true,grants:[{church_id:'M+',permission:'schedules'}],roles:[{church_id:'M+',role_key:'custom'}],features:[{feature_key:'schedules',view:true,create:true,edit:true,delete:false,export:false,approve:true,manage:true}],home_modules:['schedules','spaces'],notification_topics:['tasks'],ministries:['media']};
const request=n=>'20000000-0000-4000-8000-'+String(n).padStart(12,'0');
const save=(uid,data,ver,n)=>scalar('select public.save_admin_account_bundle($1,$2,$3::jsonb,$4,$5)',[uid,'M+',JSON.stringify(data),ver,request(n)]);
try{
 db=await database();
 await q('insert into auth.users(id,email) select x::uuid, case when x=$2 then null else x||\'@example.invalid\' end from unnest($1::text[]) x',[[owner,email,line,same,other],line]);
 await q("insert into church_auth.accounts(user_id,is_active,display_name,job_title) select id,true,'同名測試同工','測試同工' from auth.users");
 await q('insert into church_auth.owners(user_id) values($1)',[owner]);
 await q("insert into auth.identities values($1,'custom:line-web','U00000000000000000000000000000003','{\"name\":\"合成 LINE\"}')",[line]);
 await q("insert into church_auth.grants(user_id,church_id,permission) values($1,'M+','schedules'),($2,'M+','notification_settings'),($3,'SHiNE','schedules')",[email,owner,other]);
 await q("insert into church_auth.account_roles values($1,'M+','custom')",[email]);
 await q("insert into church_auth.service_ministry_scopes(user_id,church_id,ministry_key) values($1,'M+','media')",[email]);
 await q("insert into church_auth.account_feature_permissions(user_id,church_id,feature_key,can_manage) values($1,'M+','notification_settings',true)",[owner]);
 await db.exec("insert into public.review_workflow_settings(church_id,workflow_key,workflow_label,notify_app,notify_line) values('M+','daily_devotional','每日靈修',true,false)");
 await db.exec('insert into public.members(id) values(123)');
 await db.query("insert into church_auth.member_bindings(church_id,login_channel_id,line_subject,member_id,active,approved_by,approved_at) values('M+','2011645391','U00000000000000000000000000000003',123,true,$1,now())",[owner]);
 await login(owner);
 await test('migration loads in isolated PostgreSQL',async()=>assert.equal((await accounts()).length,5));
 await test('same names remain separate before verified linkage',async()=>assert.equal(new Set((await accounts()).map(x=>x.user_id)).size,5));
 await test('LINE approval persists exact source and copies ministry scopes',async()=>{assert.equal(await scalar('select public.approve_line_admin_access_review($1,$2)',[line,email]),true);assert.equal((await accounts()).length,4);});
 await test('member association follows only the approved LINE subject',async()=>{const a=(await accounts()).find(a=>a.user_id===email);assert.deepEqual(a.member_associations,[{church_id:'M+',member_id:123}]);});
 await test('approval retry is idempotent',async()=>assert.equal(await scalar('select public.approve_line_admin_access_review($1,$2)',[line,email]),true));
 await test('cannot relink an identity to another person',async()=>await assert.rejects(()=>scalar('select public.approve_line_admin_access_review($1,$2)',[line,same]),/identity_already_linked/));
 await test('verified linked row contains both Auth IDs',async()=>{const a=(await accounts()).find(a=>a.user_id===email);assert.deepEqual(a.linked_user_ids,[line]);assert.equal(a.has_line,true);});
 await test('same-name unlinked person remains visible',async()=>assert((await accounts()).some(a=>a.user_id===same)));
 await test('Email canonical account recognizes its owner-approved LINE alias',async()=>{await login(email);const c=await scalar('select public.get_my_app_capabilities()');assert.equal(c.has_line,true);assert.equal(c.canonical_user_id,email);assert.equal(c.is_owner,false);await login(owner);});
 await test('unlinked same-name account cannot inherit another LINE identity',async()=>{await login(same);assert.equal((await scalar('select public.get_my_app_capabilities()')).has_line,false);await login(owner);});
 await test('active owner capability is derived from protected records',async()=>assert.equal((await scalar('select public.get_my_app_capabilities()')).is_owner,true));
 let ver=await version(email),saved;
 await test('one transaction saves complete bundle for both identities',async()=>{saved=await save(email,input,ver,1);assert.equal(saved.saved,true);});
 await test('bundle repeated with same request returns original receipt',async()=>assert.deepEqual(await save(email,input,ver,1),saved));
 await test('request ID cannot be reused with altered data',async()=>await assert.rejects(()=>save(email,{...input,display_name:'另一內容'},ver,1),/request_reused/));
 await test('stale version cannot overwrite recent update',async()=>await assert.rejects(()=>save(email,input,ver,2),/account_changed/));
 const before=await snapshot(email);await login(owner);ver=await version(email);
 await test('failure after profile and grants writes rolls whole transaction back',async()=>await assert.rejects(()=>save(email,{...input,display_name:'必須回復',home_modules:['invalid-home']},ver,3),/invalid_preferences/));
 await test('triggered coworker profile also rolls back on failure',async()=>{await db.exec('reset role');assert.equal(await scalar('select count(*)::int from public.pastoral_staff where app_user_id=any($1::uuid[]) and display_name=$2',[[email,line],'必須回復']),0);await login(owner);});
 await test('rollback retains every previous profile, permission, home and scope',async()=>{assert.deepEqual(await snapshot(email),before);await login(owner);});
 await test('cross-church grant injection is rejected',async()=>await assert.rejects(()=>save(email,{...input,grants:[{church_id:'SHiNE',permission:'schedules'}]},ver,4),/invalid_grant/));
 await test('feature operation cannot exceed granted feature',async()=>await assert.rejects(()=>save(email,{...input,features:[{...input.features[0],feature_key:'members'}]},ver,5),/feature_without_grant/));
 await test('ministry scopes require scheduling permission',async()=>await assert.rejects(()=>save(email,{...input,grants:[{church_id:'M+',permission:'members'}],features:[]},ver,6),/scope_without_grant/));
 await test('enabled account requires at least one grant',async()=>await assert.rejects(()=>save(email,{...input,grants:[],roles:[],features:[],ministries:[]},ver,7),/active_without_grants/));
 await test('missing or null input fields fail closed',async()=>await assert.rejects(()=>save(email,{...input,active:null},ver,8),/invalid_input/));
 await test('legacy profile endpoint synchronizes only verified aliases',async()=>assert.equal(await scalar('select public.set_admin_account_profile($1,$2,$3)',[line,'已同步','測試職稱']),true));
 await test('reviewer list deduplicates only verified identity and keeps same-name peer',async()=>{const p=await scalar("select public.get_review_workflow_settings('M+')");assert.equal(p.people.length,2);assert.equal(p.people.find(p=>p.canonical_id===email).id,line);assert(p.people.find(p=>p.id===owner));});
 await test('initial and final cannot select two identities of same person',async()=>await assert.rejects(()=>scalar("select public.save_review_workflow_setting('M+','daily_devotional',$1,$2,true,false)",[email,line]),/invalid_setting/));
 await test('reviewers must have correct church membership',async()=>await assert.rejects(()=>scalar("select public.save_review_workflow_setting('M+','daily_devotional',$1,$2,true,false)",[owner,other]),/invalid_reviewer/));
 await test('non-owner cannot list admin account details',async()=>{await login(other);await assert.rejects(()=>accounts(),/not_owner/);});
 await test('non-owner cannot save account settings',async()=>await assert.rejects(()=>save(email,input,ver,9),/not_owner/));
 await test('cross-church manager cannot read workflows',async()=>await assert.rejects(()=>scalar("select public.get_review_workflow_settings('M+')"),/forbidden/));
 await test('anonymous cannot call admin RPC',async()=>{await login('', 'anon');await assert.rejects(()=>accounts(),/permission denied/);});
 await test('authenticated clients cannot read mapping, receipts or audit tables',async()=>{await login(other);for(const t of ['account_identity_links','account_operation_receipts','account_change_audit'])await assert.rejects(()=>q('select * from church_auth.'+t),/permission denied/);});
 await test('owner privileges cannot be removed',async()=>{await login(owner);await assert.rejects(()=>scalar('select public.remove_admin_account($1)',[owner]),/owner_immutable/);});
 await test('revoked owner session cannot edit accounts',async()=>{await q("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({session_id:request(99)})]);await assert.rejects(()=>save(email,input,ver,10),/session_revoked/);await login(owner);});
 await test('disabled account can clear scopes and permissions atomically',async()=>{const v=await version(email);assert((await save(email,{...input,active:false,ministries:[]},v,11)).saved);});
 await test('disabled canonical account loses LINE administrative capability',async()=>{await login(email);assert.equal((await scalar('select public.get_my_app_capabilities()')).has_line,false);await login(owner);});
 await test('disabled former workflow manager cannot save with stale feature permission',async()=>{await db.exec('reset role');await q("insert into church_auth.account_feature_permissions(user_id,church_id,feature_key,can_manage) values($1,'M+','notification_settings',true)",[email]);await login(email);await assert.rejects(()=>scalar("select public.save_review_workflow_setting('M+','daily_devotional',$1,$2,true,false)",[owner,line]),/forbidden/);await login(owner);});
 await test('revocation removes every verified admin identity in one transaction',async()=>assert.equal(await scalar('select public.remove_admin_account($1)',[line]),true));
 await test('repeated removal is safe',async()=>assert.equal(await scalar('select public.remove_admin_account($1)',[email]),true));
 await test('revocation preserves Auth identities and member records',async()=>{await db.exec('reset role');assert.equal(await scalar('select count(*)::int from public.members'),1);assert.equal(await scalar('select count(*)::int from church_auth.member_bindings where active'),1);assert.equal(await scalar('select count(*)::int from auth.users'),5);assert.equal(await scalar('select count(*)::int from auth.identities'),1);assert.equal(await scalar('select count(*)::int from church_auth.accounts where user_id=any($1::uuid[])',[[email,line]]),0);assert.equal(await scalar('select count(*)::int from church_auth.account_feature_permissions where user_id=any($1::uuid[])',[[email,line]]),0);assert.equal(await scalar('select count(*)::int from church_auth.service_ministry_scopes where user_id=any($1::uuid[])',[[email,line]]),0);});
 await test('canonical link remains available after administrative revocation',async()=>assert.equal(await scalar('select church_auth.canonical_account($1)',[line]),email));
 await test('revoked administrative account cannot regain access through retained LINE link',async()=>{await login(email);assert.equal((await scalar('select public.get_my_app_capabilities()')).has_line,false);await login(owner);});
 await test('disabled owner is no longer reported as owner',async()=>{await db.exec('reset role');await q('update church_auth.accounts set is_active=false where user_id=$1',[owner]);await login(owner);assert.equal((await scalar('select public.get_my_app_capabilities()')).is_owner,false);});
 fs.writeFileSync(new URL('db-results.json',output),JSON.stringify({engine:await scalar('select version()'),isolated:true,synthetic_accounts_only:true,checks:report},null,2));
 console.log('TOTAL',report.length);
}catch(e){console.error('FAIL',e.message,e.detail||'',e.position||'');process.exitCode=1;}finally{await db?.close();}
