import {db} from './admin-db.mjs';
import {listGroups} from './group-management.mjs';
import {listAttendance,listAttendanceMembers,saveAttendance} from './attendance-management.mjs';
const values=new URLSearchParams(location.search).getAll('church'),church=values.length===1?values[0]:null;
const $=s=>document.querySelector(s),status=$('#status'),editor=$('#editor'),records=$('#records'),term=church==='SHiNE'?'小家':'小組';let groups=[],members=[],busy=false;
const el=(tag,value,cls='')=>{const n=document.createElement(tag);n.textContent=value;n.className=cls;return n;},split=v=>(v||'').split('、').map(x=>x.trim()).filter(Boolean);
function openForm(row=null){editor.replaceChildren();editor.hidden=false;const form=document.createElement('form'),grid=el('div','','edit-grid'),date=document.createElement('input'),group=document.createElement('select'),memo=document.createElement('textarea'),people=el('fieldset');date.type='date';date.value=row?.meeting_date||new Date().toISOString().slice(0,10);group.append(new Option('-- 選擇'+term+' --',''));for(const g of groups)group.append(new Option(g.name,g.id));const currentGroup=groups.find(g=>g.name===row?.group_name);if(currentGroup)group.value=String(currentGroup.id);memo.maxLength=1000;memo.value=row?.memo||'';const priorPresent=new Set(split(row?.present_list)),priorAbsent=new Set(split(row?.absent_list)),list=el('div','','choice-grid');people.append(el('legend','勾選本次出席會員'),list);function renderPeople(){list.replaceChildren();const selected=groups.find(g=>String(g.id)===group.value),eligible=members.filter(m=>selected&&(m.group_name||'').trim()===(selected.name||'').trim()),known=new Set(eligible.map(m=>m.name));for(const oldName of [...priorPresent,...priorAbsent])if(!known.has(oldName))eligible.push({name:oldName});for(const m of eligible){const label=el('label','','choice'),box=document.createElement('input');box.type='checkbox';box.dataset.name=m.name;box.checked=priorPresent.has(m.name);label.append(box,el('span',m.name));list.append(label);}if(!eligible.length)list.append(el('p','此'+term+'目前沒有會員。','muted'));}group.onchange=()=>{priorPresent.clear();priorAbsent.clear();renderPeople();};renderPeople();for(const [label,input] of [['聚會日期',date],[term,group],['備註',memo]]){const wrap=el('label',label);wrap.append(input);grid.append(wrap);}const actions=el('div','','editor-actions'),cancel=el('button','取消','secondary'),save=el('button',row?'儲存更正':'儲存點名');cancel.type='button';cancel.onclick=()=>editor.hidden=true;actions.append(cancel,save);form.append(el('h2',row?'更正點名紀錄':'新增聚會點名'),grid,people,actions);form.onsubmit=async e=>{e.preventDefault();if(busy)return;const selected=groups.find(g=>String(g.id)===group.value);if(!selected){status.textContent='請選擇'+term+'。';return;}const boxes=[...list.querySelectorAll('input[type=checkbox]')],present=boxes.filter(x=>x.checked).map(x=>x.dataset.name),absent=boxes.filter(x=>!x.checked).map(x=>x.dataset.name);busy=true;try{await saveAttendance(db,church,{meeting_date:date.value,group_name:selected.name,leader_name:selected.leader,present,absent,memo:memo.value},row);editor.hidden=true;await load();status.textContent=row?'點名紀錄已更正。':'點名紀錄已儲存。';}catch(error){status.textContent=error.message;}finally{busy=false;}};editor.append(form);date.focus();}
function render(rows){records.replaceChildren();const expected=rows.reduce((sum,r)=>sum+(r.total_expected||0),0),present=rows.reduce((sum,r)=>sum+(r.total_present||0),0);if(rows.length)records.append(el('p','最近紀錄總出席率：'+(expected?Math.round(present/expected*100):0)+'%（'+present+' / '+expected+'）','status-message'));for(const row of rows){const card=el('article','','audit-card'),head=el('div','','audit-head');head.append(el('strong',row.meeting_date+' · '+row.group_name),el('span','出席 '+row.total_present+' / '+row.total_expected,'status-badge'));card.append(head,el('p','負責同工：'+(row.leader_name||'未填寫')),el('p','出席：'+(row.present_list||'無')),el('p','缺席：'+(row.absent_list||'無')));if(row.memo)card.append(el('p','備註：'+row.memo,'muted'));const edit=el('button','更正紀錄','secondary');edit.onclick=()=>openForm(row);card.append(edit);records.append(card);}if(!rows.length)records.append(el('p','目前沒有出席紀錄。','muted'));}
async function load(){status.textContent='正在載入…';try{const [rows,g,m]=await Promise.all([listAttendance(db,church),listGroups(db,church),listAttendanceMembers(db,church)]);groups=g;members=m;render(rows);$('#new').disabled=false;status.textContent='顯示最近 '+rows.length+' 筆出席紀錄。';}catch(error){status.textContent=error.message;}}
$('#title').textContent=(church==='M+'?'M＋大雅教會':'火樂教會')+' · 聚會點名';$('#members').href='members.html?church='+encodeURIComponent(church||'');$('#groups').href='groups.html?church='+encodeURIComponent(church||'');$('#new').onclick=()=>openForm();load();
