import {db} from './admin-db.mjs';import {listGroups,listGroupMembers,assignMemberToGroup,setGroupLeader} from './group-management.mjs';
const values=new URLSearchParams(location.search).getAll('church'),church=values.length===1?values[0]:null,$=s=>document.querySelector(s),term=church==='SHiNE'?'小家':'小組',leaderTerm=church==='SHiNE'?'小家長':'小組長';let groups=[],members=[],busy=false;
const el=(tag,value,cls='')=>{const n=document.createElement(tag);n.textContent=value;n.className=cls;return n;};
function selectedGroup(){return groups.find(x=>String(x.id)===$('#group').value);}
function render(){const group=selectedGroup(),current=$('#current'),available=$('#available');current.replaceChildren();available.replaceChildren();if(!group)return;for(const member of members){const inside=(member.group_name||'').trim()===(group.name||'').trim();if(!inside){available.append(new Option(member.name+'（'+(member.group_name||'未編組')+'）',member.id));continue;}const row=el('article','','audit-card'),head=el('div','','audit-head'),actions=el('div','','card-actions');head.append(el('strong',member.name),el('span',member.phone||'無電話','muted'));if(group.leader!==member.name){const lead=el('button','設為'+leaderTerm,'secondary');lead.onclick=()=>setLeader(group,member);actions.append(lead);}const remove=el('button','移出','secondary');remove.onclick=()=>move(member,'未編組');actions.append(remove);row.append(head,el('p',group.leader===member.name?'目前'+leaderTerm:'一般成員','muted'),actions);current.append(row);}if(!current.children.length)current.append(el('p','此'+term+'目前沒有成員。','muted'));$('#assign').disabled=!available.options.length;}
async function refresh(message=''){[groups,members]=await Promise.all([listGroups(db,church),listGroupMembers(db,church)]);const prior=$('#group').value;$('#group').replaceChildren(...groups.map(g=>new Option(g.name,g.id)));if(groups.some(g=>String(g.id)===prior))$('#group').value=prior;render();$('#status').textContent=message||'資料已載入。';}
async function move(member,name){if(busy||!confirm('確定將 '+member.name+(name==='未編組'?' 移出目前'+term:' 調入 '+name)+'？'))return;busy=true;try{await assignMemberToGroup(db,church,member,name);await refresh('成員所屬已更新。');}catch(error){$('#status').textContent=error.message;}finally{busy=false;}}
async function setLeader(group,member){if(busy||!confirm('確定將 '+member.name+' 設為'+leaderTerm+'？'))return;busy=true;try{await setGroupLeader(db,church,group,member);await refresh(leaderTerm+'已更新。');}catch(error){$('#status').textContent=error.message;}finally{busy=false;}}
$('#title').textContent=(church==='M+'?'M＋大雅教會':'火樂教會')+' · '+term+'成員管理';$('#back').href='groups.html?church='+encodeURIComponent(church||'');$('#group').onchange=render;$('#assign').onclick=()=>{const group=selectedGroup(),member=members.find(x=>String(x.id)===$('#available').value);if(group&&member)move(member,group.name);};refresh().catch(error=>$('#status').textContent=error.message);
