import {CHURCHES,FEATURES,DEMO} from './line-preview-data.mjs?v=20260923-3';

const $=selector=>document.querySelector(selector);
const params=new URLSearchParams(location.search);
let church=Object.hasOwn(CHURCHES,params.get('church'))?params.get('church'):'M+';
let feature=['menu',...FEATURES.map(item=>item.key)].includes(params.get('feature'))?params.get('feature'):'menu';
const view=$('#feature-view');
const prayerCounts=new Map(DEMO.prayer.requests.map(item=>[item.id,item.prayers]));
const prayerWatching=new Map(DEMO.prayer.requests.map(item=>[item.id,item.watching||0]));
const THREE_HOURS=3*60*60*1000;
const prayerHaloState=new Map(DEMO.prayer.requests.map(item=>[item.id,{level:item.halo||0,expiresAt:item.halo?Date.now()+THREE_HOURS:0}]));
let prayerDay=new Date().getDay(),addedPrayer=false,selectedLoveCard=0,prayerRealtimeTimer=null,prayerExpiryTimer=null;

function escape(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function setTheme(){const data=CHURCHES[church];document.documentElement.style.setProperty('--accent',data.accent);document.documentElement.style.setProperty('--accent-soft',data.accentSoft);$('#church-logo').src=data.logo;$('#church-logo').alt=data.name;$('#church-name').textContent=data.name;$('#page-context').textContent=feature==='menu'?'LINE 圖文選單':FEATURES.find(item=>item.key===feature)?.title||'LINE 會員服務';}
function updateUrl(){const next=new URL(location.href);next.searchParams.set('church',church);next.searchParams.set('feature',feature);history.replaceState(null,'',next);}
function go(next){feature=next;updateUrl();renderControls();render();view.scrollTop=0;}
function hero(title,copy,eyebrow='MEMBER CARE'){return `<header class="page-hero"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><p>${copy}</p></header>`;}

function menuPage(){return `<div class="menu-page">
  <article class="chat-sample"><span class="pill">☀️ 晨光出發 · 給今天的你</span><p class="verse">「你們心裡不要憂愁；你們信神，也當信我。」</p><p class="verse-ref">— 約翰福音 14:1</p></article>
  <div class="rich-menu-label"><strong>${escape(CHURCHES[church].group)}會員服務</strong><span>點選任一項預覽</span></div>
  <nav class="rich-menu">${FEATURES.map(item=>`<a href="?church=${encodeURIComponent(church)}&feature=${item.key}" data-feature="${item.key}"><span class="menu-icon">${item.icon}</span><strong>${item.title}</strong><small>${item.subtitle}</small></a>`).join('')}</nav>
  <p class="micro muted" style="text-align:center;margin:14px 4px 0">此畫面模擬 LINE 圖文選單；不會連接正式聊天室。</p>
  </div>`;}

function todayPage(){const d=DEMO.today;return `<div class="mobile-page">${hero('給今天的你','停一下，讓一句話陪你走過今天。','MORNING GRACE')}
  <article class="surface"><span class="pill">☀️ 晨光出發 · 還有 1 天</span><h3 style="margin:16px 0 0">${d.greeting}</h3><p class="verse">「${d.scripture}」</p><p class="verse-ref">— ${d.reference}</p><div class="reflection"><strong>💡 晨光激勵</strong><p>${d.reflection}</p></div><button class="primary" id="receive">✨ 領受宣告，阿們！</button><div id="today-response"></div></article>
  <p class="micro muted" style="text-align:center">示範資料：日後會由本堂經文庫隨機抽取。</p></div>`;}

function helpPage(){const first=DEMO.help.moods[0];return `<div class="mobile-page">${hero('隨時的幫助','現在的你，需要哪一種陪伴？','A HELP IN TIME')}
  <section class="surface"><h3 class="section-title">選擇此刻的心情</h3><div class="mood-grid">${DEMO.help.moods.map((m,i)=>`<button class="mood-button${i?'':' active'}" data-mood="${m.key}"><span>${m.icon}</span><strong>${m.label}</strong></button>`).join('')}</div></section>
  <article class="surface" id="mood-card">${moodCard(first)}</article></div>`;}
function moodCard(mood){return `<span class="pill">${mood.icon} ${mood.label}</span><p class="verse">「${mood.scripture}」</p><p class="verse-ref">— ${mood.reference}</p><div class="reflection"><strong>一起禱告</strong><p class="prayer-copy">${mood.prayer}</p></div><button class="primary" id="mood-pray">我願意一起禱告</button><div id="mood-response"></div>`;}

function activeHalo(id){const state=prayerHaloState.get(id);if(!state||!state.level||state.expiresAt<=Date.now()){if(state?.level)prayerHaloState.set(id,{level:0,expiresAt:0});return 0;}return state.level;}
function haloLayers(level){return Array.from({length:level},(_,index)=>`<span class="halo-layer halo-${index+1}" aria-hidden="true"></span>`).join('');}
function orbitDots(count){return Array.from({length:Math.min(3,count||0)},(_,index)=>`<span class="orbit-track orbit-${index+1}"><i></i></span>`).join('');}
function prayerOrb(row){const count=prayerCounts.get(row.id)??row.prayers,watching=prayerWatching.get(row.id)??row.watching??0,level=activeHalo(row.id);return `<button class="prayer-orb ${row.size}" data-prayer-id="${row.id}" data-halo-level="${level}" data-prayer-name="${escape(row.name)}" data-prayer-title="${escape(row.title)}" style="--x:${row.x}%;--y:${row.y}%">${haloLayers(level)}${orbitDots(watching)}<span class="prayer-name">${row.name}</span><strong>${row.title}</strong><span class="prayer-reactions">🙏 <b id="prayer-count-${row.id}">${count}</b><em id="watch-count-${row.id}">${watching?`守望 ${watching}`:''}</em></span></button>`;}
function prayerPage(){const day=DEMO.prayer.days[prayerDay];return `<div class="prayer-wall-page day-${prayerDay} weather-calm" id="prayer-wall">
  <header class="prayer-wall-head"><span class="pill">${escape(CHURCHES[church].name)} · 動態禱告牆</span><h2>同心微光</h2><p>點擊禱告圈，可加入代禱或寫下守望禱告。</p></header>
  <section class="prayer-compose"><div><strong><span id="weather-icon">◌</span> <span id="weather-label">台中 · 讀取此刻天氣</span></strong><span><i class="live-dot"></i><b id="realtime-status">即時同步中</b> · 光暈守望 3 小時</span></div><button id="open-prayer-form">🔥 提出代禱</button></section>
  <form class="prayer-quick-form" id="prayer-quick-form" hidden><label>稱呼<input value="測試家人" maxlength="20"></label><label>代禱主題<input value="新的方向與平安" maxlength="40"></label><label>禱告內容<textarea maxlength="300">求主帶領接下來的方向，也賜下平安與智慧。</textarea></label><div class="segmented"><label><input type="radio" name="wall-privacy" value="public" checked> 公開在禱告牆</label><label><input type="radio" name="wall-privacy" value="private"> 僅教牧同工</label></div><button class="primary">送出預覽代禱</button></form>
  <section class="prayer-sky" id="prayer-sky">${DEMO.prayer.requests.map(prayerOrb).join('')}${addedPrayer?prayerOrb({id:99,name:'測試家人',title:'新的方向與平安',prayers:0,watching:0,size:'medium',x:23,y:46}):''}<div class="prayer-spark s1"></div><div class="prayer-spark s2"></div><div class="prayer-spark s3"></div><div class="prayer-spark s4"></div></section>
  <footer class="prayer-wall-stats"><strong>🔥 今日公開代禱：41 次</strong><span>● 表示已有守望禱告文</span></footer><p class="micro prayer-legend">每位家人加入會增加一層光暈，三小時內最多七層；此頁為預覽，不會寫入資料庫。</p></div>`;}

function chips(title,items,active=0,multi=false){return `<fieldset class="chip-field"><legend>${title}</legend><div class="form-chips">${items.map((item,index)=>`<button type="button" class="form-chip ${index===active?'active':''}" data-chip-group="${title}" data-multi="${multi}">${item}</button>`).join('')}</div></fieldset>`;}
function newcomerPage(){const d=DEMO.newcomer;return `<div class="mobile-page">${hero('遇見你真好 · 歡迎回家','很高興今天有你在我們當中，願這裡成為放鬆、充飽電的溫暖角落。','WELCOME HOME')}
  <form class="surface newcomer-long" id="newcomer-demo"><span class="pill">🧡 新朋友認識卡</span><label class="field">1. 怎麼稱呼你？<input value="${d.name}"></label>${chips('性別',['弟兄／帥哥','姊妹／美女'],0)}<label class="field">2. 聯絡手機<input value="${d.phone}"></label><label class="field">3. 生日（含年份）<input type="date" value="${d.birthday}"></label>${chips('4. 年齡區間',['🎓 學生學青','💼 20–30 歲青年','🏡 30–45 歲青壯','🌟 45 歲以上熟齡'],1)}${chips('5. 平時生活地區',['📍 大雅區','📍 西屯區','📍 北屯區','📍 南屯區','📍 西區','📍 北區','📍 東區','📍 南區','📍 沙鹿區','📍 其他'],0)}${chips('6. 今天怎麼認識我們？',['🙋 朋友家人邀請','📱 IG 臉書','💻 YouTube／網站','🚶 散步路過','🎪 社區趣味活動'],0)}<label class="field">邀請你的朋友<input placeholder="是哪位朋友邀請你來的呢？"></label>${chips('7. 目前的信仰近況',['還不是基督徒','尚未受洗，想多認識','基督徒，臨時來訪','正在尋找合適教會'],1)}${chips('8. 今天最想感受什麼？',['🌿 讓心靈放鬆充電','🎵 聽聽溫暖音樂','🤝 認識聊得來的朋友','💡 探索未來方向','📖 多了解聖經'],0,true)}${chips('9. 生活興趣與休閒',['☕ 咖啡手作','🎸 音樂欣賞','💼 職場成長','🏕️ 戶外踏青','👶 親子育兒','🍳 美食料理','🏸 運動健走','📖 閱讀寫作'],1,true)}<div class="photo-preview"><span>📷</span><strong>拍照或挑選更新個人照片</strong><div><button type="button">打開相機</button><button type="button">從相簿挑選</button></div></div><label class="field">想對我們說的話<textarea>${d.note}</textarea></label><button class="primary">✨ 很高興認識你，留下今日印記</button><p class="micro muted">正式欄位與選項由各堂會管理員設定；此處只模擬手機操作。</p></form></div>`;}

function weeklyPage(){const m=CHURCHES[church].meeting;return `<div class="mobile-page">${hero('不見不散喔','本週聚會資訊都在這裡，期待與你見面。','SEE YOU THIS WEEK')}
  <article class="surface"><div class="schedule-date"><div class="calendar-tile"><small>SEP</small><span>27</span></div><div><h3>${m.date}</h3><p>${m.time} 開始</p></div></div><div class="schedule-list"><div class="schedule-row"><span>✨</span><div><strong>${m.title}</strong><br><span class="muted">信息分享：${m.speaker}</span></div></div><div class="schedule-row"><span>📍</span><div><strong>${m.place}</strong><br><span class="muted">${m.address}</span></div></div><div class="schedule-row"><span>👨‍👩‍👧</span><div><strong>兒童聚會同步進行</strong><br><span class="muted">歡迎全家一起來</span></div></div></div><button class="primary" id="calendar-demo">加入我的行事曆</button><button class="secondary" id="map-demo">查看交通方式</button><div id="weekly-response"></div></article>
  <article class="surface"><h3 class="section-title">聚會小提醒</h3><p class="muted" style="font-size:13px;line-height:1.7">建議提早 10 分鐘抵達。第一次來的朋友，可向入口接待同工說「我是新朋友」。</p></article></div>`;}

function loveCanvas(card,recipient='親愛的好友',signature='測試家人',message=card.caption){const brand=CHURCHES[church];return `<div class="love-canvas scene-${card.tone}" data-card-church="${escape(church)}"><div class="love-frame"><div class="love-card-brand"><img src="${escape(brand.logo)}" alt="${escape(brand.name)} Logo"></div><span>To. ${escape(recipient)}</span><strong>${escape(message)}</strong><small class="love-card-church-name">${escape(brand.name)}</small><i>— 來自 ${escape(signature)} 的誠摯祝福</i><em>${card.reference}</em></div></div>`;}
function lovePage(){const card=DEMO.love.cards[selectedLoveCard];return `<div class="mobile-page love-builder">${hero('把愛傳出去 · 專屬圖卡合成','為好友客製稱呼與祝福，一鍵預覽分享成品。','SHARE THE LOVE')}
  <section class="surface love-preview" id="love-preview">${loveCanvas(card)}</section><div class="love-actions"><button id="download-card">⇩ 長按或下載圖片</button><button id="share-card">LINE 選好友傳圖</button></div>
  <section class="surface"><h3 class="section-title">1. 挑選祝福情境</h3><div class="category-scroll">${DEMO.love.categories.map((c,i)=>`<button class="${i?'':'active'}">${c}</button>`).join('')}</div><div class="scene-heading"><strong>2. 選擇卡片底圖</strong><button id="random-scene">⤨ 隨機換一張</button></div><div class="scene-strip">${DEMO.love.cards.map((item,index)=>`<button class="scene-thumb scene-${item.tone} ${index===selectedLoveCard?'active':''}" data-love-card="${index}" aria-label="${item.title}"><span>${item.icon}</span></button>`).join('')}</div><div class="form-grid"><label class="field">收件人稱呼<input id="love-recipient" value="親愛的好友"></label><label class="field">你的署名<input id="love-signature" value="測試家人"></label><label class="field wide">祝福話語<textarea id="love-message">${card.caption}</textarea></label></div><div class="inspiration"><span>快速替換經典金句：</span><button data-inspire="願上帝賜福給你，使你的心滿有平安與力量。">靈感 1</button><button data-inspire="願你所走的每一步，都有恩典陪伴與光照。">靈感 2</button><button data-inspire="知道你最近很努力，願出人意外的平安親自護衛你。">靈感 3</button></div></section><div id="share-response"></div></div>`;}

const pages={menu:menuPage,today:todayPage,help:helpPage,prayer:prayerPage,newcomer:newcomerPage,weekly:weeklyPage,love:lovePage};

function success(title,copy){return `<div class="success-card"><span class="success-icon">✓</span><h3>${title}</h3><p class="muted" style="line-height:1.7">${copy}</p><button class="secondary" data-back>返回預覽表單</button></div>`;}

function wire(){
  view.querySelectorAll('[data-feature]').forEach(link=>link.onclick=event=>{event.preventDefault();go(link.dataset.feature);});
  $('#receive')?.addEventListener('click',()=>$('#today-response').innerHTML=`<p class="response-bubble">${DEMO.today.declaration}</p>`);
  view.querySelectorAll('[data-mood]').forEach(button=>button.onclick=()=>{view.querySelectorAll('[data-mood]').forEach(b=>b.classList.remove('active'));button.classList.add('active');const mood=DEMO.help.moods.find(m=>m.key===button.dataset.mood);$('#mood-card').innerHTML=moodCard(mood);wireMood();});wireMood();
  $('#open-prayer-form')?.addEventListener('click',()=>{const form=$('#prayer-quick-form');form.hidden=!form.hidden;if(!form.hidden)form.scrollIntoView({behavior:'smooth',block:'nearest'});});
  $('#prayer-quick-form')?.addEventListener('submit',event=>{event.preventDefault();const isPublic=event.currentTarget.querySelector('[name="wall-privacy"]:checked')?.value==='public';if(isPublic){addedPrayer=true;prayerCounts.set(99,0);render();}else{event.currentTarget.innerHTML=success('代禱已交給教牧同工','這筆內容不會顯示在公開禱告牆。');wireBack();}});
  wirePrayerOrbs();
  if(feature==='prayer')loadPrayerWeather();
  $('#newcomer-demo')?.addEventListener('submit',event=>{event.preventDefault();event.currentTarget.innerHTML=success('歡迎回家！','正式使用時會建立新朋友登記，並交由本堂同工後續關懷。');wireBack();});
  $('#calendar-demo')?.addEventListener('click',()=>$('#weekly-response').innerHTML='<p class="response-bubble">已模擬加入 9 月 27 日聚會行程。</p>');
  $('#map-demo')?.addEventListener('click',()=>$('#weekly-response').innerHTML='<p class="response-bubble">正式版會開啟本堂設定的地圖網址。</p>');
  view.querySelectorAll('[data-love-card]').forEach(button=>button.onclick=()=>{selectedLoveCard=Number(button.dataset.loveCard);view.querySelectorAll('[data-love-card]').forEach(b=>b.classList.toggle('active',b===button));$('#love-message').value=DEMO.love.cards[selectedLoveCard].caption;updateLovePreview();});
  $('#random-scene')?.addEventListener('click',()=>{selectedLoveCard=(selectedLoveCard+1+Math.floor(Math.random()*(DEMO.love.cards.length-1)))%DEMO.love.cards.length;const button=view.querySelector(`[data-love-card="${selectedLoveCard}"]`);button?.click();button?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});});
  for(const id of ['#love-recipient','#love-signature','#love-message'])$(id)?.addEventListener('input',updateLovePreview);
  view.querySelectorAll('[data-inspire]').forEach(button=>button.onclick=()=>{$('#love-message').value=button.dataset.inspire;updateLovePreview();});
  $('#download-card')?.addEventListener('click',()=>$('#share-response').innerHTML='<p class="response-bubble">已模擬產生高畫質圖卡；正式版可長按儲存或下載。</p>');
  $('#share-card')?.addEventListener('click',openLineFriendPicker);
  view.querySelectorAll('.category-scroll button').forEach(button=>button.onclick=()=>{view.querySelectorAll('.category-scroll button').forEach(b=>b.classList.remove('active'));button.classList.add('active');});
  view.querySelectorAll('[data-chip-group]').forEach(button=>button.onclick=()=>{const group=button.dataset.chipGroup,multi=button.dataset.multi==='true';if(!multi)view.querySelectorAll(`[data-chip-group="${CSS.escape(group)}"]`).forEach(item=>item.classList.remove('active'));button.classList.toggle('active',multi?!button.classList.contains('active'):true);});
}
function paintHalo(button,level){button.dataset.haloLevel=String(level);button.querySelectorAll('.halo-layer').forEach(node=>node.remove());button.insertAdjacentHTML('afterbegin',haloLayers(level));}
function advancePrayerHalo(id,button){const current=prayerHaloState.get(id),stillActive=current?.expiresAt>Date.now(),level=Math.min(7,stillActive?(current.level||0)+1:1);prayerHaloState.set(id,{level,expiresAt:Date.now()+THREE_HOURS});paintHalo(button,level);return level;}
function expirePrayerHalos(){view.querySelectorAll('[data-prayer-id]').forEach(button=>{const id=Number(button.dataset.prayerId);if(!activeHalo(id)&&button.dataset.haloLevel!=='0')paintHalo(button,0);});}
function joinPrayer(button,source='self'){const id=Number(button.dataset.prayerId),next=(prayerCounts.get(id)||0)+1,level=advancePrayerHalo(id,button);prayerCounts.set(id,next);const count=$(`#prayer-count-${id}`);if(count)count.textContent=String(next);button.classList.remove(source==='self'?'just-prayed':'realtime-pulse');void button.offsetWidth;button.classList.add(source==='self'?'just-prayed':'realtime-pulse');setTimeout(()=>button.classList.remove('just-prayed','realtime-pulse'),1350);const status=$('#realtime-status');if(status)status.textContent=source==='self'?`已加入代禱 · 第 ${level} 層光暈保持 3 小時`:`剛剛有家人加入 · 第 ${level} 層光暈`;return level;}
function addWatcher(button){const id=Number(button.dataset.prayerId),next=(prayerWatching.get(id)||0)+1;prayerWatching.set(id,next);button.querySelectorAll('.orbit-track').forEach(node=>node.remove());const lastHalo=[...button.querySelectorAll('.halo-layer')].at(-1);if(lastHalo)lastHalo.insertAdjacentHTML('afterend',orbitDots(next));else button.insertAdjacentHTML('afterbegin',orbitDots(next));const count=$(`#watch-count-${id}`);if(count)count.textContent=`守望 ${next}`;}
function openPrayerDetail(button,level){const sheet=document.createElement('div');sheet.className='prayer-detail-sheet';sheet.innerHTML=`<button class="sheet-backdrop" aria-label="關閉"></button><section><header><span>🙏</span><div><small>${escape(button.dataset.prayerName)}</small><strong>${escape(button.dataset.prayerTitle)}</strong></div><button data-close aria-label="關閉">×</button></header><div class="prayer-confirm">✓ 已加入代禱，禱告的手 ＋1，形成第 ${level} 層光暈</div><p class="prayer-detail-guide">也想留下文字陪伴對方嗎？</p><button class="write-watch-cta" data-write><b>✍️ 寫下守望禱告</b><small>選填 · 送出後成為守望者，圓圈旁會增加一個繞行光點</small></button><form class="watch-prayer-form" hidden><label>給對方的守望禱告<textarea maxlength="300" required placeholder="主啊，求你賜下平安、智慧與力量……"></textarea></label><p>公開禱告文會由同工管理，請避免填寫電話、地址等個人資料。</p><button class="primary">送出守望禱告</button></form><div class="prayer-sheet-response" aria-live="polite"></div></section>`;view.append(sheet);const close=()=>sheet.remove(),response=sheet.querySelector('.prayer-sheet-response');sheet.querySelector('[data-close]').onclick=close;sheet.querySelector('.sheet-backdrop').onclick=close;sheet.querySelector('[data-write]').onclick=event=>{event.currentTarget.hidden=true;const form=sheet.querySelector('.watch-prayer-form');form.hidden=false;form.querySelector('textarea').focus();};sheet.querySelector('form').onsubmit=event=>{event.preventDefault();const message=event.currentTarget.querySelector('textarea').value.trim();if(!message)return;addWatcher(button);response.innerHTML='<div class="prayer-confirm">✓ 守望禱告已送出，小圓點會持續環繞這項代禱</div>';event.currentTarget.hidden=true;const status=$('#realtime-status');if(status)status.textContent='已成為守望者 · 守望禱告同步完成';};}
function wirePrayerOrbs(){view.querySelectorAll('[data-prayer-id]').forEach(button=>button.onclick=()=>{if(button.dataset.prayerAnimating==='true')return;button.dataset.prayerAnimating='true';const level=joinPrayer(button);setTimeout(()=>{delete button.dataset.prayerAnimating;if(feature==='prayer'&&button.isConnected&&!view.querySelector('.prayer-detail-sheet'))openPrayerDetail(button,level);},1450);});if(feature==='prayer'){prayerRealtimeTimer=setInterval(()=>{const buttons=[...view.querySelectorAll('[data-prayer-id]')];if(!buttons.length)return;joinPrayer(buttons[Math.floor(Math.random()*buttons.length)],'realtime');},3600);prayerExpiryTimer=setInterval(expirePrayerHalos,60000);}}
const WEATHER={clear:{codes:[0,1],label:'晴朗微光',icon:'☀',className:'weather-clear'},cloud:{codes:[2,3],label:'雲間柔光',icon:'☁',className:'weather-cloud'},fog:{codes:[45,48],label:'薄霧安靜',icon:'◌',className:'weather-fog'},rain:{codes:[51,53,55,56,57,61,63,65,66,67,80,81,82],label:'恩典細雨',icon:'☂',className:'weather-rain'},storm:{codes:[95,96,99],label:'風雨守望',icon:'ϟ',className:'weather-storm'}};
function weatherMood(code){return Object.values(WEATHER).find(item=>item.codes.includes(code))||{label:'安靜天光',icon:'✦',className:'weather-calm'};}
async function loadPrayerWeather(){const wall=$('#prayer-wall');if(!wall)return;const weatherPreview=params.get('weather');if(weatherPreview&&Object.hasOwn(WEATHER,weatherPreview)){const mood=WEATHER[weatherPreview];wall.classList.remove('weather-calm');wall.classList.add(mood.className,'weather-day');$('#weather-icon').textContent=mood.icon;$('#weather-label').textContent=`台中 · ${mood.label}情境演示`;return;}try{const response=await fetch('https://api.open-meteo.com/v1/forecast?latitude=24.1477&longitude=120.6736&current=temperature_2m,weather_code,is_day,wind_speed_10m&timezone=Asia%2FTaipei',{signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('weather unavailable');const data=await response.json(),current=data.current||{},mood=weatherMood(Number(current.weather_code));if(!wall.isConnected)return;wall.classList.remove('weather-calm');wall.classList.add(mood.className,current.is_day===0?'weather-night':'weather-day');$('#weather-icon').textContent=mood.icon;$('#weather-label').textContent=`台中 ${Number(current.temperature_2m).toFixed(0)}° · ${mood.label}`;}catch{$('#weather-icon').textContent='✦';$('#weather-label').textContent=`台中 · ${dayFallback()}`;}}
function dayFallback(){return DEMO.prayer.days[prayerDay]?.[1]||'安靜天光';}
function updateLovePreview(){const card=DEMO.love.cards[selectedLoveCard],recipient=$('#love-recipient')?.value||'親愛的好友',signature=$('#love-signature')?.value||'測試家人',message=$('#love-message')?.value||card.caption;const area=$('#love-preview');if(area)area.innerHTML=loveCanvas(card,recipient,signature,message);}
function openLineFriendPicker(){const names=[['怡君','🌷'],['俊傑','🌿'],['美玲','🌸'],['家人群組','🏡'],['同事群組','💼'],['小組家人','⛪']],sheet=document.createElement('div');sheet.className='line-share-sheet';sheet.innerHTML=`<button class="sheet-backdrop" aria-label="關閉"></button><section><header><strong>選擇 LINE 好友</strong><button data-close>×</button></header><label class="friend-search">⌕ <input placeholder="搜尋好友或群組"></label><div class="friend-grid">${names.map(([name,icon])=>`<button data-friend><span>${icon}</span><strong>${name}</strong><i>✓</i></button>`).join('')}</div><button class="line-send" disabled>傳送</button><p>這是流程預覽；正式 LIFF 會呼叫 LINE Share Target Picker。</p></section>`;view.append(sheet);const close=()=>sheet.remove(),send=sheet.querySelector('.line-send');sheet.querySelector('[data-close]').onclick=close;sheet.querySelector('.sheet-backdrop').onclick=close;sheet.querySelectorAll('[data-friend]').forEach(friend=>friend.onclick=()=>{friend.classList.toggle('selected');const count=sheet.querySelectorAll('[data-friend].selected').length;send.disabled=!count;send.textContent=count?`傳送給 ${count} 位好友`:'傳送';});send.onclick=()=>{close();$('#share-response').innerHTML='<p class="response-bubble">好友選擇流程完成；預覽模式沒有真的傳送圖片。</p>';};}
function wireMood(){$('#mood-pray')?.addEventListener('click',()=>$('#mood-response').innerHTML='<p class="response-bubble">阿們，願平安與力量臨到你。</p>');}
function wireBack(){view.querySelector('[data-back]')?.addEventListener('click',render);}
function render(){if(prayerRealtimeTimer){clearInterval(prayerRealtimeTimer);prayerRealtimeTimer=null;}if(prayerExpiryTimer){clearInterval(prayerExpiryTimer);prayerExpiryTimer=null;}setTheme();view.innerHTML=pages[feature]();wire();renderControls();}
function renderControls(){setTheme();$('#church-switch').innerHTML=Object.entries(CHURCHES).map(([key,data])=>`<button data-church="${key}" class="${key===church?'active':''}">${data.short}</button>`).join('');$('#church-switch').querySelectorAll('button').forEach(button=>button.onclick=()=>{church=button.dataset.church;updateUrl();render();});const all=[{key:'menu',icon:'▦',title:'圖文選單',subtitle:'六個入口'},...FEATURES];$('#feature-switch').innerHTML=all.map(item=>`<button data-nav="${item.key}" class="${item.key===feature?'active':''}"><span class="nav-icon">${item.icon}</span><span><strong>${item.title}</strong><small>${item.subtitle}</small></span></button>`).join('');$('#feature-switch').querySelectorAll('button').forEach(button=>button.onclick=()=>go(button.dataset.nav));}

$('.line-back').onclick=()=>go('menu');
$('.line-more').onclick=()=>alert('預覽模式：正式 LIFF 會保留 LINE 原生導覽列。');
render();
