import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './admin-auth-config.mjs';
import {PRAYER_TEST_LIFF_IDS,PRAYER_ENDPOINT} from './prayer-wall-config.mjs';
const params=new URLSearchParams(location.search),church=params.get('church'),liffId=PRAYER_TEST_LIFF_IDS[church],$=selector=>document.querySelector(selector);
const validChurch=['M+','SHiNE'].includes(church),db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const preview=['127.0.0.1','localhost'].includes(location.hostname)&&params.get('preview')==='1';
let token='',rows=[],selected=null,busy=false,channel,motionFrame=0,motionLast=0,lifecycleTimer=0;
const motionStates=new Map();
const DAY_MS=24*60*60*1000;
const previewDate=daysAgo=>new Date(Date.now()-daysAgo*DAY_MS).toISOString();
const previewRows=[
 {id:901,author_name:'惠兒',group_name:'大雅小組',title:'家人的身體康復',content:'求主賜下平安與合適的醫治安排，也保守家人的心。',hands_count:4,halo_level:3,created_at:previewDate(.4),comments:[{id:1,author_name:'雅圓',comment_text:'願主的平安與醫治臨到。'}]},
 {id:902,author_name:'王弟兄',group_name:'青年小組',title:'新工作的方向',content:'求主帶領新的工作機會，賜下智慧與合宜的人際關係。',hands_count:6,halo_level:5,created_at:previewDate(2.4),comments:[{id:2,author_name:'主內家人',comment_text:'求神開道路並堅固你的心。'},{id:3,author_name:'淑真',comment_text:'一起守望，願你經歷恩典。'}]},
 {id:903,author_name:'麗珠',group_name:'未編組',title:'家庭和睦',content:'盼望家人彼此理解，重新有溫柔與耐心。',hands_count:3,halo_level:1,created_at:previewDate(4.4),comments:[]},
 {id:904,author_name:'第七天測試',group_name:'未編組',title:'這一圈不應顯示',content:'只用來驗證第七天會自動離開牆面。',hands_count:2,halo_level:0,created_at:previewDate(6.4),comments:[]}
];
const text=(tag,value,className='')=>{const node=document.createElement(tag);node.textContent=value;node.className=className;return node;};
const title=church==='SHiNE'?'火樂教會 · 同心微光':'M＋大雅教會 · 同心微光';$('#church-title').textContent=title;
function status(value){$('#connection').textContent=value;}
function ageProfile(row,now=Date.now()){
  const created=Date.parse(row.created_at),age=Number.isFinite(created)?Math.max(0,now-created):0;
  if(age>=6*DAY_MS)return {visible:false,scale:0,className:'age-expired'};
  if(age>=4*DAY_MS)return {visible:true,scale:.68,className:'age-fading'};
  if(age>=2*DAY_MS)return {visible:true,scale:.84,className:'age-maturing'};
  return {visible:true,scale:1,className:'age-fresh'};
}
function visibleRows(now=Date.now()){return rows.map(row=>({row,profile:ageProfile(row,now)})).filter(item=>item.profile.visible);}
function orbSize(row,profile=ageProfile(row)){return Math.max(86,Math.round((108+Math.min(18,Number(row.hands_count||0)))*profile.scale));}
async function call(action,extra={}){if(preview){if(action==='list')return {ok:true,prayers:previewRows};if(action==='pray'){const row=previewRows.find(item=>item.id===extra.prayer_id);row.hands_count++;row.halo_level=Math.min(7,row.halo_level+1);return {ok:true,hands_count:row.hands_count,halo_level:row.halo_level};}if(action==='comment')return {ok:true,comment:{id:Date.now(),author_name:'預覽守望者',comment_text:extra.comment}};if(action==='create'){const id=Date.now();if(!extra.is_private)previewRows.unshift({id,author_name:'預覽使用者',group_name:'大雅小組',title:extra.title,content:extra.content,hands_count:0,halo_level:0,comments:[]});return {ok:true,id,is_private:extra.is_private};}}const response=await fetch(PRAYER_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(15000),body:JSON.stringify({action,church,idToken:token,...extra})});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok!==true)throw new Error(data.error||'unavailable');return data;}
function motionBounds(sky,node,state){const halo=Math.min(38,Number(state.halo||0)*5+3),radius=node.offsetWidth/2+halo,width=sky.clientWidth,height=sky.clientHeight;return {radius,minX:radius+5,maxX:Math.max(radius+5,width-radius-5),minY:Math.min(height/2,142+radius),maxY:Math.max(Math.min(height/2,142+radius),height-radius-54)};}
function seedMotion(row,index,total,sky,node){const seed=(Number(row.id)*2654435761)>>>0,columns=sky.clientWidth<520?2:3,rowIndex=Math.floor(index/columns),column=index%columns,rowCount=Math.max(1,Math.ceil(total/columns)),bounds=motionBounds(sky,node,{halo:row.halo_level}),spanX=Math.max(1,bounds.maxX-bounds.minX),spanY=Math.max(1,bounds.maxY-bounds.minY),speed=18+(seed%13),angle=.42+((seed>>>8)%70)/100;return {x:bounds.minX+spanX*(column+.5)/Math.min(columns,total),y:bounds.minY+spanY*(rowIndex+.5)/rowCount,vx:(index%2?-1:1)*Math.cos(angle)*speed,vy:((seed>>>17)%2?-1:1)*Math.sin(angle)*speed,halo:Number(row.halo_level||0)};}
function runMotion(sky){cancelAnimationFrame(motionFrame);motionLast=0;const tick=time=>{const dt=motionLast?Math.min(.034,(time-motionLast)/1000):0;motionLast=time;const moving=[...sky.querySelectorAll('.prayer-orb')].map(node=>({node,state:motionStates.get(node.dataset.id)})).filter(item=>item.state);for(const item of moving){const {node,state}=item,bounds=motionBounds(sky,node,state);state.x+=state.vx*dt;state.y+=state.vy*dt;if(state.x<=bounds.minX){state.x=bounds.minX;state.vx=Math.abs(state.vx);}else if(state.x>=bounds.maxX){state.x=bounds.maxX;state.vx=-Math.abs(state.vx);}if(state.y<=bounds.minY){state.y=bounds.minY;state.vy=Math.abs(state.vy);}else if(state.y>=bounds.maxY){state.y=bounds.maxY;state.vy=-Math.abs(state.vy);}}for(let i=0;i<moving.length;i++)for(let j=i+1;j<moving.length;j++){const a=moving[i],b=moving[j],ab=motionBounds(sky,a.node,a.state),bb=motionBounds(sky,b.node,b.state),dx=b.state.x-a.state.x,dy=b.state.y-a.state.y,distance=Math.hypot(dx,dy)||1,minimum=ab.radius+bb.radius+6;if(distance>=minimum)continue;const nx=dx/distance,ny=dy/distance,overlap=(minimum-distance)/2;a.state.x-=nx*overlap;a.state.y-=ny*overlap;b.state.x+=nx*overlap;b.state.y+=ny*overlap;const approach=(b.state.vx-a.state.vx)*nx+(b.state.vy-a.state.vy)*ny;if(approach<0){a.state.vx+=approach*nx;a.state.vy+=approach*ny;b.state.vx-=approach*nx;b.state.vy-=approach*ny;}}for(const {node,state} of moving){node.style.left=state.x+'px';node.style.top=state.y+'px';}motionFrame=requestAnimationFrame(tick);};motionFrame=requestAnimationFrame(tick);}
function render(){const sky=$('#sky');sky.replaceChildren();let total=0;const displayed=visibleRows();if(!displayed.length){motionStates.clear();cancelAnimationFrame(motionFrame);const empty=text('div','','empty');empty.append(text('span','🕊️'),text('strong','目前沒有公開代禱'),text('small','按右上角提出第一項代禱'));sky.append(empty);$('#total').textContent='0';return;}const activeIds=new Set(displayed.map(({row})=>String(row.id)));for(const id of motionStates.keys())if(!activeIds.has(id))motionStates.delete(id);const buttons=[];displayed.forEach(({row,profile},index)=>{total+=Number(row.hands_count||0);const button=document.createElement('button');button.type='button';button.className=`prayer-orb ${profile.className}`;button.dataset.id=row.id;button.style.setProperty('--size',orbSize(row,profile)+'px');for(let level=1;level<=Math.min(7,Number(row.halo_level||0));level++)button.append(text('i','',`halo h${level}`));for(let i=0;i<Math.min(3,row.comments?.length||0);i++){const orbit=text('span','','orbit');orbit.style.animationDelay=(-i*1.6)+'s';orbit.append(text('i'));button.append(orbit);}button.append(text('span',row.author_name||'主內家人','prayer-name'),text('strong',row.title||'代禱事項'));const reactions=text('span','','reactions');reactions.append(text('b','🙏 '+Number(row.hands_count||0)),document.createTextNode(row.comments?.length?'　● '+row.comments.length:''));button.append(reactions);button.onclick=()=>pray(row,button);sky.append(button);buttons.push({row,index,button});});for(const {row,index,button} of buttons){let state=motionStates.get(String(row.id));if(!state)state=seedMotion(row,index,displayed.length,sky,button);state.halo=Number(row.halo_level||0);motionStates.set(String(row.id),state);}$('#total').textContent=String(total);runMotion(sky);}
function syncOrb(row,button=document.querySelector(`[data-id="${row.id}"]`)){if(!button)return;const profile=ageProfile(row);if(!profile.visible){render();return;}button.style.setProperty('--size',orbSize(row,profile)+'px');button.querySelector('.reactions b').textContent='🙏 '+Number(row.hands_count||0);button.querySelector('.reactions').childNodes[1].textContent=row.comments?.length?'　● '+row.comments.length:'';const existing=button.querySelectorAll('.halo').length;for(let level=existing+1;level<=Math.min(7,Number(row.halo_level||0));level++)button.prepend(text('i','',`halo h${level}`));button.querySelectorAll('.orbit').forEach(node=>node.remove());for(let i=0;i<Math.min(3,row.comments?.length||0);i++){const orbit=text('span','','orbit');orbit.style.animationDelay=(-i*1.6)+'s';orbit.append(text('i'));button.prepend(orbit);}$('#total').textContent=String(visibleRows().reduce((sum,item)=>sum+Number(item.row.hands_count||0),0));}
async function load({quiet=false}={}){if(!quiet)status('為代禱預備中…');try{const data=await call('list');rows=data.prayers||[];render();if(!quiet)status('讓我們同心守望');}catch(error){status(error.message==='login_required'?'請從教會 LINE 選單開啟':'暫時無法載入，請稍後再試');}}
async function pray(row,button){if(busy)return;busy=true;button.classList.add('just-prayed');try{const result=await call('pray',{prayer_id:row.id,request_id:crypto.randomUUID()});row.hands_count=result.hands_count;row.halo_level=result.halo_level;syncOrb(row,button);selected=row;setTimeout(()=>openDetail(row,result.halo_level),1400);}catch{status('這項代禱目前無法加入，請重新整理');}finally{setTimeout(()=>button.classList.remove('just-prayed'),1400);busy=false;}}
function openDetail(row,level){selected=row;$('#detail-author').textContent=(row.author_name||'主內家人')+(row.group_name?' · '+row.group_name:'');$('#detail-title').textContent=row.title;$('#detail-content').textContent=row.content;$('#joined').textContent=`✓ 已加入代禱，禱告的手 ＋1，目前形成第 ${level} 層光暈`;$('#watch-form').hidden=true;$('#watch-open').hidden=false;$('#sheet-status').textContent='';renderComments(row.comments||[]);$('#sheet').hidden=false;}
function renderComments(items){const area=$('#comments');area.replaceChildren();for(const item of items){const card=text('article','','comment');card.append(text('strong',item.author_name||'守望者'),text('p',item.comment_text||''));area.append(card);}}
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>{$('#sheet').hidden=true;});$('#watch-open').onclick=()=>{$('#watch-open').hidden=true;$('#watch-form').hidden=false;$('#watch-text').focus();};
$('#watch-form').onsubmit=async event=>{event.preventDefault();if(busy||!selected)return;const comment=$('#watch-text').value.trim();if(comment.length<2)return;busy=true;try{const data=await call('comment',{prayer_id:selected.id,comment,request_id:crypto.randomUUID()});selected.comments=[...(selected.comments||[]),data.comment];syncOrb(selected);renderComments(selected.comments);$('#watch-text').value='';event.currentTarget.hidden=true;$('#sheet-status').textContent='✓ 守望禱告已送出，光點會持續環繞這項代禱。';}catch(error){$('#sheet-status').textContent=error.message==='rate_limited'?'操作太快了，請稍候一分鐘再試。':'尚未送出，請稍後重試。';}finally{busy=false;}};
$('#create-open').onclick=()=>{$('#create').hidden=false;};document.querySelectorAll('[data-create-close]').forEach(button=>button.onclick=()=>{$('#create').hidden=true;});
$('#create-form').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;$('#create-status').textContent='正在安全送出…';try{const is_private=form.elements.privacy.value==='private';await call('create',{title:$('#new-title').value,content:$('#new-content').value,is_private,request_id:crypto.randomUUID()});form.reset();$('#create').hidden=true;status(is_private?'私密代禱已送交教牧同工':'公開代禱已加入牆面');if(!is_private)await load({quiet:true});}catch(error){$('#create-status').textContent=error.message==='rate_limited'?'操作太快了，請稍候一分鐘再試。':'尚未送出，請檢查網路後重試。';}finally{busy=false;button.disabled=false;}};
async function weather(){try{const response=await fetch('https://api.open-meteo.com/v1/forecast?latitude=24.1477&longitude=120.6736&current=weather_code,is_day&timezone=Asia%2FTaipei',{signal:AbortSignal.timeout(6000)}),data=await response.json(),code=Number(data.current?.weather_code),kind=code>=95?'storm':code>=51?'rain':code>=45?'fog':code>=1?'cloud':'clear',labels={storm:['⛈️','台中 · 雷雨'],rain:['🌧️','台中 · 雨天'],fog:['🌫️','台中 · 霧氣'],cloud:['☁️','台中 · 多雲'],clear:['☀️','台中 · 晴朗']};$('#wall').className='wall weather-'+kind;[$('#weather-icon').textContent,$('#weather-label').textContent]=labels[kind];}catch{$('#weather-label').textContent='台中 · 此刻微光';}}
async function start(){weather();lifecycleTimer=window.setInterval(render,15*60*1000);if(!validChurch){status('請從所屬教會的選單重新開啟');return;}if(preview){token='preview';await load();status('讓我們同心守望');return;}if(!liffId){status('此功能正在預備中');return;}try{await window.liff.init({liffId});if(!window.liff.isLoggedIn()){window.liff.login();return;}token=window.liff.getIDToken()||'';if(!token)throw new Error();await load();channel=db.channel('prayer-wall-'+church).on('postgres_changes',{event:'INSERT',schema:'public',table:'prayer_activity',filter:'church_id=eq.'+church},payload=>{const target=document.querySelector(`[data-id="${payload.new.prayer_id}"]`);target?.classList.add('community');setTimeout(()=>target?.classList.remove('community'),1200);load({quiet:true});}).subscribe(state=>{if(state==='SUBSCRIBED')status('讓我們同心守望');});}catch{status('暫時無法開啟，請稍後再試');}}
window.addEventListener('pagehide',()=>{cancelAnimationFrame(motionFrame);clearInterval(lifecycleTimer);if(channel)db.removeChannel(channel);});start();
