import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './admin-auth-config.mjs';
import {PRAYER_TEST_LIFF_IDS,PRAYER_ENDPOINT} from './prayer-wall-config.mjs';
const params=new URLSearchParams(location.search),church=params.get('church'),liffId=PRAYER_TEST_LIFF_IDS[church],$=selector=>document.querySelector(selector);
const validChurch=['M+','SHiNE'].includes(church),db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const preview=['127.0.0.1','localhost'].includes(location.hostname)&&params.get('preview')==='1';
let token='',rows=[],selected=null,busy=false,channel;
const previewRows=[
 {id:901,author_name:'惠兒',group_name:'大雅小組',title:'家人的身體康復',content:'求主賜下平安與合適的醫治安排，也保守家人的心。',hands_count:4,halo_level:3,comments:[{id:1,author_name:'雅圓',comment_text:'願主的平安與醫治臨到。'}]},
 {id:902,author_name:'王弟兄',group_name:'青年小組',title:'新工作的方向',content:'求主帶領新的工作機會，賜下智慧與合宜的人際關係。',hands_count:6,halo_level:5,comments:[{id:2,author_name:'主內家人',comment_text:'求神開道路並堅固你的心。'},{id:3,author_name:'淑真',comment_text:'一起守望，願你經歷恩典。'}]},
 {id:903,author_name:'麗珠',group_name:'未編組',title:'家庭和睦',content:'盼望家人彼此理解，重新有溫柔與耐心。',hands_count:3,halo_level:1,comments:[]}
];
const text=(tag,value,className='')=>{const node=document.createElement(tag);node.textContent=value;node.className=className;return node;};
const title=church==='SHiNE'?'火樂教會 · 同心微光':'M＋大雅教會 · 同心微光';$('#church-title').textContent=title;
function status(value){$('#connection').textContent=value;}
async function call(action,extra={}){if(preview){if(action==='list')return {ok:true,prayers:previewRows};if(action==='pray'){const row=previewRows.find(item=>item.id===extra.prayer_id);row.hands_count++;row.halo_level=Math.min(7,row.halo_level+1);return {ok:true,hands_count:row.hands_count,halo_level:row.halo_level};}if(action==='comment')return {ok:true,comment:{id:Date.now(),author_name:'預覽守望者',comment_text:extra.comment}};if(action==='create'){const id=Date.now();if(!extra.is_private)previewRows.unshift({id,author_name:'預覽使用者',group_name:'大雅小組',title:extra.title,content:extra.content,hands_count:0,halo_level:0,comments:[]});return {ok:true,id,is_private:extra.is_private};}}const response=await fetch(PRAYER_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(15000),body:JSON.stringify({action,church,idToken:token,...extra})});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok!==true)throw new Error(data.error||'unavailable');return data;}
function position(id,index){let n=(Number(id)*2654435761)>>>0;const x=16+(n%68),y=14+(((n>>>8)+index*23)%72);return {x,y};}
function render(){const sky=$('#sky');sky.replaceChildren();let total=0;if(!rows.length){const empty=text('div','','empty');empty.append(text('span','🕊️'),text('strong','目前沒有公開代禱'),text('small','按右上角提出第一項代禱'));sky.append(empty);$('#total').textContent='0';return;}rows.forEach((row,index)=>{total+=Number(row.hands_count||0);const pos=position(row.id,index),button=document.createElement('button');button.type='button';button.className='prayer-orb';button.dataset.id=row.id;button.style.setProperty('--x',pos.x+'%');button.style.setProperty('--y',pos.y+'%');button.style.setProperty('--size',(92+Math.min(20,Number(row.hands_count||0)))+'px');for(let level=1;level<=Math.min(7,Number(row.halo_level||0));level++)button.append(text('i','',`halo h${level}`));for(let i=0;i<Math.min(3,row.comments?.length||0);i++){const orbit=text('span','','orbit');orbit.style.animationDelay=(-i*1.6)+'s';orbit.append(text('i'));button.append(orbit);}button.append(text('span',row.author_name||'主內家人','prayer-name'),text('strong',row.title||'代禱事項'));const reactions=text('span','','reactions');reactions.append(text('b','🙏 '+Number(row.hands_count||0)),document.createTextNode(row.comments?.length?'　● '+row.comments.length:''));button.append(reactions);button.onclick=()=>pray(row,button);sky.append(button);});$('#total').textContent=String(total);}
function syncOrb(row,button=document.querySelector(`[data-id="${row.id}"]`)){if(!button)return;button.style.setProperty('--size',(92+Math.min(20,Number(row.hands_count||0)))+'px');button.querySelector('.reactions b').textContent='🙏 '+Number(row.hands_count||0);button.querySelector('.reactions').childNodes[1].textContent=row.comments?.length?'　● '+row.comments.length:'';const existing=button.querySelectorAll('.halo').length;for(let level=existing+1;level<=Math.min(7,Number(row.halo_level||0));level++)button.prepend(text('i','',`halo h${level}`));button.querySelectorAll('.orbit').forEach(node=>node.remove());for(let i=0;i<Math.min(3,row.comments?.length||0);i++){const orbit=text('span','','orbit');orbit.style.animationDelay=(-i*1.6)+'s';orbit.append(text('i'));button.prepend(orbit);}$('#total').textContent=String(rows.reduce((sum,item)=>sum+Number(item.hands_count||0),0));}
async function load({quiet=false}={}){if(!quiet)status('即時同步中…');try{const data=await call('list');rows=data.prayers||[];render();if(!quiet)status('即時同步已連線');}catch(error){status(error.message==='login_required'?'請使用 LINE 開啟此功能':'暫時無法載入，請稍後再試');}}
async function pray(row,button){if(busy)return;busy=true;button.classList.add('just-prayed');try{const result=await call('pray',{prayer_id:row.id,request_id:crypto.randomUUID()});row.hands_count=result.hands_count;row.halo_level=result.halo_level;syncOrb(row,button);selected=row;setTimeout(()=>openDetail(row,result.halo_level),1400);}catch{status('這項代禱目前無法加入，請重新整理');}finally{setTimeout(()=>button.classList.remove('just-prayed'),1400);busy=false;}}
function openDetail(row,level){selected=row;$('#detail-author').textContent=(row.author_name||'主內家人')+(row.group_name?' · '+row.group_name:'');$('#detail-title').textContent=row.title;$('#detail-content').textContent=row.content;$('#joined').textContent=`✓ 已加入代禱，禱告的手 ＋1，目前形成第 ${level} 層光暈`;$('#watch-form').hidden=true;$('#watch-open').hidden=false;$('#sheet-status').textContent='';renderComments(row.comments||[]);$('#sheet').hidden=false;}
function renderComments(items){const area=$('#comments');area.replaceChildren();for(const item of items){const card=text('article','','comment');card.append(text('strong',item.author_name||'守望者'),text('p',item.comment_text||''));area.append(card);}}
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>{$('#sheet').hidden=true;});$('#watch-open').onclick=()=>{$('#watch-open').hidden=true;$('#watch-form').hidden=false;$('#watch-text').focus();};
$('#watch-form').onsubmit=async event=>{event.preventDefault();if(busy||!selected)return;const comment=$('#watch-text').value.trim();if(comment.length<2)return;busy=true;try{const data=await call('comment',{prayer_id:selected.id,comment,request_id:crypto.randomUUID()});selected.comments=[...(selected.comments||[]),data.comment];syncOrb(selected);renderComments(selected.comments);$('#watch-text').value='';event.currentTarget.hidden=true;$('#sheet-status').textContent='✓ 守望禱告已送出，光點會持續環繞這項代禱。';}catch(error){$('#sheet-status').textContent=error.message==='rate_limited'?'操作太快了，請稍候一分鐘再試。':'尚未送出，請稍後重試。';}finally{busy=false;}};
$('#create-open').onclick=()=>{$('#create').hidden=false;};document.querySelectorAll('[data-create-close]').forEach(button=>button.onclick=()=>{$('#create').hidden=true;});
$('#create-form').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;$('#create-status').textContent='正在安全送出…';try{const is_private=form.elements.privacy.value==='private';await call('create',{title:$('#new-title').value,content:$('#new-content').value,is_private,request_id:crypto.randomUUID()});form.reset();$('#create').hidden=true;status(is_private?'私密代禱已送交教牧同工':'公開代禱已加入牆面');if(!is_private)await load({quiet:true});}catch(error){$('#create-status').textContent=error.message==='rate_limited'?'操作太快了，請稍候一分鐘再試。':'尚未送出，請檢查網路後重試。';}finally{busy=false;button.disabled=false;}};
async function weather(){try{const response=await fetch('https://api.open-meteo.com/v1/forecast?latitude=24.1477&longitude=120.6736&current=weather_code,is_day&timezone=Asia%2FTaipei',{signal:AbortSignal.timeout(6000)}),data=await response.json(),code=Number(data.current?.weather_code),kind=code>=95?'storm':code>=51?'rain':code>=45?'fog':code>=1?'cloud':'clear',labels={storm:['⛈️','台中 · 雷雨'],rain:['🌧️','台中 · 雨天'],fog:['🌫️','台中 · 霧氣'],cloud:['☁️','台中 · 多雲'],clear:['☀️','台中 · 晴朗']};$('#wall').className='wall weather-'+kind;[$('#weather-icon').textContent,$('#weather-label').textContent]=labels[kind];}catch{$('#weather-label').textContent='台中 · 柔和預設場景';}}
async function start(){weather();if(!validChurch){status('網址缺少正確堂會');return;}if(preview){token='preview';await load();status('本機畫面預覽 · 不會寫入資料庫');return;}if(!liffId){status('等待建立本堂測試 LIFF，尚未連接正式系統');return;}try{await window.liff.init({liffId});if(!window.liff.isLoggedIn()){window.liff.login();return;}token=window.liff.getIDToken()||'';if(!token)throw new Error();await load();channel=db.channel('prayer-wall-'+church).on('postgres_changes',{event:'INSERT',schema:'public',table:'prayer_activity',filter:'church_id=eq.'+church},payload=>{const target=document.querySelector(`[data-id="${payload.new.prayer_id}"]`);target?.classList.add('community');setTimeout(()=>target?.classList.remove('community'),1200);load({quiet:true});}).subscribe(state=>{if(state==='SUBSCRIBED')status('即時同步已連線');});}catch{status('LINE 登入或即時連線失敗，請重新開啟');}}
window.addEventListener('pagehide',()=>{if(channel)db.removeChannel(channel);});start();
