import {db} from './admin-db.mjs';
import {COMMON,M_PLUS,SHINE,listSchedules,listScheduleMembers,saveSchedule,listRolePreferences,saveRolePreferences} from './schedule-management.mjs?v=20260924-roles1';

const values=new URLSearchParams(location.search).getAll('church'),church=values.length===1?values[0]:null;
const $=s=>document.querySelector(s),status=$('#status'),editor=$('#editor'),records=$('#records'),roleSettings=$('#roleSettings');
const churchName=church==='M+'?'M＋大雅教會':'火樂教會';
const logoSrc=church==='M+'?'assets/brands/mplus-logo-white.png':'assets/brands/shine-logo.png';
let schedules=[],members=[],rolePreferences=[],busy=false;
const preview=location.hostname==='127.0.0.1'&&new URLSearchParams(location.search).get('preview')==='1';
const previewRows=[
  {id:0,church_id:church,service_date:'2026/09/20',event:'主日崇拜',speaker:'劉偉華 牧師',worship_leader:'敬拜團',tech_sound:'張育梓',tech_video:'曾軒佑',usher1:'雷亞蓁',usher2:'小喵',presider:'戴世華',prayer:'曾恩茹',sunday_school:'詹惠怡',sunday_school_ta:'曾以路'},
  {id:1,church_id:church,service_date:'2026-09-27',event:'主日崇拜｜在盼望中重新得力',speaker:'吳俊璋 牧師',worship_leader:'邵鈺庭',tech_sound:'陳以諾',tech_video:'林恩慈',usher1:'王雅真',usher2:'張心怡',presider:'李承恩',prayer:'許家豪',sunday_school:'周美玲',sunday_school_ta:'黃品恩',singers:'陳恩惠、林以樂',keyboard:'吳安琪',guitar:'王子恩',bass:'林嘉恩',drums:'張以諾',ushers:'王雅真、張心怡'},
  {id:2,church_id:church,service_date:'2026-10-04',event:'主日崇拜｜恩典夠用',speaker:'特邀講員',worship_leader:'李承恩',tech_sound:'林嘉恩',tech_video:'陳以諾',usher1:'許家豪',usher2:'周美玲',presider:'邵鈺庭',prayer:'張心怡',sunday_school:'黃品恩',sunday_school_ta:'王雅真',singers:'林以樂、吳安琪',keyboard:'陳恩惠',guitar:'王子恩',bass:'張以諾',drums:'許家豪',ushers:'周美玲、黃品恩'},
  {id:3,church_id:church,service_date:'2026-10-11',event:'主日崇拜｜同心同行',speaker:'吳俊璋 牧師',worship_leader:'陳恩惠',tech_sound:'張以諾',tech_video:'林嘉恩',usher1:'黃品恩',usher2:'王雅真',presider:'李承恩',prayer:'邵鈺庭',sunday_school:'周美玲',sunday_school_ta:'張心怡',singers:'吳安琪、王子恩',keyboard:'林以樂',guitar:'許家豪',bass:'陳以諾',drums:'林嘉恩',ushers:'黃品恩、王雅真'}
];
const el=(tag,value='',cls='')=>{const n=document.createElement(tag);n.textContent=value;n.className=cls;return n;};
const labels={event:'聚會主題',speaker:'信息分享',worship_leader:church==='M+'?'敬拜讚美':'敬拜主領',tech_sound:'音控控台',tech_video:church==='M+'?'投影字幕／導播':'直播導播',usher1:'招待一',usher2:'招待二',presider:'司會',prayer:'主日公禱',sunday_school:'兒主老師',sunday_school_ta:'兒主助教',singers:'敬拜歌者',keyboard:'司琴鍵盤',guitar:'木／電吉他',bass:'貝斯手',drums:'爵士鼓手',ushers:'主日招待',transport:'交通服事',communion:'聖餐服事',communion_bread:'聖餐餅',communion_cup:'聖餐杯',wed_prayer:'週三禱告會'};
const icons={speaker:'🎙️',worship_leader:'🎶',tech_sound:'🎚️',tech_video:'🎥',usher1:'👋',usher2:'🤝',presider:'🗣️',prayer:'🙏',sunday_school:'🧒',sunday_school_ta:'🌱',singers:'🎤',keyboard:'🎹',guitar:'🎸',bass:'🎸',drums:'🥁',ushers:'👋',transport:'🚐',communion:'✝️',communion_bread:'🍞',communion_cup:'🍷',wed_prayer:'🕊️'};
const roleKeys=()=>['speaker','worship_leader','tech_sound','tech_video',...(church==='M+'?['usher1','usher2',...M_PLUS]:SHINE)];
const roles=()=>['event',...roleKeys()];
const preferenceFor=key=>rolePreferences.find(item=>item.role_key===key)||{role_key:key,label:labels[key]||key,icon:icons[key]||'✦',is_visible:true,sort_order:999};
const visiblePreferences=()=>rolePreferences.filter(item=>item.is_visible).sort((a,b)=>a.sort_order-b.sort_order);
const visibleRoles=()=>visiblePreferences().map(item=>item.role_key);
const previewPreferences=()=>roleKeys().map((key,index)=>({church_id:church,role_key:key,label:labels[key]||key,icon:icons[key]||'✦',is_visible:!['transport','communion','communion_bread','communion_cup','wed_prayer'].includes(key),sort_order:(index+1)*10}));
const isoDate=value=>{const match=String(value||'').trim().match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/);return match?match[1]+'-'+match[2].padStart(2,'0')+'-'+match[3].padStart(2,'0'):'';};
const parseDate=value=>{const iso=isoDate(value),parts=iso.split('-').map(Number);return iso?new Date(parts[0],parts[1]-1,parts[2],12):null;};
const dateParts=value=>{const d=parseDate(value);if(!d||!Number.isFinite(d.getTime()))return{day:'—',month:'日期',weekday:'待確認',full:'日期待確認'};return{day:String(d.getDate()).padStart(2,'0'),month:(d.getMonth()+1)+'月',weekday:new Intl.DateTimeFormat('zh-TW',{weekday:'long'}).format(d),full:new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(d)}};
const escapeFile=value=>value.replace(/[\\/:*?"<>|\s]+/g,'-');

function memberSelect(key,current=''){const select=document.createElement('select');select.append(new Option('－（未安排）',''));const keyword={worship_leader:'主領',tech_sound:'音控',tech_video:'導播',usher1:'招待',usher2:'招待',presider:'司會',prayer:'禱告',keyboard:'司琴',guitar:'吉他',bass:'貝斯',drums:'鼓'}[key]||'';const sorted=[...members].sort((a,b)=>Number((b.ministry||'').includes(keyword))-Number((a.ministry||'').includes(keyword))||a.name.localeCompare(b.name,'zh-TW'));for(const m of sorted)select.append(new Option(m.name+'（'+(m.group_name||'未編組')+'）',m.name));if(current&&!sorted.some(m=>m.name===current))select.append(new Option(current+'（舊資料）',current));select.value=current||'';return select;}

function openForm(row=null){editor.replaceChildren();editor.hidden=false;const form=document.createElement('form'),grid=el('div','','edit-grid'),date=document.createElement('input'),inputs={};date.type='date';date.value=row?.service_date||'';let wrap=el('label','服事日期');wrap.append(date);grid.append(wrap);for(const key of ['event',...visibleRoles()]){const input=['event','speaker','singers','ushers'].includes(key)?document.createElement('input'):memberSelect(key,row?.[key]||'');if(input.tagName==='INPUT'){input.value=row?.[key]||'';input.maxLength=300;}wrap=el('label',labels[key]);wrap.append(input);grid.append(wrap);inputs[key]=input;}const actions=el('div','','editor-actions'),cancel=el('button','取消','secondary'),save=el('button',row?'儲存更正':'儲存排班');cancel.type='button';cancel.onclick=()=>editor.hidden=true;actions.append(cancel,save);form.append(el('h2',row?'更正服事排班':'新增服事排班'),grid,actions);form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{const payload={service_date:date.value,...Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value]))};await saveSchedule(db,church,payload,row);editor.hidden=true;await load();status.textContent=row?'排班已更正。':'排班已儲存。';}catch(error){status.textContent=error.message;}finally{busy=false;}};editor.append(form);editor.scrollIntoView({behavior:'smooth',block:'start'});date.focus();}

function openRoleSettings(){
  if(!roleSettings.hidden){roleSettings.hidden=true;$('#manageRoles').textContent='管理服事項目';return;}
  const draft=rolePreferences.map(item=>({...item})).sort((a,b)=>a.sort_order-b.sort_order);
  const renderEditor=()=>{
    roleSettings.replaceChildren();
    const heading=el('div','','role-settings-heading');heading.append(el('div','🎛️','role-settings-mark'),el('div','','role-settings-copy'));
    heading.lastChild.append(el('h2','服事項目管理'),el('p','開關控制是否呈現；使用箭頭調整順序，也可以修改圖示與顯示名稱。'));
    const list=el('div','','role-preference-list');
    draft.forEach((item,index)=>{
      const row=el('div','',`role-preference-row${item.is_visible?'':' is-hidden'}`),order=el('span',String(index+1),'role-order');
      const icon=document.createElement('input');icon.className='role-icon-input';icon.value=item.icon;icon.maxLength=12;icon.setAttribute('aria-label',item.label+'圖示');icon.oninput=()=>item.icon=icon.value;
      const name=document.createElement('input');name.className='role-name-input';name.value=item.label;name.maxLength=30;name.setAttribute('aria-label','服事項目名稱');name.oninput=()=>item.label=name.value;
      const toggle=el('label','','role-visibility'),check=document.createElement('input'),track=el('span','','toggle-track'),stateText=el('span',item.is_visible?'顯示':'隱藏');check.type='checkbox';check.checked=item.is_visible;check.onchange=()=>{item.is_visible=check.checked;row.classList.toggle('is-hidden',!item.is_visible);stateText.textContent=item.is_visible?'顯示':'隱藏';};toggle.append(check,track,stateText);
      const moves=el('div','','role-moves'),up=el('button','↑','secondary'),down=el('button','↓','secondary');up.type=down.type='button';up.setAttribute('aria-label','向上移動');down.setAttribute('aria-label','向下移動');up.disabled=index===0;down.disabled=index===draft.length-1;up.onclick=()=>{[draft[index-1],draft[index]]=[draft[index],draft[index-1]];renderEditor();};down.onclick=()=>{[draft[index+1],draft[index]]=[draft[index],draft[index+1]];renderEditor();};moves.append(up,down);row.append(order,icon,name,toggle,moves);list.append(row);
    });
    const actions=el('div','','role-settings-actions'),cancel=el('button','取消','secondary'),save=el('button','儲存呈現設定');cancel.type=save.type='button';cancel.onclick=()=>{roleSettings.hidden=true;$('#manageRoles').textContent='管理服事項目';};save.onclick=async()=>{if(busy)return;busy=true;save.disabled=true;try{rolePreferences=preview?draft.map((item,index)=>({...item,sort_order:(index+1)*10})):await saveRolePreferences(db,church,draft);render();configureExports();roleSettings.hidden=true;$('#manageRoles').textContent='管理服事項目';status.textContent=preview?'預覽設定已套用（不寫入資料庫）。':'服事項目呈現設定已儲存。';}catch(error){status.textContent=error.message;save.disabled=false;}finally{busy=false;}};actions.append(cancel,save);
    roleSettings.append(heading,list,actions);
  };
  renderEditor();roleSettings.hidden=false;$('#manageRoles').textContent='收起項目管理';roleSettings.scrollIntoView({behavior:'smooth',block:'start'});
}

function weekStartIso(){const today=new Date(),day=today.getDay()||7,monday=new Date(today.getFullYear(),today.getMonth(),today.getDate()-day+1,12);return monday.getFullYear()+'-'+String(monday.getMonth()+1).padStart(2,'0')+'-'+String(monday.getDate()).padStart(2,'0');}
function weekEndIso(){const start=parseDate(weekStartIso()),end=new Date(start.getFullYear(),start.getMonth(),start.getDate()+6,12);return end.getFullYear()+'-'+String(end.getMonth()+1).padStart(2,'0')+'-'+String(end.getDate()).padStart(2,'0');}
function roleTone(key){if(['speaker','worship_leader','presider','prayer','wed_prayer','singers','keyboard','guitar','bass','drums'].includes(key))return'role-item--worship';if(['tech_sound','tech_video'].includes(key))return'role-item--tech';if(['usher1','usher2','ushers','transport'].includes(key))return'role-item--welcome';if(['sunday_school','sunday_school_ta','communion','communion_bread','communion_cup'].includes(key))return'role-item--kids';return'';}
function roleLabel(pref){const line=el('span','','role-label'),icon=el('i',pref.icon,'role-icon');icon.setAttribute('aria-hidden','true');line.append(icon,document.createTextNode(pref.label));return line;}
function scheduleCard(row,index=0,isPast=false){const d=dateParts(row.service_date),card=el('article','','schedule-card'+(index===0&&!isPast?' schedule-card--featured':'')+(isPast?' schedule-card--past':'')),date=el('div','','schedule-date');date.append(el('strong',d.day),el('span',d.month+' · '+d.weekday),el('small',isoDate(row.service_date)||'日期待確認'));const content=el('div','','schedule-content'),heading=el('div','','schedule-title-row'),copy=el('div');if(index===0&&!isPast)heading.append(el('span',isoDate(row.service_date)<=weekEndIso()?'本週聚會':'下一場聚會','schedule-now'));copy.append(el('h3',row.event||'主日崇拜'));heading.prepend(copy);content.append(heading);const grid=el('div','','role-grid');for(const pref of visiblePreferences()){const key=pref.role_key,value=row[key],item=el('div','',('role-item '+roleTone(key)).trim());item.append(roleLabel(pref),el('strong',value&&value!=='－'?value:'尚未安排'));grid.append(item);}content.append(grid);const edit=el('button','調整服事','secondary');edit.onclick=()=>openForm(row);card.append(date,content,edit);return card;}
function render(){const cutoff=weekStartIso(),upcoming=schedules.filter(row=>isoDate(row.service_date)>=cutoff),past=schedules.filter(row=>isoDate(row.service_date)<cutoff).reverse(),history=document.querySelector('#history'),historyRecords=document.querySelector('#historyRecords');records.replaceChildren(...upcoming.map((row,index)=>scheduleCard(row,index,false)));if(!upcoming.length)records.append(el('div','本週之後目前還沒有服事排班。','schedule-empty'));historyRecords.replaceChildren(...past.map((row,index)=>scheduleCard(row,index,true)));history.hidden=!past.length;document.querySelector('#historyCount').textContent=past.length?'共 '+past.length+' 筆':'';document.querySelector('#rangeNote').textContent=upcoming.length?'已排定 '+upcoming.length+' 場未來聚會':'';}

function configureExports(){const week=$('#weekPick'),month=$('#monthPick'),today=new Date(),current=today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0');week.replaceChildren();for(const row of schedules){const d=dateParts(row.service_date);week.append(new Option(d.full+'｜'+(row.event||'主日聚會'),row.service_date));}const now=current+'-'+String(today.getDate()).padStart(2,'0'),future=schedules.find(row=>isoDate(row.service_date)>=now)||schedules.at(-1);if(future)week.value=future.service_date;const futureMonth=future?isoDate(future.service_date).slice(0,7):current;month.value=schedules.some(row=>isoDate(row.service_date).startsWith(current))?current:futureMonth;$('#weekPng').disabled=!schedules.length;$('#monthPng').disabled=!schedules.length;}

function roundRect(ctx,x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();}
function canvasText(ctx,text,x,y,maxWidth,lineHeight,maxLines=3){const chars=[...String(text||'')],lines=[];let line='';for(const char of chars){const test=line+char;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=char;}else line=test;}if(line)lines.push(line);const shown=lines.slice(0,maxLines);if(lines.length>maxLines)shown[maxLines-1]=shown[maxLines-1].slice(0,-1)+'…';shown.forEach((value,index)=>ctx.fillText(value,x,y+index*lineHeight));return shown.length*lineHeight;}
async function image(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src;});}
function canvasBase(height,title,subtitle){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=height;const ctx=canvas.getContext('2d');const bg=ctx.createLinearGradient(0,0,1080,height);bg.addColorStop(0,'#fbf6ef');bg.addColorStop(1,'#ead9c8');ctx.fillStyle=bg;ctx.fillRect(0,0,1080,height);roundRect(ctx,52,48,976,190,38,'#76503a');ctx.fillStyle='#fff';ctx.font='800 42px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText(title,92,130);ctx.fillStyle='#f9dfc7';ctx.font='500 24px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText(subtitle,92,178);return{canvas,ctx};}
async function brandLogo(ctx){try{const img=await image(logoSrc),ratio=img.width/img.height,maxW=church==='M+'?205:245,maxH=70;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio;}if(church==='SHiNE')roundRect(ctx,932-w,58,w+36,h+36,18,'#fff6ed');ctx.drawImage(img,950-w,76,w,h);}catch{ctx.fillStyle='#fff';ctx.font='800 28px system-ui';ctx.textAlign='right';ctx.fillText(churchName,950,118);ctx.textAlign='left';}}
function servicePanel(ctx,row,x,y,w,compact=false){const h=compact?380:900;roundRect(ctx,x,y,w,h,30,'#fffdf9');const d=dateParts(row.service_date);roundRect(ctx,x+24,y+24,compact?185:220,52,26,'#f2e0ce');ctx.fillStyle='#8b5739';ctx.font='750 22px -apple-system,BlinkMacSystemFont,"PingFang TC",sans-serif';ctx.fillText(d.month+' '+d.day+'日',x+45,y+58);ctx.fillStyle='#846c5d';ctx.font='600 19px -apple-system,BlinkMacSystemFont,"PingFang TC",sans-serif';ctx.fillText(d.weekday,x+(compact?225:270),y+58);ctx.fillStyle='#3f322a';ctx.font='800 30px -apple-system,BlinkMacSystemFont,"PingFang TC",sans-serif';canvasText(ctx,row.event||'主日聚會',x+30,y+120,w-60,38,1);const entries=visiblePreferences(),columns=compact?4:2,colW=(w-60)/columns,rowH=compact?54:78;entries.forEach((pref,index)=>{const cx=x+30+(index%columns)*colW,cy=y+(compact?170:185)+Math.floor(index/columns)*rowH;ctx.fillStyle='#a08d7f';ctx.font='650 15px -apple-system,BlinkMacSystemFont,"PingFang TC",sans-serif';ctx.fillText(pref.icon+' '+pref.label,cx,cy);ctx.fillStyle='#45372e';ctx.font='750 21px -apple-system,BlinkMacSystemFont,"PingFang TC",sans-serif';canvasText(ctx,row[pref.role_key]||'—',cx,cy+27,colW-22,26,1);});return h;}
function weeklyGroups(row){const order=new Map(visiblePreferences().map((item,index)=>[item.role_key,index])),visible=new Set(visibleRoles()),items=keys=>keys.filter(key=>visible.has(key)).sort((a,b)=>(order.get(a)||0)-(order.get(b)||0)).map(key=>[key,preferenceFor(key).icon+' '+preferenceFor(key).label,row[key]]);const groups=[
  {title:'聚會帶領',icon:'✨',tone:'#f7e7d8',accent:'#bc7549',items:items(['speaker','worship_leader','presider','prayer','wed_prayer'])},
  {title:church==='SHiNE'?'敬拜團隊':'教會服事',icon:church==='SHiNE'?'🎵':'🌿',tone:'#f7ecdf',accent:'#d28a48',items:items(church==='SHiNE'?['singers','keyboard','guitar','bass','drums']:['sunday_school','sunday_school_ta','transport','communion','communion_bread','communion_cup'])},
  {title:'影音技術',icon:'🎛️',tone:'#eaf3f1',accent:'#55998e',items:items(['tech_sound','tech_video'])},
  {title:'迎賓接待',icon:'🤝',tone:'#f8eae6',accent:'#cf7f70',items:items(church==='M+'?['usher1','usher2']:['ushers'])}
].filter(group=>group.items.length);return groups.slice(0,4);}
function canvasGroup(ctx,group,x,y,w,h){roundRect(ctx,x,y,w,h,28,'#fffdf9');roundRect(ctx,x+22,y+21,46,46,15,group.tone);ctx.fillStyle=group.accent;ctx.font='800 22px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.textAlign='center';ctx.fillText(group.icon,x+45,y+52);ctx.textAlign='left';ctx.fillStyle='#44352c';ctx.font='800 24px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText(group.title,x+82,y+52);const startY=y+91,rowH=(h-112)/Math.max(group.items.length,1);group.items.forEach((item,index)=>{const cy=startY+index*rowH;if(index){ctx.strokeStyle='#eadfd4';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+25,cy-13);ctx.lineTo(x+w-25,cy-13);ctx.stroke();}ctx.fillStyle='#9a897c';ctx.font='650 15px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText(item[1],x+26,cy+5);ctx.fillStyle='#44352c';ctx.font='750 19px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.textAlign='right';const value=item[2]&&item[2]!=='－'?item[2]:'尚未安排';const clipped=value.length>14?value.slice(0,13)+'…':value;ctx.fillText(clipped,x+w-26,cy+5);ctx.textAlign='left';});}
function canvasDecor(ctx){ctx.save();ctx.globalAlpha=.12;ctx.strokeStyle='#fff';ctx.lineWidth=2;for(const [x,y,r] of [[930,55,170],[960,80,110],[880,20,70]]){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=.18;ctx.fillStyle='#fff';for(const [x,y,r] of [[810,75,5],[850,205,3],[1000,190,7]]){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}ctx.restore();}
async function makeWeekly(row){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d'),accent=church==='SHiNE'?'#d75b32':'#8d563b',accentDeep=church==='SHiNE'?'#9e391f':'#5f3928',bg=ctx.createLinearGradient(0,0,1080,1350);bg.addColorStop(0,church==='SHiNE'?'#fff5ed':'#fbf4ec');bg.addColorStop(1,church==='SHiNE'?'#f6dfcf':'#ead8c6');ctx.fillStyle=bg;ctx.fillRect(0,0,1080,1350);const header=ctx.createLinearGradient(0,0,1080,290);header.addColorStop(0,accentDeep);header.addColorStop(.68,accent);header.addColorStop(1,church==='SHiNE'?'#ee8a5e':'#c99a73');roundRect(ctx,34,30,1012,280,42,header);canvasDecor(ctx);ctx.fillStyle='rgba(255,255,255,.14)';ctx.font='900 108px system-ui,-apple-system,sans-serif';ctx.fillText('SERVE',610,270);roundRect(ctx,76,66,238,42,21,'rgba(255,255,255,.14)');ctx.fillStyle='#fff1e5';ctx.font='750 15px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText('WEEKLY SERVICE TEAM',96,93);ctx.fillStyle='#fff';ctx.font='850 43px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText(churchName,76,164);ctx.font='800 33px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText('本週服事團隊',76,213);await brandLogo(ctx);const d=dateParts(row.service_date);roundRect(ctx,52,338,976,150,31,'#fffdf9');roundRect(ctx,76,364,126,98,24,church==='SHiNE'?'#fff0e7':'#f4e3d4');ctx.fillStyle=accent;ctx.textAlign='center';ctx.font='900 43px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText(d.day,139,411);ctx.font='750 15px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText(d.month+' · '+d.weekday,139,442);ctx.textAlign='left';ctx.fillStyle='#9a897c';ctx.font='700 14px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText('THIS WEEK · '+(isoDate(row.service_date)||''),235,378);ctx.fillStyle='#3f3129';ctx.font='850 29px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';canvasText(ctx,row.event||'主日崇拜',235,419,730,34,1);ctx.fillStyle=accent;ctx.font='700 19px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';const speaker=visibleRoles().includes('speaker')?'信息分享｜'+(row.speaker||'尚未安排'):'同心服事 · 一起預備';ctx.fillText(speaker,235,454);const groups=weeklyGroups(row),cardW=476,cardH=330;groups.forEach((group,index)=>canvasGroup(ctx,group,52+(index%2)*(cardW+24),520+Math.floor(index/2)*(cardH+24),cardW,cardH));ctx.fillStyle='#6e5c4f';ctx.textAlign='center';ctx.font='750 20px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText('同心服事 · 彼此補位 · 一起預備美好的聚會',540,1247);ctx.fillStyle='#9a887a';ctx.font='500 15px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.fillText('CHURCH MANAGEMENT  ·  感謝每一位同工忠心擺上',540,1284);ctx.textAlign='left';return canvas;}
async function makeMonthly(rows,month){const panelH=380,gap=20,height=Math.max(1120,300+rows.length*(panelH+gap)+130),{canvas,ctx}=canvasBase(height,churchName+'｜本月服事表',month.replace('-',' 年 ')+' 月 · 共 '+rows.length+' 場聚會');await brandLogo(ctx);rows.forEach((row,index)=>servicePanel(ctx,row,52,278+index*(panelH+gap),976,true));ctx.fillStyle='#8d7b6e';ctx.font='500 18px -apple-system,BlinkMacSystemFont,"PingFang TC","Noto Sans TC",sans-serif';ctx.textAlign='center';ctx.fillText('謝謝每一位同工忠心擺上，請彼此確認並預備服事。',540,height-58);ctx.textAlign='left';return canvas;}
function toast(message){document.querySelector('.png-toast')?.remove();const node=el('div',message,'png-toast');document.body.append(node);setTimeout(()=>node.remove(),3600);}
async function download(canvas,name){const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png',1));if(!blob)throw new Error('PNG 圖片產生失敗。');const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=escapeFile(name)+'.png';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
async function exportWeekly(){const row=schedules.find(item=>item.service_date===$('#weekPick').value);if(!row)return toast('請先選擇要輸出的聚會日期。');setExportBusy(true);try{await download(await makeWeekly(row),churchName+'-'+row.service_date+'-本週服事表');toast('本週服事表 PNG 已完成下載。');}catch(error){toast(error.message);}finally{setExportBusy(false);}}
async function exportMonthly(){const month=$('#monthPick').value,rows=schedules.filter(row=>isoDate(row.service_date).startsWith(month));if(!rows.length)return toast('這個月份目前沒有排班資料。');setExportBusy(true);try{await download(await makeMonthly(rows,month),churchName+'-'+month+'-本月服事表');toast('本月服事表 PNG 已完成下載。');}catch(error){toast(error.message);}finally{setExportBusy(false);}}
function setExportBusy(value){$('#weekPng').disabled=value;$('#monthPng').disabled=value;status.textContent=value?'正在製作 PNG 圖片…':'共 '+schedules.length+' 筆排班。';}
async function load(){status.textContent='正在載入…';try{if(preview){schedules=previewRows;members=[];rolePreferences=previewPreferences();}else [schedules,members,rolePreferences]=await Promise.all([listSchedules(db,church),listScheduleMembers(db,church),listRolePreferences(db,church)]);render();configureExports();$('#new').disabled=false;status.textContent=(preview?'版面預覽 · ':'共 ')+schedules.length+' 筆排班。';}catch(error){status.textContent=error.message;}}

$('#title').textContent=churchName+' · 服事排班';
$('#members').href='members.html?church='+encodeURIComponent(church||'');
$('#new').onclick=()=>openForm();
$('#manageRoles').onclick=openRoleSettings;
$('#weekPng').onclick=exportWeekly;
$('#monthPng').onclick=exportMonthly;
load().then(async()=>{if(preview&&new URLSearchParams(location.search).get('previewPng')==='1'&&schedules.length){const shell=el('section','','png-dev-preview'),canvas=await makeWeekly(schedules.find(row=>isoDate(row.service_date)>=weekStartIso())||schedules[0]);canvas.style.width='min(540px,100%)';canvas.style.height='auto';shell.append(el('h2','本週 PNG 預覽'),canvas);document.body.append(shell);}});
