import {db} from './admin-db.mjs';import {COMMON,M_PLUS,SHINE,listSchedules,listScheduleMembers,saveSchedule} from './schedule-management.mjs';
const values=new URLSearchParams(location.search).getAll('church'),church=values.length===1?values[0]:null,$=s=>document.querySelector(s),status=$('#status'),editor=$('#editor'),records=$('#records');let schedules=[],members=[],busy=false;
const el=(tag,value,cls='')=>{const n=document.createElement(tag);n.textContent=value;n.className=cls;return n;};
const labels={event:'聚會主題',speaker:'講員',worship_leader:church==='M+'?'敬拜讚美':'敬拜主領',tech_sound:'音控控台',tech_video:church==='M+'?'投影字幕／導播':'直播導播',usher1:'招待一',usher2:'招待二',presider:'司會（主持／報告）',prayer:'主日公禱',sunday_school:'兒主主責老師',sunday_school_ta:'兒主助教同工',singers:'敬拜歌者',keyboard:'司琴鍵盤',guitar:'木／電吉他',bass:'貝斯手',drums:'爵士鼓手',ushers:'主日招待'};
function memberSelect(key,current=''){const select=document.createElement('select');select.append(new Option('－（未安排）',''));const keyword={worship_leader:'主領',tech_sound:'音控',tech_video:'導播',usher1:'招待',usher2:'招待',presider:'司會',prayer:'禱告',keyboard:'司琴',guitar:'吉他',bass:'貝斯',drums:'鼓'}[key]||'';const sorted=[...members].sort((a,b)=>Number((b.ministry||'').includes(keyword))-Number((a.ministry||'').includes(keyword))||a.name.localeCompare(b.name,'zh-TW'));for(const m of sorted)select.append(new Option(m.name+'（'+(m.group_name||'未編組')+'）',m.name));if(current&&!sorted.some(m=>m.name===current))select.append(new Option(current+'（舊資料）',current));select.value=current||'';return select;}
function openForm(row=null){editor.replaceChildren();editor.hidden=false;const form=document.createElement('form'),grid=el('div','','edit-grid'),date=document.createElement('input'),inputs={};date.type='date';date.value=row?.service_date||'';let wrap=el('label','服事日期');wrap.append(date);grid.append(wrap);for(const key of [...COMMON,...(church==='M+'?M_PLUS:SHINE)]){const input=['event','speaker','singers','ushers'].includes(key)?document.createElement('input'):memberSelect(key,row?.[key]||'');if(input.tagName==='INPUT'){input.value=row?.[key]||'';input.maxLength=300;}wrap=el('label',labels[key]);wrap.append(input);grid.append(wrap);inputs[key]=input;}const actions=el('div','','editor-actions'),cancel=el('button','取消','secondary'),save=el('button',row?'儲存更正':'儲存排班');cancel.type='button';cancel.onclick=()=>editor.hidden=true;actions.append(cancel,save);form.append(el('h2',row?'更正服事排班':'新增服事排班'),grid,actions);form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{const payload={service_date:date.value,...Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value]))};await saveSchedule(db,church,payload,row);editor.hidden=true;await load();status.textContent=row?'排班已更正。':'排班已儲存。';}catch(error){status.textContent=error.message;}finally{busy=false;}};editor.append(form);date.focus();}
function render(){records.replaceChildren();for(const row of schedules){const card=el('article','','member-card');card.append(el('h3',row.service_date),el('p',(row.event||'主日聚會')+' · 講員：'+(row.speaker||'未定'),'status-badge'));for(const key of [...COMMON,...(church==='M+'?M_PLUS:SHINE)].filter(k=>!['event','speaker'].includes(k)))if(row[key])card.append(el('p',labels[key]+'：'+row[key]));const edit=el('button','調整服事','secondary');edit.onclick=()=>openForm(row);card.append(edit);records.append(card);}if(!schedules.length)records.append(el('p','目前沒有服事排班。','muted'));}
async function load(){status.textContent='正在載入…';try{[schedules,members]=await Promise.all([listSchedules(db,church),listScheduleMembers(db,church)]);render();$('#new').disabled=false;status.textContent='共 '+schedules.length+' 筆排班。';}catch(error){status.textContent=error.message;}}
$('#title').textContent=(church==='M+'?'M＋大雅教會':'火樂教會')+' · 服事排班';$('#members').href='members.html?church='+encodeURIComponent(church||'');$('#new').onclick=()=>openForm();load();
