import {db} from './admin-db.mjs?v=20261006-mobile-stability1';
const $=s=>document.querySelector(s),endpoint='https://aqanuwilmvdtlzuqlrau.supabase.co/functions/v1/system-monitor';
const el=(tag,text='',className='')=>{const node=document.createElement(tag);node.textContent=text;node.className=className;return node;};
const labels={church:{title:'教會 OS',icon:'⛪',items:[['members','全部會友'],['mplus_members','M+ 會友'],['shine_members','火樂會友'],['newcomers','M+ 新朋友'],['groups','小組／小家'],['open_care','關懷進行中'],['overdue_care','逾期關懷'],['pending_prayers','待關懷代禱'],['future_services','未來服事表']]},school:{title:'課輔管理',icon:'📚',items:[['students','在班學生'],['staff','老師／同工'],['today_checkins','今日打卡'],['month_rollcalls','本月點名'],['today_counseling','今日輔導']]},basketball:{title:'籃球隊',icon:'🏀',items:[['players','球員'],['members','系統成員'],['future_games','未來賽事'],['game_stats','球員比賽紀錄'],['today_checkins','今日簽到']]}};
const cronLabels={'mplus-line-discussion-summary-daily':['M+ LINE 群組討論日報','每天晚上 9 點'],'mschool-daily-line-report-9pm':['課輔每日報告','每天晚上 9 點'],'pastoral-newcomer-care-reminders-hourly':['新朋友關懷提醒','每小時整點'],'shine-weekly-sunday-service-line-card':['火樂主日服事圖卡','每週四上午 9 點'],'weekly-sunday-service-line-card':['M+ 主日服事圖卡','每週五上午 9 點']};
const metricLinks={overdue_care:'newcomer-care.html?church=M%2B&filter=overdue'};
let busy=false,timer=null;
function formatTime(value){if(!value)return '尚無紀錄';return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(value));}
function renderSystems(items){const area=$('#systems');area.replaceChildren();for(const item of items){const card=document.createElement('a');card.href=item.url;card.target='_blank';card.rel='noopener';card.className='system-status-card'+(item.online?'':' offline');const head=el('div','','system-status-head');head.append(el('strong',item.name),el('b',item.online?'正常':'異常'));card.append(head,el('span',item.online?'可正常連線':'目前無法確認服務'),el('small',item.status?`HTTP ${item.status} · ${item.latency_ms} ms`:`連線逾時 · ${item.latency_ms} ms`));area.append(card);}}
function renderMetrics(data){const area=$('#metrics');area.replaceChildren();for(const [key,group] of Object.entries(labels)){const box=el('article','','metric-group');box.append(el('h3',`${group.icon} ${group.title}`));const grid=el('div','','metric-grid');for(const [field,label] of group.items){const href=key==='church'?metricLinks[field]:null,card=el(href?'a':'div','','metric-card'+(field==='overdue_care'&&Number(data[key]?.[field])>0?' alert':''));if(href){card.href=href;card.setAttribute('aria-label',`${label}，點擊查看名單`);}card.append(el('strong',String(data[key]?.[field]??'—')),el('span',label));grid.append(card);}box.append(grid);area.append(box);}}
function automationCard(title,status,detail,time){const okay=status==='sent'||status==='succeeded'||status===true,card=el('article','','automation-card'),head=document.createElement('header');head.append(el('strong',title),el('span',okay?'正常':'需注意','state-pill '+(okay?'':'failed')));card.append(head,el('span',detail),el('small',time));return card;}
function renderAutomation(data){const area=$('#automation');area.replaceChildren();const line=data.line_summary||{},school=data.school_report||{};area.append(automationCard('LINE 群組討論日報',line.status,`${line.date||'尚無日期'} · ${line.messages??0} 則訊息`,formatTime(line.sent_at)),automationCard('課輔每日報告',school.status,school.date||'尚無日期',formatTime(school.sent_at)));for(const job of data.cron_jobs||[]){const info=cronLabels[job.name]||[job.name,'自動排程'],card=automationCard(info[0],job.active&&job.last_status==='succeeded',job.active?info[1]:'目前已關閉',formatTime(job.last_start)),button=el('button',job.active?'關閉排程':'開啟排程','secondary');button.type='button';button.onclick=()=>toggleCron(job.name,!job.active,button);card.append(button);area.append(card);}}
async function toggleCron(job,active,button){button.disabled=true;try{const session=await db.auth.getSession(),token=session.data.session?.access_token;if(!token)throw new Error('登入已失效。');const response=await fetch(endpoint,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({action:'set_cron',job,active}),cache:'no-store',signal:AbortSignal.timeout(20000)}),data=await response.json().catch(()=>({}));if(!response.ok||data.ok!==true)throw new Error('排程設定未儲存。');$('#status').textContent=active?'排程已開啟。':'排程已關閉。';busy=false;await load();}catch(error){$('#status').textContent=error.message;}finally{button.disabled=false;}}
function shortDate(value){const date=new Date(`${value}T00:00:00+08:00`);return `${date.getMonth()+1}/${date.getDate()}`;}
function trendCard(title,description,rows,series){const card=el('article','','trend-card');card.append(el('h3',title),el('p',description));if(!rows.length){card.append(el('div','尚無足夠資料','chart-empty'));return card;}const chart=el('div','','bar-chart'),max=Math.max(1,...rows.flatMap(row=>series.map(item=>Number(row[item.key]||0))));for(const row of rows){const column=el('div','','bar-column'),stack=el('div','','bar-stack');for(const item of series){const bar=el('span','','bar '+(item.secondary?'secondary':''));bar.style.height=`${Math.max(2,Number(row[item.key]||0)/max*100)}%`;bar.title=`${item.label}：${row[item.key]??0}`;stack.append(bar);}column.append(stack,el('small',shortDate(row.date)));chart.append(column);}card.append(chart);const summary=el('div','','trend-summary'),totals={};for(const item of series){const total=rows.reduce((sum,row)=>sum+Number(row[item.key]||0),0),label=el('span');totals[item.key]=total;label.append(el('strong',String(total)),document.createTextNode(` ${item.totalLabel||item.label}`));summary.append(label);}if(totals.expected>0){const rate=el('span');rate.append(el('strong',`${Math.round(totals.present*100/totals.expected)}%`),document.createTextNode(' 整體出席率'));summary.append(rate);}card.append(summary);return card;}
function renderTrends(data){const area=$('#trends');area.replaceChildren();area.append(trendCard('會友與新朋友新增','最近 12 週新增人數',data.member_growth||[],[{key:'members',label:'全部新增',totalLabel:'位新增會友'},{key:'newcomers',label:'新朋友',totalLabel:'位新朋友',secondary:true}]),trendCard('教會聚會出席','最近 12 筆點名：應到與實到',data.church_attendance||[],[{key:'expected',label:'應到',totalLabel:'人次應到'},{key:'present',label:'實到',totalLabel:'人次實到',secondary:true}]),trendCard('課輔每日出席','最近 30 個有點名的上課日',data.school_attendance||[],[{key:'expected',label:'應到',totalLabel:'人次應到'},{key:'present',label:'實到',totalLabel:'人次實到',secondary:true}]),trendCard('籃球隊健康簽到','最近 30 天每日簽到人數',data.basketball_checkins||[],[{key:'count',label:'簽到',totalLabel:'人次簽到'}]));}
function loading(){for(const selector of ['#systems','#metrics','#automation','#trends'])$(selector).replaceChildren(el('div','','monitor-empty skeleton'));}
async function load(){if(busy)return;busy=true;$('#refresh').disabled=true;$('#status').textContent='';if(!$('#systems').children.length)loading();try{const session=await db.auth.getSession(),token=session.data.session?.access_token;if(!token){location.replace('admin-login.html');return;}const response=await fetch(endpoint,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:'{}',cache:'no-store',signal:AbortSignal.timeout(20000)});const data=await response.json().catch(()=>({}));if(response.status===403)throw new Error('您的帳號尚未取得系統監控權限。');if(!response.ok||!data.ok)throw new Error('目前無法取得監控資料，請稍後再試。');renderSystems(data.systems||[]);renderMetrics(data);renderAutomation(data.automation||{});renderTrends(data.trends||{});const offline=(data.systems||[]).filter(item=>!item.online).length;$('#overall-dot').className='live-dot '+(offline?'warning':'');$('#overall-status').textContent=offline?`${offline} 個服務需要確認`:'所有對外服務正常';$('#updated-at').textContent=`更新：${formatTime(data.generated_at)} · 資料庫 ${(Number(data.database?.size_bytes||0)/1048576).toFixed(1)} MB`;$('#status').textContent=offline?'已完成檢查，請查看標示異常的服務。':'即時資料已更新。';}catch(error){$('#overall-dot').className='live-dot down';$('#overall-status').textContent='監控資料暫時無法取得';$('#status').textContent=error.message;}finally{busy=false;$('#refresh').disabled=false;clearTimeout(timer);timer=setTimeout(load,60000);}}
$('#refresh').onclick=load;document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});load();
