import {AudioBufferSource,BufferTarget,CanvasSource,Mp4OutputFormat,Output,Quality,canEncodeVideo} from 'https://cdn.jsdelivr.net/npm/mediabunny@1.61.0/+esm';

const WIDTH=720,HEIGHT=1280,FPS=24,DURATION=5;
function hero(ctx,image,progress){const scale=Math.min(612/image.width,344/image.height)*(1+progress*.015),w=image.width*scale,h=image.height*scale,x=(WIDTH-w)/2,y=190+(344-h)/2;ctx.save();ctx.beginPath();ctx.roundRect(54,190,612,344,24);ctx.clip();ctx.drawImage(image,x,y,w,h);ctx.restore();}
function roundedRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function wrap(ctx,text,maxWidth,maxLines=3){const chars=[...String(text||'')],lines=[];let line='';for(const char of chars){const next=line+char;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=char;if(lines.length===maxLines-1)break;}else line=next;}if(line&&lines.length<maxLines)lines.push(line);const used=lines.join('').length;if(used<chars.length)lines[lines.length-1]=lines[lines.length-1].replace(/[，。！？、,.!?…]*$/,'')+'…';return lines;}
function drawFrame(ctx,image,data,progress){
  ctx.save();const gradient=ctx.createLinearGradient(0,0,0,1280);gradient.addColorStop(0,'#071713');gradient.addColorStop(1,'#123d35');ctx.fillStyle=gradient;ctx.fillRect(0,0,WIDTH,HEIGHT);hero(ctx,image,progress);
  const rise=Math.max(0,(.16-progress)*85),fade=Math.min(1,progress/.18,(1-progress)/.12);ctx.globalAlpha=Math.max(.15,fade);ctx.translate(0,rise);
  ctx.fillStyle='rgba(255,255,255,.95)';roundedRect(ctx,54,70,220,54,27);ctx.fillStyle='#153f37';ctx.font='800 23px system-ui,"Noto Sans TC",sans-serif';ctx.fillText('M+ 大雅教會',78,106);
  ctx.fillStyle='#ffd060';ctx.font='800 23px system-ui,"Noto Sans TC",sans-serif';ctx.fillText('YOU ARE INVITED · 歡迎你',54,588);
  ctx.fillStyle='#fff';ctx.font='800 47px system-ui,"Noto Sans TC",sans-serif';ctx.fillText('這個主日，一起回家',54,657);
  const card=(y,label,value,mark)=>{ctx.fillStyle='rgba(255,255,255,.12)';roundedRect(ctx,54,y,612,label==='聚會地址'?142:120,24);ctx.fillStyle='#ffd060';ctx.beginPath();ctx.arc(96,y+(label==='聚會地址'?71:60),23,0,Math.PI*2);ctx.fill();ctx.fillStyle='#173f37';ctx.textAlign='center';ctx.font='800 23px system-ui,"Noto Sans TC",sans-serif';ctx.fillText(mark,96,y+(label==='聚會地址'?80:69));ctx.textAlign='left';ctx.fillStyle='rgba(255,255,255,.65)';ctx.font='500 21px system-ui,"Noto Sans TC",sans-serif';ctx.fillText(label,134,y+43);ctx.fillStyle='#fff';ctx.font='750 28px system-ui,"Noto Sans TC",sans-serif';const lines=String(value).split('\n');lines.forEach((line,i)=>ctx.fillText(line,134,y+82+i*34));};
  card(704,'主日崇拜','每週日上午 10:00','日');card(846,'聚會地址','台中市大雅區神林南路\n513巷13號','址');ctx.fillStyle='#ffd060';roundedRect(ctx,54,1020,612,108,28);ctx.fillStyle='#173f37';ctx.textAlign='center';ctx.font='800 35px system-ui,"Noto Sans TC",sans-serif';ctx.fillText('歡迎回家！',360,1088);ctx.fillStyle='rgba(255,255,255,.55)';ctx.font='600 19px system-ui,"Noto Sans TC",sans-serif';ctx.fillText('MPLUS CHURCH · TAICHUNG',360,1202);ctx.textAlign='left';ctx.restore();
}
async function loadImage(url){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error('reel_image');return createImageBitmap(await response.blob());}
export function reelSupported(){return typeof VideoEncoder!=='undefined'&&typeof VideoFrame!=='undefined';}
async function musicBuffer(url,startSeconds=0){if(!url)return null;const raw=await (await fetch(url,{cache:'no-store'})).arrayBuffer(),context=new AudioContext({sampleRate:48000}),decoded=await context.decodeAudioData(raw),frames=48000*DURATION,out=new AudioBuffer({length:frames,numberOfChannels:Math.min(2,decoded.numberOfChannels),sampleRate:48000});for(let channel=0;channel<out.numberOfChannels;channel++){const target=out.getChannelData(channel),source=decoded.getChannelData(channel);for(let i=0;i<frames;i++){const fade=Math.min(1,i/9600,(frames-i)/19200);target[i]=source[(Math.floor(startSeconds*decoded.sampleRate)+i)%source.length]*.24*Math.max(0,fade);}}await context.close();return out;}
export async function createWeeklyReel({imageUrl,title,subtitle,serviceDate,audioUrl='',audioStart=0,onProgress=()=>{}}){
  onProgress({phase:'prepare',completed:0,total:FPS*DURATION});
  if(!reelSupported())throw new Error('reel_unsupported');
  if(!await canEncodeVideo('avc',{width:WIDTH,height:HEIGHT,quality:new Quality({bitrate:3_000_000})}))throw new Error('reel_unsupported');
  const canvas=document.createElement('canvas');canvas.width=WIDTH;canvas.height=HEIGHT;const ctx=canvas.getContext('2d',{alpha:false}),image=await loadImage(imageUrl),audio=await musicBuffer(audioUrl,audioStart),target=new BufferTarget(),output=new Output({format:new Mp4OutputFormat(),target}),source=new CanvasSource(canvas,{codec:'avc',quality:new Quality({bitrate:3_000_000})});
  output.addVideoTrack(source,{frameRate:FPS});let audioSource=null;if(audio){audioSource=new AudioBufferSource({codec:'aac',bitrate:128000});output.addAudioTrack(audioSource);}await output.start();if(audioSource)await audioSource.add(audio);
  const dateLabel=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date(`${serviceDate}T12:00:00+08:00`));
  for(let frame=0;frame<FPS*DURATION;frame++){const progress=frame/(FPS*DURATION-1);drawFrame(ctx,image,{title,subtitle,dateLabel},progress);await source.add(frame/FPS,1/FPS);onProgress({phase:'frames',completed:frame+1,total:FPS*DURATION});if(frame%6===0)await new Promise(resolve=>setTimeout(resolve,0));}
  onProgress({phase:'finalize',completed:FPS*DURATION,total:FPS*DURATION});await output.finalize();image.close();if(!target.buffer)throw new Error('reel_encode');return new Blob([target.buffer],{type:'video/mp4'});
}
