import {weeklyMetadata} from './weekly-youtube-content.mjs?v=20261010-youtube1';
const ENDPOINT='https://aqanuwilmvdtlzuqlrau.supabase.co/functions/v1/youtube-oauth';
const messages={broadcast_in_use:'這個場次已供另一週週報使用，請選擇本週的新待播場次。',past_bulletin:'過去的週報不會覆蓋目前直播資訊。',not_connected:'請先連結教會 YouTube 頻道。',token_refresh:'YouTube 授權已失效，請重新連結。',select_broadcast:'找不到唯一的待播場次，請按「選擇待播場次」指定。',broadcast_date_mismatch:'直播日期與週報不同，請重新選擇場次。',broadcast_already_started:'這個場次已開始或結束，無法再同步。',broadcast_not_found:'找不到指定的直播場次。',channel_mismatch:'連結的頻道與授權帳號不一致，請重新連結。',thumbnail_required:'請先儲存橫式預告圖。',thumbnail_format:'YouTube 預告圖須為 JPG 或 PNG，請重新製圖。',thumbnail_download_failed:'預告圖暫時無法讀取，請稍後重試。',sermon_information_required:'請填寫主題、經文和講員。',sync_in_progress:'正在同步，請稍後按「確認同步結果」。',verification_pending:'資料已送出，YouTube 尚在更新，請稍後確認結果或重試。',bulletin_changed:'週報已更新，請重新載入最新內容。',bulletin_not_approved:'週報核准後才能同步。',reviewer_required:'只有具備週報核准權限的帳號可以重新同步。',forbidden:'目前帳號沒有這項操作的權限。',youtube_quotaExceeded:'YouTube 今日使用額度已滿，請稍後重試。',youtube_forbidden:'YouTube 尚未允許這項更新，請確認頻道授權與縮圖權限。'};
const errorText=code=>messages[code]||'YouTube 更新未完成，請確認連線後重試。';
const dateTW=s=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(s));
export function initWeeklyYoutube({db,church,getContext,onDirty}){
 const panel=document.querySelector('#weekly-youtube');if(!panel)return null;panel.hidden=church!=='M+';
 const $=s=>panel.querySelector(s),enabled=$('#youtube-enabled'),target=$('#youtube-target'),state=$('#youtube-state'),preview=$('#youtube-preview'),choose=$('#youtube-choose'),refresh=$('#youtube-refresh'),retry=$('#youtube-retry');
 let loading=false,sequence=0;
 function status(text,tone=''){state.textContent=text;state.dataset.tone=tone;}
 async function api(action,payload={}){const session=await db.auth.getSession(),token=session.data.session?.access_token;if(!token)throw new Error('登入已失效，請重新登入。');const response=await fetch(ENDPOINT,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({church,action,...payload}),credentials:'omit',cache:'no-store',signal:AbortSignal.timeout(120000)}),result=await response.json().catch(()=>({}));if(!response.ok||!result.ok)throw new Error(errorText(result.error));return result;}
 function context(){return getContext();}
 function renderPreview(){const c=context();try{const data=weeklyMetadata(c.row);preview.textContent=data.title+'\n\n'+data.description+'\n\n標籤：'+data.tags.join('、');}catch{preview.textContent='填寫主題、經文與講員後，這裡會顯示自動產生的標題、說明及標籤。';}}
 function sync(){if(church!=='M+')return;const c=context(),locked=loading||c.busy,canTarget=c.editable||c.row?.status==='published'&&c.reviewer;enabled.disabled=!c.editable||locked;target.disabled=!canTarget||locked||!enabled.checked;choose.disabled=!canTarget||locked||!enabled.checked;refresh.disabled=locked||!c.saved;retry.hidden=c.row?.status!=='published'||!c.reviewer||!enabled.checked;retry.disabled=locked;panel.setAttribute('aria-busy',String(loading));renderPreview();}
 function collect(){return {youtube_sync_enabled:church==='M+'&&enabled.checked,youtube_video_id:target.value||null};}
 function reset(){sequence++;loading=false;$('#youtube-watch').hidden=true;const c=context();enabled.checked=c.row?.youtube_sync_enabled===true;target.replaceChildren(new Option('自動使用每週直播入口', ''));if(c.row?.youtube_video_id)target.add(new Option('已指定場次 · '+c.row.youtube_video_id,c.row.youtube_video_id));target.value=c.row?.youtube_video_id||'';status(enabled.checked?'核准後會同步主題、日期、經文、講員、標籤與橫式預告圖。':'未啟用 YouTube 同步。');sync();if(c.saved&&church==='M+')readStatus();}
 async function readStatus(){const c=context();if(!c.saved||church!=='M+'||loading)return;const version=sequence;loading=true;status('正在確認 YouTube 同步結果…');sync();try{const result=await api('weekly_status',{bulletinId:c.row.id});if(sequence!==version)return;const p=result.publication;if(!p)status(enabled.checked?'核准後將更新 YouTube；尚未同步。':'未啟用 YouTube 同步。');else if(p.status==='synced'&&p.bulletin_version===c.row.version){status('YouTube 標題、說明、標籤與預告圖已同步。','success');const link=$('#youtube-watch');link.href='https://www.youtube.com/watch?v='+p.video_id;link.hidden=false;}else if(p.status==='syncing')status('正在同步到 YouTube，請稍後確認結果。');else if(p.status==='failed')status(errorText(p.error_code),'error');else status('這個版本尚未同步。');}catch(e){if(sequence===version)status(e.message,'error');}finally{if(sequence===version){loading=false;sync();}}}
 choose.onclick=async()=>{const c=context();if(loading||!(c.editable||c.row?.status==='published'&&c.reviewer)||c.busy)return;const version=sequence,selected=target.value;loading=true;status('正在尋找教會的待播場次…');sync();try{const result=await api('weekly_live_info');if(version!==sequence)return;target.replaceChildren(new Option('自動使用每週直播入口',''));const candidates=result.candidates.filter(r=>!r.scheduledStartTime||Date.parse(r.scheduledStartTime)<Date.parse('2000-01-01')||dateTW(r.scheduledStartTime)===c.row.service_date);for(const r of candidates)target.add(new Option(r.title+' · '+(r.scheduledStartTime?dateTW(r.scheduledStartTime):'隨時開播'),r.id));if(selected&&!candidates.some(r=>r.id===selected))target.add(new Option('原指定場次 · '+selected,selected));target.value=selected;status(candidates.length?'請選擇本週場次；保留「自動」會沿用已確認的直播串流設定。':'目前沒有符合週報日期的待播場次，請影音同工先準備直播。');}catch(e){if(version===sequence)status(e.message,'error');}finally{if(version===sequence){loading=false;sync();}}};
 retry.onclick=async()=>{const c=context();if(loading||c.busy||!c.reviewer||c.row?.status!=='published')return;const version=sequence;loading=true;status('正在將核准的週報及預告圖同步到 YouTube…');sync();try{const result=await api('weekly_sync',{bulletinId:c.row.id,version:c.row.version,...(target.value?{videoId:target.value}:{})});if(version!==sequence)return;status(result.status==='synced'?'YouTube 資訊及預告圖已同步。':'這份週報未啟用同步。',result.status==='synced'?'success':'');if(result.url){const link=$('#youtube-watch');link.href=result.url;link.hidden=false;}}catch(e){if(version===sequence)status(e.name==='TimeoutError'?'等待較久，請按「確認同步結果」，先確認是否已完成。':e.message,'error');}finally{if(version===sequence){loading=false;sync();}}};
 refresh.onclick=readStatus;enabled.onchange=()=>{onDirty();sync();};target.onchange=()=>{if(context().editable)onDirty();else status('已選擇場次，按「重新同步本週資訊」套用。');};
 return {collect,reset,sync};
}
