import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const {default:puppeteer}=await import(process.env.PUPPETEER_MODULE||'puppeteer-core');
const root=new URL('../../',import.meta.url).pathname,out=process.env.TREE_TEST_OUTPUT||new URL('./results/',import.meta.url).pathname;
fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html; charset=utf-8','.mjs':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.wav':'audio/wav'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
const checks=[],errors=[],calls=[];let records=[],notes=[],challenges=[],gardenDelay=0,writeDelay=0,meDelay=0,failAction='',incompleteAction='',failScripture=false,scriptureDelay=0,liffAuth=true,failed=false,browser;
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const count=action=>calls.filter(call=>call.action===action).length;
const check=(name,detail={})=>{checks.push({name,passed:true,...detail});console.log('PASS',name);};
const headers={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'*'};
try{
 browser=await puppeteer.launch({executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-first-run','--disable-background-networking','--autoplay-policy=no-user-gesture-required'],userDataDir:fs.mkdtempSync(path.join(os.tmpdir(),'life-tree-'))});
 const page=await browser.newPage();await page.setBypassServiceWorker(true);
 await page.evaluateOnNewDocument(()=>{
  if(location.hostname!=='127.0.0.1')return;
  const RealDate=Date;window.Date=class extends RealDate{constructor(...args){super(...(args.length?args:['2026-10-10T08:00:00+08:00']));}static now(){return new RealDate('2026-10-10T08:00:00+08:00').getTime();}};
  const nativeTimeout=window.setTimeout;window.setTimeout=(callback,ms,...args)=>nativeTimeout(callback,(window.__shortDeadlines&&ms===15000)||(window.__audioHang&&ms===6000)?100:ms,...args);
  const nativeAbortTimeout=AbortSignal.timeout.bind(AbortSignal);AbortSignal.timeout=ms=>nativeAbortTimeout(window.__shortApiDeadline&&ms===15000?100:ms);
  window.__audioCalls=[];
  const unlocked=new WeakSet(),policy=localStorage.getItem('fixtureAudioPolicy')||'gesture';
  if(localStorage.getItem('fixtureBlockClick')==='1')document.addEventListener('click',event=>event.stopImmediatePropagation(),true);
  const nativePlay=HTMLMediaElement.prototype.play;
  HTMLMediaElement.prototype.play=function(){
   const gesture=navigator.userActivation.isActive,blocked=policy!=='allow'&&!gesture&&!unlocked.has(this);
   window.__audioCalls.push({kind:this.dataset.lifeTreeAudio,src:this.src,gesture,blocked});
   if(blocked){if(policy==='pending')return new Promise(()=>{});return Promise.reject(new DOMException('Gesture required','NotAllowedError'));}
   unlocked.add(this);
   if(window.__audioFailure===true||window.__audioFailure===this.dataset.lifeTreeAudio)return Promise.reject(Error('test audio unavailable'));
   if(window.__audioHang)return new Promise(()=>{});
   return nativePlay.call(this);
  };
 });
 page.on('pageerror',error=>errors.push(error.message));
 await page.setRequestInterception(true);
 page.on('request',async request=>{try{
  const url=new URL(request.url());if(url.origin===base)return request.continue();
  if(url.href.includes('sdk.js'))return request.respond({status:200,contentType:'application/javascript',body:`window.liff={init:async({liffId})=>{if(liffId==='2011645391-9t2SxuSG'&&!location.pathname.endsWith('/tree-reading-october-test.html'))throw Error('LIFF endpoint mismatch');},isInClient:()=>true,isLoggedIn:()=>${liffAuth},getIDToken:()=>${liffAuth?'"isolated-fixture"':'""'}}`});
  if(url.hostname.endsWith('supabase.co')){
   if(request.method()==='OPTIONS')return request.respond({status:200,headers,body:'{}'});
   const body=JSON.parse(request.postData()||'{}');calls.push({action:body.action,date:body.readingDate,endpoint:url.pathname,project:url.hostname,resolution:body.resolutionAction,challenge:body.challengeId});
   if(body.action==='me'&&meDelay)await sleep(meDelay);
   if(body.action===failAction)return request.respond({status:503,contentType:'application/json',headers,body:'{"error":"unavailable"}'});
   let data={};
   if(body.action==='me')data={participant:{id:'fixture-member',display_name:'測試同工',reading_start_date:'2026-10-01'},records,challenges,notes};
   if(body.action==='garden'){await sleep(gardenDelay);data={trees:Array.from({length:18},(_,index)=>({display_name:'同工'+(index+1),tree_number:index+1,completed_count:9,on_time_count:8}))};}
   if(body.action==='leaderboard')data={members:[{display_name:'測試同工',on_time_count:9}]};
   if(['mark_read','water_tree','resolve_challenge','journal_save'].includes(body.action))await sleep(writeDelay);
   if(body.action==='mark_read'){if(!records.some(row=>row.reading_date===body.readingDate))records=records.concat({reading_date:body.readingDate,completion_type:body.readingDate==='2026-10-10'?'on_time':'makeup',watered_at:null});data={records,completion_type:body.readingDate==='2026-10-10'?'on_time':'makeup'};}
   if(body.action==='water_tree'){records=records.map(row=>row.reading_date===body.readingDate?{...row,watered_at:'2026-10-10T00:01:00Z'}:row);data={records};}
   if(body.action==='journal_save'){const note={reading_date:body.readingDate,note:body.note};notes=notes.filter(n=>n.reading_date!==body.readingDate).concat(note);data={note};}
   if(body.action==='resolve_challenge'){challenges=challenges.map(row=>row.id===body.challengeId?{...row,status:'resolved'}:row);data={challenges};}
   if(body.action===incompleteAction)data={};
   return request.respond({status:200,contentType:'application/json',headers,body:JSON.stringify(data)});
  }
  if(url.hostname==='raw.githubusercontent.com'){
   await sleep(scriptureDelay);
   return request.respond({status:failScripture?503:200,contentType:'application/json',headers,body:JSON.stringify({chapters:Array.from({length:31},()=>Array.from({length:30},(_,index)=>`${index+1} 隔離測試文字：智慧使人明白道路，願神的話成為今天腳前的燈，路上的光。`))})});
  }
  if(url.hostname==='api.open-meteo.com')return request.respond({status:200,contentType:'application/json',headers,body:JSON.stringify({current:{weather_code:2,temperature_2m:26,wind_speed_10m:9,time:'2026-10-10T08:00'}})});
  return request.abort();
 }catch(error){if(!/already handled|closed|Invalid InterceptionId/i.test(error.message))errors.push('interception: '+error.message);}});
 const openTree=async()=>{await page.goto(base+'/tree-reading-october-test.html',{waitUntil:'networkidle0'});await page.waitForSelector('#member-view:not([hidden])');};
 await page.setViewport({width:402,height:874,isMobile:true,hasTouch:true});await openTree();
 await page.waitForSelector('#journey-guide[open]');assert.equal(await page.$eval('#journey-guide-audio',n=>n.checked),true);assert.equal(await page.evaluate(()=>document.querySelectorAll('audio').length),0);assert.equal(count('garden'),0);assert.equal(count('leaderboard'),0);assert.equal(await page.evaluate(()=>document.activeElement.id),'journey-guide-title');await page.keyboard.press('Escape');assert.equal(await page.$eval('#journey-guide',n=>n.open),true);check('First visit shows explanation with prechecked sound choice, focused heading and no premature audio');
 for(const [width,height] of [[320,568],[402,874],[1440,900]]){await page.setViewport({width,height,isMobile:width<600,hasTouch:width<600});await page.waitForSelector('#journey-guide[open]');assert(await page.$eval('#journey-guide',n=>{const r=n.getBoundingClientRect();return r.left===0&&r.top===0&&r.width===innerWidth&&Math.abs(r.height-innerHeight)<2&&n.scrollWidth<=r.width;}));await page.$eval('#journey-guide-start',n=>n.scrollIntoView({block:'center',behavior:'instant'}));assert(await page.$eval('#journey-guide-start',n=>{const r=n.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));await page.screenshot({path:out+'/guide-'+width+'.png'});}check('First-visit explanation fills phone and desktop viewports and scrolls to reachable start control');
 assert.equal(await page.$$eval('.journey-guide-steps .guide-picture',nodes=>nodes.length),3);assert.equal(await page.$$eval('.guide-tools svg',nodes=>nodes.length),4);check('Visual explanation has three illustrated steps and four matching care tools');
 for(const [width,height] of [[320,568],[402,874],[1440,900]]){await page.setViewport({width,height,isMobile:width<600,hasTouch:width<600});await page.waitForSelector('#journey-guide[open]');await page.$eval('#journey-guide',n=>n.scrollTo(0,0));assert(await page.$$eval('.guide-picture',nodes=>nodes.every(n=>n.getBoundingClientRect().width>=80)));if(width===402)assert(await page.$$eval('.journey-guide-steps li:nth-child(n+2) div>span',nodes=>nodes.every(n=>{const range=document.createRange();range.selectNodeContents(n);return range.getBoundingClientRect().height<=parseFloat(getComputedStyle(n).lineHeight)+1;})),'Short guide captions stay on one line at 402px');await page.screenshot({path:out+'/visual-guide-'+width+'.png'});}
 await page.click('#journey-guide-start');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');assert(await page.evaluate(()=>window.__audioCalls.filter(c=>c.kind==='music'||c.kind==='effect').every(c=>c.gesture||c.blocked)));check('Prechecked sound starts only on trusted Start click');await page.click('#show-journey-guide');await page.click('#journey-guide-audio');await page.click('#journey-guide-start');assert(await page.$$eval('audio',nodes=>nodes.every(n=>n.paused)));assert.equal(await page.evaluate(()=>localStorage.getItem('lifeTreeSound')),'off');await openTree();assert.equal(await page.$eval('#journey-guide',n=>n.open),false);await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));assert.equal(await page.evaluate(()=>document.querySelectorAll('audio').length),0);check('Unchecked choice permits normal use, persists silent preference and does not repeat onboarding');
 await page.click('#show-journey-guide');await page.keyboard.press('Escape');assert.equal(await page.$eval('#journey-guide',n=>n.open),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'show-journey-guide');check('Reopened explanation closes with Escape and restores keyboard focus');
 await page.click('#show-journey-guide');await page.click('#journey-guide-audio');assert.equal(await page.evaluate(()=>document.querySelectorAll('audio').length),0);await page.focus('#journey-guide-start');await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');await page.waitForFunction(()=>document.querySelector('[data-life-tree-audio=music]').currentTime>.2);assert(await page.evaluate(()=>window.__audioCalls.filter(c=>c.kind==='music'||c.kind==='effect').every(c=>c.gesture||c.blocked)));assert.equal(await page.evaluate(()=>localStorage.getItem('lifeTreeSound')),'on');check('Checking sound alone does not play; trusted keyboard Start primes both native players and advances music clock');
 await openTree();assert.equal(await page.$eval('#journey-guide',n=>n.open),false);assert.equal(await page.$eval('#sound-toggle',n=>n.dataset.enabled),'true');assert.equal(await page.evaluate(()=>document.querySelectorAll('audio').length),2);assert(await page.evaluate(()=>window.__audioCalls.some(c=>c.kind==='music'&&c.blocked)));assert.match(await page.$eval('#music-status',n=>n.textContent),/輕觸頁面/);await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');await page.tap('#sound-toggle');check('Remembered opt-in attempts autoplay on reload; blocked playback resumes on normal gesture, speaker still mutes');
 await page.evaluate(()=>{localStorage.setItem('lifeTreeSound','on');localStorage.setItem('fixtureAudioPolicy','allow');});await openTree();await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');assert(await page.evaluate(()=>window.__audioCalls.some(c=>c.kind==='music'&&!c.gesture&&!c.blocked)));await page.waitForFunction(()=>document.querySelector('[data-life-tree-audio=music]').currentTime>.2);check('Allowed browser policy restores remembered music on entry without pressing any control');
 await page.evaluate(()=>{localStorage.removeItem('fixtureAudioPolicy');localStorage.setItem('fixtureBlockClick','1');});await page.setViewport({width:402,height:874,isMobile:true,hasTouch:true});await openTree();assert.equal(await page.$eval('#sound-toggle',n=>n.getAttribute('aria-pressed')),'false');await page.tap('#tree-title');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');assert(await page.evaluate(()=>window.__audioCalls.filter(c=>!c.blocked&&c.kind==='effect').length>=1));check('Trusted touch on ordinary tree text starts both players even when click propagation is suppressed');
 await page.evaluate(()=>{localStorage.removeItem('fixtureBlockClick');localStorage.setItem('fixtureAudioPolicy','pending');});await openTree();assert.equal(await page.$eval('#sound-toggle',n=>n.disabled),true);await page.tap('#tree-title');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');assert.equal(await page.$eval('#sound-toggle',n=>n.disabled),false);check('Normal touch supersedes a pending autoplay attempt immediately without waiting six seconds');
 await page.evaluate(()=>{localStorage.removeItem('fixtureAudioPolicy');localStorage.setItem('lifeTreeSound','off');});await page.setViewport({width:1440,height:900,isMobile:false,hasTouch:false});await openTree();await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));assert.equal(await page.evaluate(()=>window.__audioCalls.length),0);check('Remembered mute stays silent on reload, page return and ordinary interactions');
 await page.evaluate(()=>window.scrollTo(0,0));assert(await page.$eval('#read-today',n=>n.getBoundingClientRect().bottom<innerHeight));assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),1440);await page.screenshot({path:out+'/desktop-initial.png'});check('No devotional dock before watering');
 assert.equal(await page.$('#devotional-invitation'),null);assert.equal(await page.$('#test-sound'),null);assert.equal(await page.$eval('#tree-challenge-notice',n=>n.hidden),true);for(const width of [320,402,1440]){await page.setViewport({width,height:874,isMobile:width<600,hasTouch:width<600});await page.waitForFunction(()=>document.querySelector('#tree-scene')?.getBoundingClientRect().width>0);await page.$eval('.tree-card',n=>n.scrollIntoView({block:'start',behavior:'instant'}));const layout=await page.evaluate(()=>{const node=document.querySelector('#sound-toggle'),a=node.getBoundingClientRect().toJSON(),scene=document.querySelector('#tree-scene').getBoundingClientRect().toJSON();return {a,scene,controls:document.querySelectorAll('#tree-scene button,#tree-scene a').length,hit:node.contains(document.elementFromPoint(a.x+a.width/2,a.y+a.height/2)),overflow:document.documentElement.scrollWidth>innerWidth};});assert(layout.a.width>=44&&layout.a.height>=44&&layout.a.bottom<=layout.scene.top+.5&&layout.controls===0&&layout.hit&&!layout.overflow,JSON.stringify({width,...layout}));if(width===402)await page.screenshot({path:out+'/mobile-tree-clear.png'});}await page.setViewport({width:402,height:874,isMobile:true,hasTouch:true});await page.waitForSelector('#member-view:not([hidden])');check('Healthy tree artwork has no overlaid controls; 44px speaker sits in heading at 320/402/1440px');
 assert.equal(await page.$eval('#makeup-count',n=>n.textContent),'7 天可補讀');assert.equal(await page.$$eval('#makeup-dates button',nodes=>nodes.length),7);assert.match(await page.$eval('#makeup-expired',n=>n.textContent),/2 天/);await page.click('#go-makeup');assert.equal(await page.evaluate(()=>document.activeElement.id),'makeup-section');assert.match(await page.$eval('#makeup-dates button',n=>n.textContent),/10\/9.*箴言 9/);await sleep(700);await page.screenshot({path:out+'/mobile-makeup.png'});await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:out+'/mobile-navigation.png'});check('Stable three-action navigation exposes missing count, exact date/chapter and honest 7-day expiry');
 const before=count('me');meDelay=350;await page.click('#switch-member');await page.$eval('#switch-member',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));assert.equal(count('me')-before,1);meDelay=0;check('Refresh button works and ignores repeat clicks');
 await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');
 await page.waitForFunction(()=>document.querySelector('[data-life-tree-audio=music]').currentTime>.2);assert(await page.evaluate(()=>window.__audioCalls.filter(c=>c.kind==='music'||c.kind==='effect').every(c=>c.gesture||c.blocked)));assert.equal(await page.$eval('[data-life-tree-audio=music]',n=>n.muted),false);assert.equal(await page.$eval('[data-life-tree-audio=music]',n=>n.volume),.65);
 await page.tap('#sound-toggle');assert.equal(await page.evaluate(()=>localStorage.getItem('lifeTreeSound')),'off');assert(await page.$$eval('audio',nodes=>nodes.every(n=>n.paused)));check('Trusted touch starts native music and primes same effect element; clock advances; mute pauses both');
 await page.evaluate(()=>window.__audioFailure=true);await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#music-status').textContent.includes('重試'));assert.equal(await page.$eval('#sound-toggle',n=>n.getAttribute('aria-pressed')),'false');assert.equal(await page.$eval('#sound-toggle',n=>n.disabled),false);await page.evaluate(()=>window.__audioFailure=false);check('Audio failure shows retry without claiming playback');
 await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');await page.tap('#sound-toggle');
 await page.evaluate(()=>window.__audioHang=true);await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#music-status').textContent.includes('重試')&&!document.querySelector('#sound-toggle').disabled);assert.equal(await page.$eval('#sound-toggle',n=>n.disabled),false);assert(await page.$$eval('audio',nodes=>nodes.every(n=>n.paused)));await page.evaluate(()=>window.__audioHang=false);check('Never-resolving media playback times out, stops both channels and restores controls');
 await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');await page.waitForFunction(()=>document.querySelector('#music-status').textContent==='');check('Speaker retry recovers playback and enables effects');
 await page.tap('#sound-toggle');await page.evaluate(()=>window.__audioFailure='effect');await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#music-status').textContent.includes('音效尚未啟動'));assert.equal(await page.$eval('#sound-toggle',n=>n.getAttribute('aria-pressed')),'true');await page.evaluate(()=>window.__audioFailure=false);await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#music-status').textContent==='');assert.equal(await page.$$eval('audio',nodes=>nodes.length),2);check('Effect-only failure reports retry while music continues; retry reuses exactly two media elements');
 await page.evaluate(()=>{window.__treeHidden=true;Object.defineProperty(document,'hidden',{configurable:true,get:()=>window.__treeHidden});document.dispatchEvent(new Event('visibilitychange'));});assert(await page.$$eval('audio',nodes=>nodes.every(n=>n.paused)));await page.evaluate(()=>{window.__treeHidden=false;document.dispatchEvent(new Event('visibilitychange'));});await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');assert.equal(await page.$$eval('audio',nodes=>nodes.length),2);check('Background pauses all audio; visible page retries remembered music through the same players');
 const levels=await page.evaluate(async()=>{const context=new OfflineAudioContext(1,22050,22050),result={};for(const name of ['reading','storm','care','open','celebration','water','journal','wind']){const bytes=await(await fetch(`assets/audio/life-tree/${name}.wav`)).arrayBuffer();const buffer=await context.decodeAudioData(bytes);const samples=buffer.getChannelData(0);let sum=0,peak=0;for(const v of samples){sum+=v*v;peak=Math.max(peak,Math.abs(v));}result[name]={duration:buffer.duration,rms:Math.sqrt(sum/samples.length),peak};}return result;});for(const level of Object.values(levels)){assert(level.rms>.025);assert(level.peak>.3&&level.peak<.7);}check('Every shipped WAV decodes with nonzero signal and controlled peak/RMS',levels);
 await page.tap('#sound-toggle');
 await page.click('#read-today');await page.waitForSelector('#scripture-end');assert.equal(await page.$eval('#mark-read',n=>n.disabled),true);await page.$eval('#scripture-end',n=>n.scrollIntoView({block:'center',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#mark-read').disabled);check('Today reading requires reaching Scripture end');
 writeDelay=350;await page.click('#mark-read');assert.match(await page.$eval('#mark-read',n=>n.textContent),/記錄/);await page.$eval('#mark-read',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>!document.querySelector('#care-tree').hidden);assert.equal(count('mark_read'),1);check('Read request has pending state and duplicate guard');
 await sleep(650);await page.$eval('#sound-toggle',n=>n.scrollIntoView({block:'center',behavior:'instant'}));await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');const effectsBeforeWater=await page.evaluate(()=>window.__audioCalls.filter(c=>c.src.includes('celebration.wav')).length);
 failAction='water_tree';await page.click('#care-tree');await page.waitForFunction(()=>!document.querySelector('#care-tree').disabled);assert.equal(await page.$('#devotional-invitation'),null);assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);assert.equal(await page.evaluate(()=>window.__audioCalls.filter(c=>c.src.includes('celebration.wav')).length),effectsBeforeWater);check('Failed watering remains retryable without showing devotional dock or playing celebration sound');
 failAction='';const waterBefore=count('water_tree');await page.click('#care-tree');assert.equal(await page.$eval('#care-tree',n=>n.textContent),'正在澆水…');await page.$eval('#care-tree',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>document.querySelector('#care-tree').hidden);assert.equal(count('water_tree')-waterBefore,1);assert(await page.$('.care-animation'));await page.waitForFunction(()=>document.querySelector('[data-life-tree-audio=effect]').src.includes('celebration.wav')&&!document.querySelector('[data-life-tree-audio=effect]').paused);assert.equal(await page.evaluate(()=>window.__audioCalls.filter(c=>c.src.includes('celebration.wav')).length),effectsBeforeWater+1);assert.equal(await page.$$eval('[data-life-tree-audio=effect]',nodes=>nodes.length),1);check('Watering success unlocks invitation once and plays celebration through the reused, gesture-primed element after API completion');
 await page.screenshot({path:out+'/mobile-watered.png',fullPage:true});
 await page.waitForFunction(()=>{const n=document.querySelector('#devotional-dock-link'),r=n.getBoundingClientRect();return r.height>0&&r.top>=0&&r.bottom<=innerHeight&&n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));});check('Watering success immediately reveals clickable floating invitation');
 for(const [width,height] of [[320,568],[390,844],[402,874],[430,900],[1280,900],[1440,900],[1920,900],[402,420]]){await page.setViewport({width,height,isMobile:width<600,hasTouch:width<600});await page.waitForSelector('#member-view:not([hidden])');await page.$eval('#tree-stats',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#devotional-dock').hidden);assert(await page.$eval('#devotional-dock',n=>{const r=n.getBoundingClientRect();return !n.hidden&&r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}));assert(await page.$eval('#devotional-dock-link',n=>n.getBoundingClientRect().height>=44));assert(await page.$eval('#dismiss-devotional-dock',n=>n.getBoundingClientRect().height>=44));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);}check('Floating invitation fits mobile, short and desktop viewports with 44px controls');
 await page.setViewport({width:402,height:874,isMobile:true,hasTouch:true});await page.$eval('#tree-stats',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#devotional-dock').hidden);await page.screenshot({path:out+'/mobile-watered-viewport.png'});
 await page.$eval('.tree-card',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#devotional-dock').hidden);check('Floating invitation remains available at tree heading without an upper duplicate entry');
 assert.equal(await page.$('#reflection-note'),null);assert.equal(await page.$('.reflection-card'),null);check('Tree has no duplicate journal editor');
 const progressBeforeJournal=JSON.stringify(records),callsBeforePreview=calls.length;await page.click('#devotional-dock-link');await page.waitForFunction(()=>document.querySelector('#reflection-note')&&!document.querySelector('#reflection-note').disabled);assert.match(page.url(),/tree-reading-october-test.html\?view=devotional/);assert.equal(await page.$('#complete'),null);assert.equal(await page.$$eval('textarea',nodes=>nodes.length),1);assert.match(await page.$eval('#status',n=>n.textContent),/創世記試閱/);assert.match(await page.$eval('.journal-context',n=>n.textContent),/2026-10-10/);assert.equal(calls.slice(callsBeforePreview).filter(c=>c.action!=='me').length,0);assert.equal(calls.at(-1).project,'svwgfgyxxgbqabosriom.supabase.co');check('Devotional owns single authenticated October journal with actual date, isolated endpoint and no progress writes');
 await page.type('#reflection-note','尚未收藏的測試拾光');await page.click('.tree-return');await page.waitForSelector('#member-view:not([hidden])');assert.equal(await page.$('#reflection-note'),null);assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);assert.equal(JSON.stringify(records),progressBeforeJournal);check('Return from devotional keeps October progress and removes duplicate invitation');
 const openDevotional=async()=>{await page.goto(base+'/daily-devotional.html?church=M%2B&preview=1&from=october-tree',{waitUntil:'networkidle0'});await page.waitForFunction(()=>document.querySelector('#reflection-note')&&!document.querySelector('#reflection-note').disabled);};
 await openDevotional();assert.equal(await page.$eval('#reflection-note',n=>n.value),'尚未收藏的測試拾光');check('Single devotional journal restores its private draft after leaving and reopening');
 failAction='journal_save';await page.click('#save-reflection');await page.waitForFunction(()=>!document.querySelector('#save-reflection').disabled);assert.equal(await page.$eval('#reflection-note',n=>n.value),'尚未收藏的測試拾光');assert.match(await page.$eval('#reflection-status',n=>n.textContent),/重試/);failAction='';const journalBefore=count('journal_save');writeDelay=200;await page.click('#save-reflection');await page.$eval('#save-reflection',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>document.querySelector('#reflection-status').textContent.includes('已收藏'));assert.equal(count('journal_save')-journalBefore,1);assert.equal(notes.length,1);assert.equal(notes[0].reading_date,'2026-10-10');assert.equal(JSON.stringify(records),progressBeforeJournal);writeDelay=0;check('Journal failure retains input, success ignores duplicate clicks and writes actual October date only');
 await page.click('.journal-history summary');assert.match(await page.$eval('#journal-entries',n=>n.textContent),/尚未收藏的測試拾光/);await page.$eval('#october-journal',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.screenshot({path:out+'/devotional-single-journal-402.png'});check('Saved journal is viewable inside devotional history');
 incompleteAction='journal_save';await page.click('#save-reflection');await page.waitForFunction(()=>!document.querySelector('#save-reflection').disabled);assert.match(await page.$eval('#reflection-status',n=>n.textContent),/尚未確認/);assert.equal(await page.$eval('#reflection-note',n=>n.value),'尚未收藏的測試拾光');incompleteAction='';check('Incomplete journal response cannot claim successful collection');
 await page.evaluate(()=>window.__shortApiDeadline=true);writeDelay=350;await page.click('#save-reflection');await page.waitForFunction(()=>!document.querySelector('#save-reflection').disabled);assert.match(await page.$eval('#reflection-status',n=>n.textContent),/等待過久/);assert.equal(await page.$eval('#reflection-note',n=>n.disabled),false);await sleep(400);writeDelay=0;check('Timed-out journal save preserves draft and restores controls');
 liffAuth=false;const authCalls=calls.length;await page.goto(base+'/daily-devotional.html?preview=1&from=october-tree',{waitUntil:'networkidle0'});await page.waitForSelector('.journal-retry');assert.equal(await page.$eval('#reflection-note',n=>n.disabled),true);assert.equal(calls.length,authCalls);liffAuth=true;check('No LINE identity cannot read or write journal; preview content stays available');
 failAction='me';await page.goto(base+'/daily-devotional.html?preview=1&from=october-tree',{waitUntil:'networkidle0'});await page.waitForSelector('.journal-retry');assert.equal(await page.$eval('#save-reflection',n=>n.disabled),true);failAction='';await page.click('.journal-retry');await page.waitForFunction(()=>!document.querySelector('#reflection-note').disabled);check('Journal loading failure offers working retry without enabling unauthenticated writes');
 const keptRecords=records;records=[];await page.goto(base+'/daily-devotional.html?preview=1&from=october-tree',{waitUntil:'networkidle0'});await page.waitForFunction(()=>document.querySelector('#reflection-status')?.textContent.includes('請先完成'));assert.equal(await page.$eval('#save-reflection',n=>n.disabled),true);await page.click('.journal-history summary');assert.match(await page.$eval('#journal-entries',n=>n.textContent),/尚未收藏的測試拾光/);records=keptRecords;check('Reading prerequisite preserved; earlier journal remains readable');
 await page.evaluate(()=>{for(const key of Object.keys(sessionStorage))if(key.startsWith('october-devotional-dismissed:'))sessionStorage.removeItem(key);});await openTree();await page.$eval('#tree-stats',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#devotional-dock').hidden);await page.click('#dismiss-devotional-dock');await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);check('Dismissal survives progress refresh');
 const beforeCachedReturn=count('me');meDelay=150;await page.evaluate(()=>{sessionStorage.setItem('october-journal-updated','1');window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:false}));});await sleep(200);assert.equal(count('me'),beforeCachedReturn);await page.evaluate(()=>{window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await page.waitForFunction(()=>!sessionStorage.getItem('october-journal-updated'));assert.equal(count('me')-beforeCachedReturn,1);meDelay=0;check('Only cached return refreshes saved journal once; normal load and repeated return do not race');
 for(const kind of ['worm','wind','typhoon','trouble']){
  challenges=[{id:'fixture-'+kind,status:'active',challenge_type:kind,challenge_date:'2026-10-10'}];await page.click('#switch-member');await page.waitForFunction(expected=>document.querySelector('#tree-art svg')?.dataset.careScene===expected,{},kind);await page.waitForFunction(()=>!document.querySelector('#switch-member').disabled);
  assert.equal(await page.$eval('#tree-challenge-notice',n=>n.hidden),false);assert.match(await page.$eval('#challenge-summary',n=>n.textContent),/1/);assert.equal(await page.$eval('#challenge-section',n=>n.open),true);assert.equal(await page.$eval('#health-badge',n=>n.textContent),'待照顧 1 項');assert(await page.$('#tree-art .care-scene-fx'));
  await page.waitForFunction(()=>!document.querySelector('.care-tool-success'));await page.$eval('.tree-card',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.screenshot({path:out+'/challenge-'+kind+'.png'});
  if(kind==='typhoon'){await page.setViewport({width:1440,height:900});await page.waitForSelector('#member-view:not([hidden])');await page.$eval('.tree-card',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.screenshot({path:out+'/challenge-desktop.png'});await page.setViewport({width:402,height:874,isMobile:true,hasTouch:true});await page.waitForSelector('#member-view:not([hidden])');}
  assert.equal(await page.$eval('#tree-care-tools button',n=>n.dataset.careType),kind);assert(await page.$eval('#tree-care-tools button',n=>n.querySelector('svg')&&n.getBoundingClientRect().width>=44&&n.getBoundingClientRect().height>=44));const wantedTrack=kind==='typhoon'||kind==='wind'?'storm':'care';await page.click('#tree-title');await page.waitForFunction(wanted=>{const a=document.querySelector('[data-life-tree-audio=music]');return a?.dataset.track===wanted&&!a.paused&&a.currentTime>.1;},{},wantedTrack);assert.equal(await page.$$eval('[data-life-tree-audio=music]',nodes=>nodes.length),1);
  const beforeLink=count('resolve_challenge');await page.focus('#go-care-challenges');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.matches('.tree-tool')),true);assert.equal(count('resolve_challenge'),beforeLink);await sleep(800);
  failAction='resolve_challenge';await page.click('#tree-care-tools button');await page.waitForFunction(()=>!document.querySelector('#tree-care-tools button').disabled&&document.querySelector('#tree-care-feedback').textContent.length>0);assert.equal(count('resolve_challenge'),beforeLink+1);assert.equal(await page.$eval('#tree-challenge-notice',n=>n.hidden),false);assert.match(await page.$eval('#challenge-feedback',n=>n.textContent),/連線|中斷|重試/);failAction='';
  writeDelay=150;const challengeBefore=count('resolve_challenge');await page.$eval('#tree-care-tools button',n=>window.__priorCareButton=n);await page.click('#tree-care-tools button');await page.$eval('#tree-care-tools button',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));assert(await page.$$eval('#tree-care-tools button,#active-challenges button',nodes=>nodes.every(n=>n.disabled)));await page.waitForFunction(()=>!document.querySelector('#active-challenges button'));assert.equal(count('resolve_challenge')-challengeBefore,1);await page.evaluate(()=>window.__priorCareButton.dispatchEvent(new MouseEvent('click',{bubbles:true})));assert.equal(count('resolve_challenge')-challengeBefore,1);writeDelay=0;assert.equal(await page.$eval('#tree-challenge-notice',n=>n.hidden),true);assert.equal(await page.$eval('#tree-art svg',n=>n.dataset.careScene),'none');assert.match(await page.$eval('#tree-care-feedback',n=>n.textContent),/照顧完成/);assert.equal(await page.$eval('#tree-care-tools',n=>n.hidden),true);assert.equal(calls.filter(c=>c.action==='resolve_challenge').at(-1).resolution,{worm:'pest',wind:'support',typhoon:'guard',trouble:'repair'}[kind]);assert(await page.$('.care-tool-success'));await page.waitForFunction(()=>{const a=document.querySelector('[data-life-tree-audio=music]');return a.dataset.track==='reading'&&!a.paused;});check(kind+' challenge: visible notice and distinctive scene; keyboard CTA; failure retains prompt; one success restores background');
 }
 challenges=[{id:'future',status:'active',challenge_type:'typhoon',challenge_date:'2026-10-11'},{id:'resolved',status:'resolved',challenge_type:'trouble',challenge_date:'2026-10-10'}];await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));assert.equal(await page.$eval('#tree-challenge-notice',n=>n.hidden),true);assert.equal(await page.$eval('#tree-art svg',n=>n.dataset.careScene),'none');assert.equal(await page.$eval('#challenge-count',n=>n.textContent),'0');check('Future and resolved challenges cannot trigger notice, count or altered background');
 challenges.push({id:'multi-worm',status:'active',challenge_type:'worm',challenge_date:'2026-10-10'},{id:'multi-wind',status:'active',challenge_type:'wind',challenge_date:'2026-10-10'});await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#tree-challenge-title').textContent.includes('2'));assert.equal(await page.$eval('#tree-art svg',n=>n.dataset.careScene),'wind');await page.click('#active-challenges button');await page.waitForFunction(()=>document.querySelector('#challenge-count').textContent==='1');assert.equal(await page.$eval('#tree-challenge-notice',n=>n.hidden),false);assert.equal(await page.$eval('#tree-art svg',n=>n.dataset.careScene),'worm');await page.click('#active-challenges button');await page.waitForFunction(()=>document.querySelector('#tree-challenge-notice').hidden);check('Multiple active challenges keep reminder and next scene until all current care is complete');
 challenges=['typhoon','worm','wind','trouble'].map(kind=>({id:'all-'+kind,status:'active',challenge_type:kind,challenge_date:'2026-10-10'}));await page.click('#switch-member');await page.waitForFunction(()=>document.querySelectorAll('#tree-care-tools button').length===4);await page.waitForFunction(()=>!document.querySelector('#switch-member').disabled);
 await page.waitForFunction(()=>!document.querySelector('.care-tool-success'));for(const width of [320,402,1440]){await page.setViewport({width,height:900,isMobile:width<600,hasTouch:width<600});await page.waitForSelector('#member-view:not([hidden])');await page.$eval('#tree-scene',n=>n.scrollIntoView({block:'center',behavior:'instant'}));const geometry=await page.evaluate(()=>{const scene=document.querySelector('#tree-scene').getBoundingClientRect(),buttons=[...document.querySelectorAll('#tree-care-tools button')];return buttons.map(n=>{const r=n.getBoundingClientRect();return {type:n.dataset.careType,inside:r.left>=scene.left&&r.right<=scene.right&&r.top>=scene.top&&r.bottom<=scene.bottom,hit:n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)),left:r.left,right:r.right,top:r.top,bottom:r.bottom};});});assert.equal(geometry.length,4);assert(geometry.every(g=>g.inside&&g.hit),JSON.stringify({width,geometry}));for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)assert(geometry[i].right<=geometry[j].left||geometry[j].right<=geometry[i].left||geometry[i].bottom<=geometry[j].top||geometry[j].bottom<=geometry[i].top);await sleep(250);await page.screenshot({path:out+'/tools-all-'+width+'.png'});}check('Four cute tools surround tree without covering each other at 320/402/1440px');assert(await page.$eval('#tree-art .tree-canopy>path',n=>n.getBoundingClientRect().height>50));check('Seedling stays visibly enlarged while its gentle sway animation runs');assert.match(await page.$eval('.tree-tool-wind',n=>n.textContent),/彼此扶持/);assert.equal(await page.$$eval('.tree-tool-wind svg>circle',n=>n.length),2);check('Wind tool presents two people shoulder to shoulder with mutual-support label');
 challenges=[{id:'worm-a',status:'active',challenge_type:'worm',challenge_date:'2026-10-09'},{id:'worm-b',status:'active',challenge_type:'worm',challenge_date:'2026-10-10'}];await page.click('#switch-member');await page.waitForFunction(()=>!document.querySelector('#switch-member').disabled);assert.equal(await page.$$eval('#tree-care-tools button',n=>n.length),1);assert.match(await page.$eval('#tree-care-tools button',n=>n.textContent),/2 項/);await page.click('#tree-care-tools button');await page.waitForFunction(()=>document.querySelector('#challenge-count').textContent==='1');assert.equal(await page.$$eval('#tree-care-tools button',n=>n.length),1);await page.click('#tree-care-tools button');await page.waitForFunction(()=>document.querySelector('#tree-care-tools').hidden);check('Repeated same-type challenges share one counted tool and resolve one record per click');challenges=[];await page.setViewport({width:402,height:874,isMobile:true,hasTouch:true});await page.waitForSelector('#member-view:not([hidden])');await page.click('#switch-member');await page.waitForFunction(()=>!document.querySelector('#switch-member').disabled);assert.equal(await page.$eval('#tree-care-tools',n=>n.hidden),true);await page.click('#go-tree-care');assert.match(await page.$eval('#tree-care-feedback',n=>n.textContent),/目前平安/);check('Healthy tree hides context tools and care shortcut gives clear feedback');
 await sleep(700);gardenDelay=350;await page.click('[data-tree-view=group]');assert.match(await page.$eval('#view-status',n=>n.textContent),/載入/);await page.waitForFunction(()=>document.querySelectorAll('.garden-tree-button').length===18);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),402);assert(await page.$eval('.garden-tree-button',n=>n.getBoundingClientRect().width>90));await page.screenshot({path:out+'/mobile-garden.png',fullPage:true});check('18-person garden uses readable rows without horizontal overflow');
 await page.click('[data-tree-view=church]');await page.click('[data-tree-view=personal]');await sleep(450);assert.equal(await page.$eval('.tree-view-button.active',n=>n.dataset.treeView),'personal');assert.equal(await page.$eval('#tree-art',n=>n.hidden),false);check('Late garden response cannot overwrite a newer personal view');await page.click('[data-tree-view=group]');await page.click('#go-tree-care');await sleep(800);assert.equal(await page.$eval('.tree-view-button.active',n=>n.dataset.treeView),'personal');assert.equal(await page.$eval('.tree-view-switch',n=>n.getAttribute('aria-busy')),'false');check('Care shortcut cancels a pending garden switch and remains at personal tree');
 await page.click('.leaderboard-card>summary');await page.waitForSelector('#leaderboard li');assert(count('leaderboard')>0);check('Ranking loads on demand');
 for(const width of [320,390,402,430,1280,1440,1920]){await page.setViewport({width,height:900,isMobile:width<600,hasTouch:width<600});await page.waitForSelector('#member-view:not([hidden])');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);const short=await page.evaluate(()=>[...document.querySelectorAll('button,a,input,select,summary')].filter(n=>!n.matches('input[type=checkbox]')&&n.getBoundingClientRect().height>0&&n.getBoundingClientRect().height<43.9).map(n=>({label:n.textContent.trim(),height:n.getBoundingClientRect().height})));assert.deepEqual(short,[]);const dateGrid=await page.evaluate(()=>{const dates=[...document.querySelectorAll('#makeup-dates button')].map(n=>n.getBoundingClientRect().toJSON()),other=document.querySelector('.makeup-other').getBoundingClientRect().toJSON();return {dates,other};});assert.equal(dateGrid.dates.length,7);assert.match(await page.$eval('#tree-weather',n=>n.textContent),/大雅｜/);assert.doesNotMatch(await page.$eval('#tree-weather',n=>n.textContent),/實際天氣/);assert(await page.$eval('#tree-weather',n=>{const range=document.createRange();range.selectNodeContents(n);return range.getBoundingClientRect().height<=parseFloat(getComputedStyle(n).lineHeight)+1;}),'Weather must fit one line at '+width);assert(dateGrid.dates.slice(0,4).every(r=>Math.abs(r.top-dateGrid.dates[0].top)<1));assert(dateGrid.dates.slice(4).every(r=>Math.abs(r.top-dateGrid.other.top)<1));assert(dateGrid.other.left>dateGrid.dates[6].left);assert(dateGrid.dates.every(r=>r.width>=44&&r.height>=44&&r.height<=70));if(width===402){await page.$eval('#makeup-section',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.screenshot({path:out+'/mobile-makeup.png'});}if(width===1440)await page.screenshot({path:out+'/desktop-1440.png',fullPage:true});}check('320–1920px layouts fit, controls meet 44px and compact makeup grid has 4 dates then 3 plus dropdown');
 await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0);check('Reduced-motion preference stops decorative animations');
 // Exercise failed Scripture and a timed-out shared source in fresh page loads (empty module cache).
 records=[];failScripture=true;await openTree();await page.click('#read-today');await page.waitForSelector('#scripture-text button');assert.equal(await page.$eval('#mark-read',n=>n.disabled),true);failScripture=false;await page.click('#scripture-text button');await page.waitForSelector('#scripture-end');check('Failed Scripture fetch offers a working retry');
 await openTree();await page.evaluate(()=>window.__shortDeadlines=true);scriptureDelay=250;await page.click('#read-today');await page.waitForSelector('#scripture-text button');scriptureDelay=0;await page.evaluate(()=>window.__shortDeadlines=false);await page.click('#scripture-text button');await page.waitForSelector('#scripture-end');check('Scripture deadline clears failed cache and permits retry');
 // Complete an earlier date without altering today's reading date or preview progress.
 await page.click('#makeup-dates button');await page.waitForSelector('#scripture-end');assert.equal(await page.$eval('#mark-late',n=>n.disabled),true);await page.$eval('#scripture-end',n=>n.scrollIntoView({block:'center',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#mark-late').disabled);const makeupBefore=count('mark_read');await page.click('#mark-late');await page.waitForFunction(()=>!document.querySelector('#care-tree').hidden);assert.equal(count('mark_read')-makeupBefore,1);assert.equal(records.at(-1).reading_date,'2026-10-09');await sleep(700);await page.click('#care-tree');await page.waitForFunction(()=>document.querySelector('#care-tree').hidden);assert.equal(records.at(-1).watered_at!==null,true);assert.equal(await page.$('#devotional-invitation'),null);assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);check('Makeup reading and watering use selected date without claiming today completion or showing floating invite');assert.doesNotMatch(await page.$eval('#mark-late',n=>n.textContent),/正在記錄/);check('Makeup completion cannot retain the pending save label');
 const startMakeup=async()=>{await page.click('#makeup-dates button');await page.waitForSelector('#scripture-end');await page.$eval('#scripture-end',n=>n.scrollIntoView({block:'center',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#mark-late').disabled);};
 await page.setViewport({width:402,height:874,isMobile:true,hasTouch:true});
 records=[{reading_date:'2026-10-10',completion_type:'on_time',watered_at:'2026-10-10T00:00:00Z'}];await page.evaluate(()=>{for(const key of Object.keys(sessionStorage))if(key.startsWith('october-devotional-dismissed:'))sessionStorage.removeItem(key);});await openTree();assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),false);await startMakeup();assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);writeDelay=250;const completedToday=JSON.stringify(records[0]),newMakeup=count('mark_read');await page.click('#mark-late');assert.match(await page.$eval('#mark-late',n=>n.textContent),/正在記錄/);assert.equal(await page.$eval('#complete-reading-actions',n=>n.getAttribute('aria-busy')),'true');await page.$eval('#read-today',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.$eval('#toggle-scripture',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));assert.equal(await page.$eval('#reading-date',n=>n.textContent),'10/9');assert.equal(await page.$eval('#scripture-text',n=>n.hidden),false);await page.$eval('#mark-late',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>document.querySelector('#mark-late').textContent.includes('已記錄'));assert.equal(count('mark_read')-newMakeup,1);assert.equal(await page.$eval('#late-date',n=>n.value),'');assert.equal(await page.$eval('#mark-late',n=>n.disabled),false);assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);assert.equal(JSON.stringify(records[0]),completedToday);await sleep(700);assert(await page.$eval('#care-tree',n=>{const r=n.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));await page.screenshot({path:out+'/makeup-saved-watering-visible.png'});await page.click('#mark-late');await sleep(700);assert.equal(count('mark_read')-newMakeup,1);assert.equal(await page.evaluate(()=>document.activeElement.id),'tree-water-stage');await page.click('#care-tree');await page.waitForFunction(()=>document.querySelector('#mark-late').textContent.includes('已澆水'));assert.equal(JSON.stringify(records[0]),completedToday);await page.click('#mark-late');await sleep(700);assert.equal(await page.evaluate(()=>document.activeElement.id),'tree-title');assert.equal(count('mark_read')-newMakeup,1);writeDelay=0;check('Today already watered plus makeup: pending resets, cleared selector still navigates, dock stays clear, no duplicate writes');
 records=[];await openTree();await startMakeup();failAction='mark_read';await page.click('#mark-late');await page.waitForFunction(()=>document.querySelector('#mark-late').textContent.includes('重試'));assert.equal(await page.$eval('#mark-late',n=>n.disabled),false);assert.match(await page.$eval('#scripture-read-hint',n=>n.textContent),/中斷|重試/);assert.equal(await page.$eval('#complete-reading-actions',n=>n.getAttribute('aria-busy')),'false');assert.equal(await page.$eval('#late-date',n=>n.value),'2026-10-09');await page.screenshot({path:out+'/makeup-failed-retry.png'});failAction='';await page.click('#mark-late');await page.waitForFunction(()=>document.querySelector('#mark-late').textContent.includes('已記錄'));assert.equal(records.filter(r=>r.reading_date==='2026-10-09').length,1);check('Failed makeup save restores local retry feedback and selected date; retry succeeds once');
 records=[];await openTree();await startMakeup();incompleteAction='mark_read';await page.click('#mark-late');await page.waitForFunction(()=>document.querySelector('#mark-late').textContent.includes('重試'));assert.match(await page.$eval('#scripture-read-hint',n=>n.textContent),/尚未確認/);assert.equal(await page.$eval('#care-tree',n=>n.hidden),true);incompleteAction='';const writesBeforeVerify=count('mark_read');await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));assert.match(await page.$eval('#mark-late',n=>n.textContent),/已記錄/);assert.doesNotMatch(await page.$eval('#scripture-read-hint',n=>n.textContent),/尚未確認/);await page.click('#mark-late');await sleep(700);assert.equal(count('mark_read'),writesBeforeVerify);assert.equal(records.filter(r=>r.reading_date==='2026-10-09').length,1);check('Incomplete response cannot invent success; progress refresh confirms stored date and clears stale error without writing again');
 records=[];await openTree();await startMakeup();await page.evaluate(()=>window.__shortApiDeadline=true);writeDelay=350;await page.click('#mark-late');await page.waitForFunction(()=>document.querySelector('#mark-late').textContent.includes('重試'));assert.equal(await page.$eval('#mark-late',n=>n.disabled),false);assert.match(await page.$eval('#scripture-read-hint',n=>n.textContent),/中斷|等待過久/);await sleep(400);writeDelay=0;await page.evaluate(()=>window.__shortApiDeadline=false);await page.click('#mark-late');await page.waitForFunction(()=>document.querySelector('#mark-late').textContent.includes('已記錄'));assert.equal(records.filter(r=>r.reading_date==='2026-10-09').length,1);check('Timed-out makeup save releases busy state; a late committed request can be retried without losing progress');

 failAction='me';await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('重試'));assert.equal(await page.$eval('#switch-member',n=>n.disabled),false);failAction='';check('Refresh failure restores controls and displays recovery');
 const previewCalls=calls.length;await page.goto(base+'/daily-devotional.html?church=M%2B&preview=1&from=untrusted&returnTo=https%3A%2F%2Fexample.invalid',{waitUntil:'networkidle0'});await page.waitForSelector('#complete');assert.equal(await page.$eval('#complete',n=>n.disabled),true);assert.equal(await page.$('.tree-return'),null);assert.match(await page.$eval('.topbar a',n=>n.href),/line-member.html/);assert.equal(calls.length,previewCalls);check('Ordinary devotional preview keeps existing member-menu return and ignores arbitrary destinations');
 await page.goto(base+'/daily-devotional.html?church=M%2B&preview=1&from=october-tree',{waitUntil:'networkidle0'});await page.waitForSelector('.tree-return');await page.click('.tree-return');await page.waitForSelector('#member-view:not([hidden])');assert.match(page.url(),/tree-reading-october-test.html/);check('Direct preview entry has a working fixed tree return');
 records=[{reading_date:'2026-10-09',completion_type:'on_time',watered_at:null}];await openTree();assert.equal(await page.$eval('#resume-watering',n=>n.hidden),false);assert.match(await page.$eval('#resume-watering',n=>n.textContent),/10\/9/);await page.click('#resume-watering');await sleep(700);assert(await page.$eval('#care-tree',n=>{const r=n.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));assert.match(await page.$eval('#care-tree',n=>n.textContent),/10\/9/);const pendingWater=count('water_tree');await page.click('#care-tree');await page.waitForFunction(()=>document.querySelector('#care-tree').hidden);assert.equal(count('water_tree')-pendingWater,1);assert.equal(calls.filter(c=>c.action==='water_tree').at(-1).date,'2026-10-09');assert.equal(await page.$eval('#resume-watering',n=>n.hidden),true);assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);check('Yesterday on-time reading without water has a dated resume path; success cannot mark today watered');
 // Reported 10/6 continuation must reveal the whole tree, not merely the water button.
 records=[{reading_date:'2026-10-06',completion_type:'late',watered_at:null},{reading_date:'2026-10-10',completion_type:'on_time',watered_at:'2026-10-10T00:00:00Z'}];challenges=[];
 for(const [width,height] of [[320,568],[402,600],[402,874],[1440,900]]){
  await page.setViewport({width,height,isMobile:width<600,hasTouch:width<600});await openTree();await page.click('#resume-watering');await sleep(800);
  const geometry=await page.evaluate(()=>{const tree=document.querySelector('#tree-scene').getBoundingClientRect(),button=document.querySelector('#care-tree'),r=button.getBoundingClientRect();return {tree:{top:tree.top,bottom:tree.bottom,width:tree.width},button:{top:r.top,bottom:r.bottom},height:innerHeight,hit:button.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)),controls:document.querySelectorAll('#tree-scene button,#tree-scene a').length,focus:document.activeElement.id};});
  assert(geometry.tree.top>=0&&geometry.tree.bottom<=height&&geometry.tree.width>=200&&geometry.button.top>=geometry.tree.bottom&&geometry.button.bottom<=height&&geometry.hit&&geometry.controls===0&&geometry.focus==='tree-water-stage',JSON.stringify({width,height,...geometry}));assert.match(await page.$eval('#care-tree',n=>n.textContent),/10\/6/);assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);await page.screenshot({path:out+'/resume-oct6-'+width+'x'+height+'.png'});
 }
 const oct6Water=count('water_tree');await page.click('#care-tree');await page.waitForFunction(()=>document.querySelector('#care-tree').hidden);assert.equal(count('water_tree')-oct6Water,1);assert.equal(calls.filter(c=>c.action==='water_tree').at(-1).date,'2026-10-06');assert.equal(records.find(r=>r.reading_date==='2026-10-10').watered_at,'2026-10-10T00:00:00Z');check('10/6 resume shows entire tree and external watering button in short/full mobile and desktop viewports; waters only 10/6');
 records=[{reading_date:'2026-10-06',completion_type:'late',watered_at:null}];await openTree();await page.click('#resume-watering');await sleep(800);assert.match(await page.$eval('#care-tree',n=>n.textContent),/10\/6/);records.push({reading_date:'2026-10-10',completion_type:'on_time',watered_at:null});await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));assert.match(await page.$eval('#care-tree',n=>n.textContent),/10\/6/);await page.click('#read-today');await sleep(800);assert.equal(await page.evaluate(()=>document.activeElement.id),'tree-water-stage');assert.match(await page.$eval('#care-tree',n=>n.textContent),/10\/10/);check('Today return reselects today and shares the visible tree landing');
 records=[{reading_date:'2026-10-01',completion_type:'on_time',watered_at:null}];await openTree();assert.equal(await page.$eval('#resume-watering',n=>n.hidden),true);assert.equal(await page.$eval('#care-tree',n=>n.hidden),true);check('Expired watering cannot expose a button that backend would reject');
 await page.click('#show-journey-guide');await page.$eval('#journey-guide-audio',n=>n.checked=false);await page.evaluate(()=>{window.__originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Storage blocked','SecurityError');};});await page.click('#journey-guide-start');assert.equal(await page.$eval('#journey-guide',n=>n.open),false);assert.equal(await page.$eval('#sound-toggle',n=>n.dataset.enabled),'false');await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));await page.evaluate(()=>Storage.prototype.setItem=window.__originalSet);check('Blocked preference storage cannot prevent closing explanation or using reading progress');
 assert.deepEqual(errors,[]);check('No uncaught browser exceptions');
 console.log('ALL CHECKS PASSED',checks.length);
}catch(error){failed=true;checks.push({name:'run',passed:false,error:error.stack});console.error(error.stack);}
finally{fs.writeFileSync(out+'/results.json',JSON.stringify({environment:'Chromium isolated synthetic LINE/API/Scripture; no external database access; no real-device or audible-output claims',checks,errors,calls},null,2));await browser?.close();server.close();if(failed)process.exitCode=1;}
