import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const {default:puppeteer}=await import(process.env.PUPPETEER_MODULE||'puppeteer-core');
const root=new URL('../../',import.meta.url).pathname,out=process.env.TREE_TEST_OUTPUT||new URL('./results/',import.meta.url).pathname;
fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html; charset=utf-8','.mjs':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
const checks=[],errors=[],calls=[];let records=[],notes=[],challenges=[],gardenDelay=0,writeDelay=0,meDelay=0,failAction='',failScripture=false,scriptureDelay=0,failed=false,browser;
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const count=action=>calls.filter(call=>call.action===action).length;
const check=(name,detail={})=>{checks.push({name,passed:true,...detail});console.log('PASS',name);};
const headers={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'*'};
try{
 browser=await puppeteer.launch({executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-first-run','--disable-background-networking','--autoplay-policy=document-user-activation-required'],userDataDir:fs.mkdtempSync(path.join(os.tmpdir(),'life-tree-'))});
 const page=await browser.newPage();await page.setBypassServiceWorker(true);
 await page.evaluateOnNewDocument(()=>{
  if(location.hostname!=='127.0.0.1')return;
  const RealDate=Date;window.Date=class extends RealDate{constructor(...args){super(...(args.length?args:['2026-10-10T08:00:00+08:00']));}static now(){return new RealDate('2026-10-10T08:00:00+08:00').getTime();}};
  const nativeTimeout=window.setTimeout;window.setTimeout=(callback,ms,...args)=>nativeTimeout(callback,window.__shortDeadlines&&ms===15000?100:ms,...args);
  window.__contexts=[];const Audio=window.AudioContext;if(Audio)window.AudioContext=class extends Audio{constructor(...args){super(...args);window.__contexts.push(this);}resume(){return window.__audioFailure?Promise.reject(Error('test audio unavailable')):super.resume();}};
 });
 page.on('pageerror',error=>errors.push(error.message));
 await page.setRequestInterception(true);
 page.on('request',async request=>{try{
  const url=new URL(request.url());if(url.origin===base)return request.continue();
  if(url.href.includes('sdk.js'))return request.respond({status:200,contentType:'application/javascript',body:'window.liff={init:async()=>{},isInClient:()=>true,isLoggedIn:()=>true,getIDToken:()=>"isolated-fixture"}'});
  if(url.hostname.endsWith('supabase.co')){
   if(request.method()==='OPTIONS')return request.respond({status:200,headers,body:'{}'});
   const body=JSON.parse(request.postData()||'{}');calls.push({action:body.action,date:body.readingDate,endpoint:url.pathname});
   if(body.action==='me'&&meDelay)await sleep(meDelay);
   if(body.action===failAction)return request.respond({status:503,contentType:'application/json',headers,body:'{"error":"unavailable"}'});
   let data={};
   if(body.action==='me')data={participant:{id:'fixture-member',display_name:'測試同工',reading_start_date:'2026-10-01'},records,challenges,notes};
   if(body.action==='garden'){await sleep(gardenDelay);data={trees:Array.from({length:18},(_,index)=>({display_name:'同工'+(index+1),tree_number:index+1,completed_count:9,on_time_count:8}))};}
   if(body.action==='leaderboard')data={members:[{display_name:'測試同工',on_time_count:9}]};
   if(['mark_read','water_tree','resolve_challenge','journal_save'].includes(body.action))await sleep(writeDelay);
   if(body.action==='mark_read'){records=records.filter(row=>row.reading_date!==body.readingDate).concat({reading_date:body.readingDate,completion_type:body.readingDate==='2026-10-10'?'on_time':'makeup',watered_at:null});data={records,completion_type:body.readingDate==='2026-10-10'?'on_time':'makeup'};}
   if(body.action==='water_tree'){records=records.map(row=>row.reading_date===body.readingDate?{...row,watered_at:'2026-10-10T00:01:00Z'}:row);data={records};}
   if(body.action==='journal_save'){notes=[{reading_date:body.readingDate,note:body.note}];}
   if(body.action==='resolve_challenge'){challenges=challenges.map(row=>row.id===body.challengeId?{...row,status:'resolved'}:row);data={challenges};}
   return request.respond({status:200,contentType:'application/json',headers,body:JSON.stringify(data)});
  }
  if(url.hostname==='raw.githubusercontent.com'){
   await sleep(scriptureDelay);
   return request.respond({status:failScripture?503:200,contentType:'application/json',headers,body:JSON.stringify({chapters:Array.from({length:31},()=>Array.from({length:30},(_,index)=>`${index+1} 隔離測試文字：智慧使人明白道路，願神的話成為今天腳前的燈，路上的光。`))})});
  }
  if(url.hostname==='api.open-meteo.com')return request.respond({status:200,contentType:'application/json',headers,body:JSON.stringify({current:{weather_code:2,temperature_2m:26,wind_speed_10m:9,time:'2026-10-10T08:00'}})});
  return request.abort();
 }catch(error){if(!/already handled|closed|Invalid InterceptionId/i.test(error.message))errors.push('interception: '+error.message);}});
 const openTree=async()=>{await page.goto(base+'/tree-reading-october-test.html',{waitUntil:'networkidle0'});await page.waitForSelector('#member-view:not([hidden])');};
 await page.setViewport({width:402,height:874,isMobile:true,hasTouch:true});await page.goto(base+'/tree-reading-october-test.html',{waitUntil:'networkidle0'});await page.evaluate(()=>localStorage.setItem('lifeTreeSound','off'));await openTree();
 assert.equal(await page.$eval('#sound-toggle',n=>n.textContent),'播放音樂');assert.equal(await page.evaluate(()=>window.__contexts.length),0);assert.equal(count('garden'),0);assert.equal(count('leaderboard'),0);check('Remember muted preference; hidden garden/ranking not requested on entry');
 assert(await page.$eval('#read-today',n=>n.getBoundingClientRect().bottom<innerHeight));assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),402);await page.screenshot({path:out+'/mobile-initial.png',fullPage:true});check('Reading entry visible on first 402×874 screen; no devotional dock before watering');
 const before=count('me');meDelay=350;await page.click('#switch-member');await page.$eval('#switch-member',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));assert.equal(count('me')-before,1);meDelay=0;check('Refresh button works and ignores repeat clicks');
 await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');assert.equal(await page.evaluate(()=>window.__contexts[0].state),'running');await page.tap('#sound-toggle');assert.equal(await page.evaluate(()=>localStorage.getItem('lifeTreeSound')),'off');check('Explicit music touch starts audio; pause stores preference');
 await page.evaluate(()=>window.__audioFailure=true);await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#music-status').textContent.includes('重試'));assert.equal(await page.$eval('#sound-toggle',n=>n.getAttribute('aria-pressed')),'false');assert.equal(await page.$eval('#sound-toggle',n=>n.disabled),false);await page.evaluate(()=>window.__audioFailure=false);check('Audio failure shows retry without claiming playback');
 await page.tap('#sound-toggle');await page.waitForFunction(()=>document.querySelector('#sound-toggle').getAttribute('aria-pressed')==='true');await page.tap('#sound-toggle');
 await page.click('#read-today');await page.waitForSelector('#scripture-end');assert.equal(await page.$eval('#mark-read',n=>n.disabled),true);await page.$eval('#scripture-end',n=>n.scrollIntoView({block:'center',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#mark-read').disabled);check('Today reading requires reaching Scripture end');
 writeDelay=350;await page.click('#mark-read');assert.match(await page.$eval('#mark-read',n=>n.textContent),/記錄/);await page.$eval('#mark-read',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>!document.querySelector('#care-tree').hidden);assert.equal(count('mark_read'),1);check('Read request has pending state and duplicate guard');
 failAction='water_tree';await page.click('#care-tree');await page.waitForFunction(()=>!document.querySelector('#care-tree').disabled);assert.equal(await page.$eval('#devotional-invitation',n=>n.hidden),true);assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);check('Failed watering remains retryable and does not unlock preview or floating dock');
 failAction='';const waterBefore=count('water_tree');await page.click('#care-tree');assert.equal(await page.$eval('#care-tree',n=>n.textContent),'正在澆水…');await page.$eval('#care-tree',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>!document.querySelector('#devotional-invitation').hidden);assert.equal(count('water_tree')-waterBefore,1);assert(await page.$('.care-animation'));check('Watering success unlocks invitation once and preserves celebration');
 await page.screenshot({path:out+'/mobile-watered.png',fullPage:true});
 assert(await page.$eval('#devotional-dock-link',n=>{const r=n.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));assert(await page.$eval('#devotional-invitation',n=>n.compareDocumentPosition(document.querySelector('.tree-card'))&Node.DOCUMENT_POSITION_FOLLOWING));check('Watering success puts clickable invitation in the current viewport and permanent entry before tree');
 for(const [width,height] of [[320,568],[390,844],[402,874],[430,900],[1280,900],[1440,900],[1920,900],[402,420]]){await page.setViewport({width,height,isMobile:width<600,hasTouch:width<600});await page.$eval('.tree-card',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#devotional-dock').hidden);assert(await page.$eval('#devotional-dock',n=>{const r=n.getBoundingClientRect();return !n.hidden&&r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}));assert(await page.$eval('#devotional-dock-link',n=>n.getBoundingClientRect().height>=44));assert(await page.$eval('#dismiss-devotional-dock',n=>n.getBoundingClientRect().height>=44));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);}check('Floating invitation fits mobile, short and desktop viewports with 44px controls');
 await page.setViewport({width:402,height:874,isMobile:true,hasTouch:true});await page.$eval('.tree-card',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#devotional-dock').hidden);await page.screenshot({path:out+'/mobile-watered-viewport.png'});
 await page.$eval('#devotional-invitation',n=>n.scrollIntoView({block:'center',behavior:'instant'}));await page.waitForFunction(()=>document.querySelector('#devotional-dock').hidden);assert(await page.$eval('#devotional-preview-link',n=>{const r=n.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}));await page.$eval('.tree-card',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#devotional-dock').hidden);check('Upper entry visibility suppresses duplicate floating card; scrolling away restores it');
 await page.focus('#reflection-note');assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);await page.$eval('#reflection-note',n=>n.blur());await page.waitForFunction(()=>!document.querySelector('#devotional-dock').hidden);check('Floating invitation hides while writing and returns after leaving the input');
 await page.$eval('#reflection-note',n=>n.value='尚未收藏的測試拾光');const callsBeforePreview=calls.length;await page.click('#devotional-dock-link');await page.waitForSelector('.tree-return');assert.equal(await page.$eval('#complete',n=>n.disabled),true);assert.match(await page.$eval('#status',n=>n.textContent),/創世記試閱/);assert.equal(calls.length,callsBeforePreview);await page.click('.tree-return');await page.waitForSelector('#member-view:not([hidden])');assert.equal(await page.$eval('#devotional-invitation',n=>n.hidden),false);assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);assert.equal(records.length,1);assert.equal(await page.$eval('#reflection-note',n=>n.value),'尚未收藏的測試拾光');check('Floating entry and fixed return preserve October progress and draft without repeating the invitation');
 await page.evaluate(()=>{for(const key of Object.keys(sessionStorage))if(key.startsWith('october-devotional-dismissed:'))sessionStorage.removeItem(key);});await openTree();await page.$eval('.tree-card',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#devotional-dock').hidden);await page.click('#dismiss-devotional-dock');await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('已更新'));assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);assert.equal(await page.$eval('#devotional-invitation',n=>n.hidden),false);check('Dismissal survives progress refresh and keeps the permanent upper entry');
 const upperCalls=calls.length;await page.click('#devotional-preview-link');await page.waitForSelector('.tree-return');assert.equal(calls.length,upperCalls);await page.click('.tree-return');await page.waitForSelector('#member-view:not([hidden])');check('Permanent upper devotional entry still works after dismissing floating invitation');
 failAction='journal_save';await page.click('#save-reflection');await page.waitForFunction(()=>!document.querySelector('#save-reflection').disabled);assert.equal(await page.$eval('#reflection-note',n=>n.value),'尚未收藏的測試拾光');failAction='';const journalBefore=count('journal_save');await page.click('#save-reflection');await page.$eval('#save-reflection',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>document.querySelector('#reflection-status').textContent.includes('已收藏'));assert.equal(count('journal_save')-journalBefore,1);assert.equal(notes.length,1);check('Journal failure retains input; success ignores repeat submissions');
 challenges=[{id:'fixture-challenge',status:'active',challenge_type:'worm',challenge_date:'2026-10-10'}];await page.click('#switch-member');await page.waitForSelector('#active-challenges button');assert.equal(await page.$eval('#challenge-section',n=>n.open),true);failAction='resolve_challenge';await page.click('#active-challenges button');await page.waitForFunction(()=>!document.querySelector('#active-challenges button').disabled);failAction='';const challengeBefore=count('resolve_challenge');await page.click('#active-challenges button');await page.$eval('#active-challenges button',n=>n.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForFunction(()=>!document.querySelector('#active-challenges button'));assert.equal(count('resolve_challenge')-challengeBefore,1);check('Active challenge opens, failure recovers, and success runs once');
 gardenDelay=350;await page.click('[data-tree-view=group]');assert.match(await page.$eval('#view-status',n=>n.textContent),/載入/);await page.waitForFunction(()=>document.querySelectorAll('.garden-tree-button').length===18);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),402);assert(await page.$eval('.garden-tree-button',n=>n.getBoundingClientRect().width>90));await page.screenshot({path:out+'/mobile-garden.png',fullPage:true});check('18-person garden uses readable rows without horizontal overflow');
 await page.click('[data-tree-view=church]');await page.click('[data-tree-view=personal]');await sleep(450);assert.equal(await page.$eval('.tree-view-button.active',n=>n.dataset.treeView),'personal');assert.equal(await page.$eval('#tree-art',n=>n.hidden),false);check('Late garden response cannot overwrite a newer personal view');
 await page.click('.leaderboard-card>summary');await page.waitForSelector('#leaderboard li');assert(count('leaderboard')>0);check('Ranking loads on demand');
 for(const width of [320,390,402,430,1280,1440,1920]){await page.setViewport({width,height:900,isMobile:width<600,hasTouch:width<600});await page.waitForSelector('#member-view:not([hidden])');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);const short=await page.evaluate(()=>[...document.querySelectorAll('button,a,input,select,summary')].filter(n=>n.getBoundingClientRect().height>0&&n.getBoundingClientRect().height<43.9).map(n=>({label:n.textContent.trim(),height:n.getBoundingClientRect().height})));assert.deepEqual(short,[]);if(width===1440)await page.screenshot({path:out+'/desktop-1440.png',fullPage:true});}check('320–1920px layouts fit and visible controls meet 44px height');
 await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0);check('Reduced-motion preference stops decorative animations');
 // Exercise failed Scripture and a timed-out shared source in fresh page loads (empty module cache).
 records=[];failScripture=true;await openTree();await page.click('#read-today');await page.waitForSelector('#scripture-text button');assert.equal(await page.$eval('#mark-read',n=>n.disabled),true);failScripture=false;await page.click('#scripture-text button');await page.waitForSelector('#scripture-end');check('Failed Scripture fetch offers a working retry');
 await openTree();await page.evaluate(()=>window.__shortDeadlines=true);scriptureDelay=250;await page.click('#read-today');await page.waitForSelector('#scripture-text button');scriptureDelay=0;await page.evaluate(()=>window.__shortDeadlines=false);await page.click('#scripture-text button');await page.waitForSelector('#scripture-end');check('Scripture deadline clears failed cache and permits retry');
 // Complete an earlier date without altering today's reading date or preview progress.
 await page.select('#late-date','2026-10-09');await page.waitForFunction(()=>!document.querySelector('#mark-late').disabled);const makeupBefore=count('mark_read');await page.click('#mark-late');await page.waitForFunction(()=>!document.querySelector('#care-tree').hidden);assert.equal(count('mark_read')-makeupBefore,1);assert.equal(records.at(-1).reading_date,'2026-10-09');await page.click('#care-tree');await page.waitForFunction(()=>document.querySelector('#care-tree').hidden);assert.equal(records.at(-1).watered_at!==null,true);assert.equal(await page.$eval('#devotional-invitation',n=>n.hidden),true);assert.equal(await page.$eval('#devotional-dock',n=>n.hidden),true);check('Makeup reading and watering use selected date without unlocking today preview');
 failAction='me';await page.click('#switch-member');await page.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('重試'));assert.equal(await page.$eval('#switch-member',n=>n.disabled),false);failAction='';check('Refresh failure restores controls and displays recovery');
 const previewCalls=calls.length;await page.goto(base+'/daily-devotional.html?church=M%2B&preview=1&from=untrusted&returnTo=https%3A%2F%2Fexample.invalid',{waitUntil:'networkidle0'});await page.waitForSelector('#complete');assert.equal(await page.$eval('#complete',n=>n.disabled),true);assert.equal(await page.$('.tree-return'),null);assert.match(await page.$eval('.topbar a',n=>n.href),/line-member.html/);assert.equal(calls.length,previewCalls);check('Ordinary devotional preview keeps existing member-menu return and ignores arbitrary destinations');
 await page.goto(base+'/daily-devotional.html?church=M%2B&preview=1&from=october-tree',{waitUntil:'networkidle0'});await page.waitForSelector('.tree-return');await page.click('.tree-return');await page.waitForSelector('#member-view:not([hidden])');assert.match(page.url(),/tree-reading-october-test.html/);check('Direct preview entry has a working fixed tree return');
 assert.deepEqual(errors,[]);check('No uncaught browser exceptions');
 console.log('ALL CHECKS PASSED',checks.length);
}catch(error){failed=true;checks.push({name:'run',passed:false,error:error.stack});console.error(error.stack);}
finally{fs.writeFileSync(out+'/results.json',JSON.stringify({environment:'Chromium isolated synthetic LINE/API/Scripture; no external database access; no real-device or audible-output claims',checks,errors,calls},null,2));await browser?.close();server.close();if(failed)process.exitCode=1;}
