import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {FESTIVALS,MONSTERS,festivalForDate,decorationForDate,festivalDay} from '../../life-tree-festivals.mjs';
import {festivalScene,festivalEquipment} from '../../life-tree-festival-art.mjs';
import {availableFunctionKeys,availableSettingsGroups} from '../../app-function-catalog.mjs';
const {default:puppeteer}=await import(process.env.PUPPETEER_MODULE||'puppeteer-core');
const root=new URL('../../',import.meta.url).pathname,output=process.env.TREE_TEST_OUTPUT||'/tmp/life-tree-festivals-results';
fs.mkdirSync(output,{recursive:true});
const checks=[],errors=[],external=[],missing=[];
const check=(name,detail={})=>{checks.push({name,passed:true,...detail});console.log('PASS',name);};
const types={'.html':'text/html; charset=utf-8','.mjs':'text/javascript','.css':'text/css','.wav':'audio/wav'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
let browser,failed=false;
try{
 assert.equal(FESTIVALS.length,9);assert.equal(new Set(FESTIVALS.map(item=>item.id)).size,9);
 for(const item of FESTIVALS){assert.equal(item.days.length,item.id==='newyear'?3:7);for(const content of item.days)assert(content.title&&content.reference&&content.reflection&&content.prompt);assert.equal(festivalForDate(item.start),item);assert.equal(festivalForDate(item.end),item);assert.equal(festivalDay(item,item.end),item.days.length);}
 assert.equal(festivalForDate('2027-01-04'),null);assert.equal(festivalForDate('2028-12-25'),null);assert.equal(festivalForDate('x'),null);assert.equal(festivalDay(FESTIVALS[0],'bad'),1);
 check('Nine distinct festival calendars and all 59 candidate scripture/reflection/prompt sets');
 for(let day=1;day<=31;day++)assert.equal(decorationForDate('2027-12-'+String(day).padStart(2,'0')).id,'christmas');
 for(const date of ['2027-11-30','2028-01-01','2027-12-32','2027-12-00','2026-12-25',null])assert.equal(decorationForDate(date),null);
 assert.equal(festivalForDate('2027-12-05'),null);assert.equal(festivalForDate('2027-12-25').id,'christmas');check('Christmas decoration applies every December day, with the activity week separately selected');
 const treeAccess={grants:['members','tree_reading_admin'].map(permission=>({church_id:'M+',permission})),featurePermissions:[]};
 assert(availableFunctionKeys(treeAccess,'M+').includes('life_tree_festivals'));assert(availableSettingsGroups(treeAccess,'M+').some(group=>group.key==='content'&&group.keys.includes('life_tree_festivals')));
 assert(!availableFunctionKeys({grants:[],featurePermissions:[]},'M+').includes('life_tree_festivals'));assert(!availableFunctionKeys(treeAccess,'SHiNE').includes('life_tree_festivals'));
 check('Preview settings use existing M+ tree permission; no new grant or home allowlist change');
 assert.equal(new Set(MONSTERS.map(item=>item.tool)).size,7);assert.equal(new Set(Array.from({length:7},(_,i)=>festivalEquipment(i+1))).size,7);
 check('Seven monsters have seven distinct equipment illustrations');
 for(const item of FESTIVALS){const buffer=fs.readFileSync(path.join(root,'assets/audio/life-tree/festivals',item.id+'.wav'));assert.equal(buffer.toString('ascii',0,4),'RIFF');assert.equal(buffer.readUInt32LE(24),22050);let squares=0,peak=0;for(let i=44;i<buffer.length;i+=2){const sample=buffer.readInt16LE(i)/32768;squares+=sample*sample;peak=Math.max(peak,Math.abs(sample));}assert(peak<.36&&peak>.34);assert(Math.sqrt(squares/((buffer.length-44)/2))>.03);}
 check('All nine original seasonal music loops contain audible PCM without clipping');
 browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage();page.on('pageerror',error=>errors.push(error.message));await page.setRequestInterception(true);page.on('request',request=>{if(!request.url().startsWith(base)){external.push(request.url());return request.abort();}request.continue();});page.on('response',response=>{if(response.status()>=400&&!response.url().endsWith('favicon.ico'))missing.push(response.url());});
 const open=async(query='',width=402,height=874)=>{await page.setViewport({width,height,isMobile:width<800,hasTouch:width<800});await page.goto(base+'/life-tree-festivals.html'+query,{waitUntil:'networkidle0'});await page.waitForSelector('#festival-art svg');};
 const click=async selector=>{await page.$eval(selector,node=>node.scrollIntoView({block:'center',behavior:'instant'}));await page.click(selector);};
 const idle=()=>page.waitForFunction(()=>!document.querySelector('#festival-action').disabled);
 for(const [width,height] of [[320,568],[402,874],[760,900],[1024,768],[1280,800],[1440,900],[1920,1080]]){await open('?festival=christmas',width,height);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(width===1440)await page.screenshot({path:output+'/desktop-christmas.png',fullPage:true});check(`No page overflow and Christmas renders: ${width}×${height}`);}
 await open('?festival=christmas');
 const targets=await page.$$eval('button',nodes=>nodes.filter(n=>!n.hidden&&n.getClientRects().length&&!n.disabled).map(n=>({id:n.id,width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})).filter(n=>n.width<43.9||n.height<43.9));assert.deepEqual(targets,[]);check('All visible enabled controls have at least 44×44px hit targets');
 for(const item of FESTIVALS){await click(`[data-festival="${item.id}"]`);assert.equal(await page.$eval('body',n=>n.dataset.festival),item.id);assert.match(await page.$eval('#festival-title',n=>n.textContent),new RegExp(item.title));await page.$eval('#festival-world',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.screenshot({path:output+'/mobile-'+item.id+'.png'});check(`Mobile world, original motifs and candidate content: ${item.name}`);}
 await click('[data-festival="christmas"]');assert.equal(await page.$$eval('.festival-bulb',n=>n.length),19);assert(await page.$('.festival-christmas-decor'));assert(await page.$('.festival-manger-glow'));check('Christmas tree has 19 animated bulbs, baubles, bow, top star and gifts; week includes manger');
 await click('#festival-pat');assert.match(await page.$eval('#festival-toast',n=>n.textContent),/聖誕燈/);check('Tree pat animates and announces Christmas greeting');
 await click('#festival-action');await page.$eval('#festival-action',n=>n.click());assert.equal(await page.$eval('#festival-scene',n=>n.dataset.phase),'watering');await idle();assert.equal(await page.$eval('#festival-scene',n=>n.dataset.phase),'ready');
 for(let i=0;i<3;i++){await click('#festival-hotspot');await page.$eval('#festival-action',n=>n.click());await idle();}
 assert.equal(await page.$eval('#festival-scene',n=>n.dataset.phase),'complete');assert.equal(await page.$eval('#festival-hit-count',n=>n.textContent),'3 / 3');check('Watering and three interactions animate, ignore duplicates and finish without hanging');
 await click('#festival-action');assert.equal(await page.$eval('#festival-day-label',n=>n.textContent),'第 2 天');await click('#festival-action');await click('[data-festival="moon"]');await new Promise(resolve=>setTimeout(resolve,1400));assert.equal(await page.$eval('body',n=>n.dataset.festival),'moon');assert.equal(await page.$eval('#festival-scene',n=>n.dataset.phase),'idle');check('Switching world during watering cancels old action and does not apply completion to another world');
 await click('#festival-motion');assert.equal(await page.$eval('.festival-canopy',n=>getComputedStyle(n).animationName),'none');check('Manual reduced motion stops animations');
 for(const item of FESTIVALS){await click(`[data-festival="${item.id}"]`);for(let day=1;day<=item.days.length;day++){await click(`[data-day="${day}"]`);if(item.id==='light'){assert.equal(await page.$eval('#festival-monster-name',n=>n.textContent),MONSTERS[day-1].name);assert.equal(await page.$eval('#festival-equipment-art svg',n=>Number(n.dataset.equipment)),day);}if(await page.$eval('#festival-scene',n=>n.dataset.phase)!=='complete'){for(let i=0;i<4;i++){await click('#festival-action');await idle();}}assert.equal(await page.$eval('#festival-scene',n=>n.dataset.phase),'complete');}check(`All ${item.days.length} days complete and collect exactly once: ${item.name}`);}
 assert.equal(await page.$eval('#festival-collection-count',n=>n.textContent),'9');await click('#festival-replay');for(let i=0;i<4;i++){await click('#festival-action');await idle();}assert.equal(await page.$eval('#festival-collection-count',n=>n.textContent),'9');check('Replay preserves earned badges and never duplicates a collection');
 await click('#festival-collection');assert(await page.$eval('#festival-dialog',n=>n.open));assert.equal(await page.$$eval('.festival-badge[data-earned=true]',n=>n.length),9);assert.equal(await page.$eval('body',n=>n.style.overflow),'hidden');await page.keyboard.press('Escape');assert.equal(await page.$eval('#festival-dialog',n=>n.open),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'festival-collection');check('Collection modal locks background, Escape closes and restores focus');
 await open('?date=2027-01-02');assert.equal(await page.$eval('body',n=>n.dataset.festival),'newyear');assert.equal(await page.$eval('#festival-day-label',n=>n.textContent),'第 2 天');assert.equal(await page.$$eval('.festival-day:not([hidden])',n=>n.length),3);assert.equal(await page.$$eval('.festival-firework-burst',n=>n.length),3);assert.match(await page.$eval('.festival-newyear-heading',n=>n.textContent),/2027新年快樂/);assert.equal(await page.$('.festival-monster'),null);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:output+'/newyear-402.png'});check('New Year covers January 1–3 with three preview days, fireworks and 2027 greeting');
 await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);assert.equal(await page.$eval('.festival-firework-burst',n=>getComputedStyle(n).animationName),'none');await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);check('New Year fireworks respect reduced motion without hiding the greeting');
 await open('?date=2027-12-05');assert(await page.$('.festival-christmas-decor'));assert.equal(await page.$('.festival-manger-glow'),null);assert.match(await page.$eval('#festival-period',n=>n.textContent),/12\/01 — 12\/31/);check('December outside Christmas week shows decorated tree without premature Nativity scene');
 await open('?date=2027-12-25');assert(await page.$('.festival-manger-glow'));check('Christmas week automatically includes the Nativity scene');
 await open('?festival=light&day=1.6');assert.equal(await page.$eval('#festival-day-label',n=>n.textContent),'第 2 天');check('Fractional preview day is safely normalized');
 await open('?festival=easter&day=6');assert.equal(await page.$eval('.festival-tomb-glow',n=>Number(n.style.opacity)),0);await click('[data-day="7"]');assert.equal(await page.$eval('.festival-tomb-glow',n=>Number(n.style.opacity)),1);check('Holy Saturday has closed stone; resurrection scene follows calendar day seven, not a game reward');
 await page.evaluate(()=>{window.__play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=()=>Promise.reject(new DOMException('test denial','NotAllowedError'));});await click('#festival-sound');await page.waitForFunction(()=>document.querySelector('#festival-audio-status').textContent.includes('重試'));assert.equal(await page.$eval('#festival-sound',n=>n.getAttribute('aria-pressed')),'false');await page.evaluate(()=>HTMLMediaElement.prototype.play=window.__play);await click('#festival-sound');await page.waitForFunction(()=>document.querySelector('#festival-audio-status').textContent.includes('正在播放'));check('Autoplay denial gives recoverable speaker retry and trusted click resumes native audio');
 await click('[data-festival="christmas"]');await page.waitForFunction(()=>document.querySelector('#festival-audio-status').textContent.includes('聖誕節'));await click('#festival-sound');check('Music switches with world; speaker mutes');
 await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);assert.equal(await page.$eval('.festival-bulb',n=>getComputedStyle(n).animationName),'none');check('System reduced-motion setting stops Christmas light animation');
 await open('?festival=christmas');assert.equal(await page.$eval('#festival-collection-count',n=>n.textContent),'0');assert.equal(await page.$eval('#festival-scene',n=>n.dataset.phase),'idle');assert((await page.evaluate(()=>Object.keys(localStorage))).every(key=>['lifeTreeSound','lifeTreeFestivalMotion'].includes(key)));check('Reload clears all preview progress; browser stores only sound/motion preferences');
 await click('#festival-action');await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});assert.equal(await page.$eval('#festival-action',n=>n.disabled),false);assert.equal(await page.$eval('#festival-scene',n=>n.dataset.phase),'idle');check('Returning from page cache during an animation restores an actionable state');
 await page.evaluate(()=>{window.__play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=()=>new Promise(()=>{});});await click('#festival-sound');await page.waitForFunction(()=>document.querySelector('#festival-audio-status').textContent.includes('重試'),{timeout:9000});assert.equal(await page.$eval('#festival-action',n=>n.disabled),false);await page.evaluate(()=>HTMLMediaElement.prototype.play=window.__play);await click('#festival-pat');await page.waitForFunction(()=>document.querySelector('#festival-audio-status').textContent.includes('正在播放'));check('Audio timeout leaves controls usable; remembered preference resumes on an ordinary trusted tap');await click('#festival-sound');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(missing,[]);check('No script errors, external/auth/database calls or missing resources');
}catch(error){failed=true;console.error(error);checks.push({name:'Run failure',passed:false,error:error.stack});}finally{await browser?.close();server.close();fs.writeFileSync(output+'/results.json',JSON.stringify({checks,errors,external,missing,passed:!failed},null,2));}
if(failed)process.exitCode=1;
