import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const {default:puppeteer}=await import(process.env.PUPPETEER_MODULE||'puppeteer-core');
const root=new URL('../../',import.meta.url).pathname;
const output=process.env.TREE_TEST_OUTPUT||'/tmp/life-tree-garden-preview-results';
fs.mkdirSync(output,{recursive:true});
const types={'.html':'text/html; charset=utf-8','.mjs':'text/javascript','.css':'text/css','.wav':'audio/wav'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`,checks=[],errors=[],external=[],missing=[];
const check=(name,detail={})=>{checks.push({name,passed:true,...detail});console.log('PASS',name);};
let browser,failed=false;
try{
 browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage();page.on('pageerror',error=>errors.push(error.message));await page.setRequestInterception(true);page.on('request',request=>{if(!request.url().startsWith(base)){external.push(request.url());return request.abort();}request.continue();});page.on('response',response=>{if(response.status()>=400&&!response.url().endsWith('favicon.ico'))missing.push(response.url());});
 const open=async(width=402,height=874)=>{await page.setViewport({width,height,isMobile:width<761,hasTouch:width<761});await page.goto(base+'/life-tree-garden-preview.html',{waitUntil:'networkidle0'});await page.waitForSelector('#garden-art svg');};
 const click=async selector=>{await page.$eval(selector,node=>node.scrollIntoView({block:'center',behavior:'instant'}));await page.click(selector);};
 const overflow=()=>page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 for(const [width,height] of [[320,568],[402,874],[760,900],[1024,768],[1280,800],[1440,900],[1920,1080]]){
   await open(width,height);assert.equal(await overflow(),false);const layout=await page.evaluate(()=>({tree:document.querySelector('#garden-scene').getBoundingClientRect().toJSON(),read:document.querySelector('#primary-action').getBoundingClientRect().toJSON(),height:innerHeight}));assert(layout.tree.top<layout.height/2&&layout.tree.bottom<layout.height,JSON.stringify(layout));if(width===402){assert(layout.read.bottom<layout.height);await page.screenshot({path:output+'/mobile-home.png',fullPage:true});await page.screenshot({path:output+'/mobile-first-screen.png'});}if(width===1440)await page.screenshot({path:output+'/desktop-home.png'});check(`Garden is visible in first screen, no horizontal overflow: ${width}×${height}`);
 }
 await open();assert.equal(await page.$eval('#devotional-invite',n=>n.hidden),true);assert.equal(await page.$eval('#care-tools',n=>n.hidden),true);check('Healthy tree has no permanent large overlay and no devotional invite before watering');
 await click('#touch-tree');assert.match(await page.$eval('#world-feedback',n=>n.textContent),/打招呼/);check('Tree responds to a touch');
 await click('#primary-action');assert(await page.$eval('#garden-dialog',n=>n.open));await click('#finish-reading');assert.equal(await page.$eval('#garden-dialog',n=>n.open),false);assert.match(await page.$eval('#primary-action',n=>n.textContent),/為小樹澆水/);assert.equal(await page.$eval('#primary-action',n=>n.parentElement.id),'world-action-slot');await new Promise(resolve=>setTimeout(resolve,650));const waterLayout=await page.evaluate(()=>({tree:document.querySelector('#garden-scene').getBoundingClientRect().toJSON(),button:document.querySelector('#primary-action').getBoundingClientRect().toJSON(),height:innerHeight}));assert(waterLayout.tree.top>=0&&waterLayout.button.bottom<=waterLayout.height);await page.screenshot({path:output+'/mobile-ready-water.png'});check('Reading returns to complete tree and watering button together');
 await click('#primary-action');await page.$eval('#primary-action',n=>n.click());assert(await page.$eval('#primary-action',n=>n.disabled));await new Promise(resolve=>setTimeout(resolve,1000));assert(await page.$('.watering-can'));await page.screenshot({path:output+'/mobile-watering.png'});await page.waitForFunction(()=>document.querySelector('#devotional-invite').hidden===false);assert.equal(await page.$eval('#growth-count',n=>n.textContent),'7 / 7 天');assert.equal(await page.$$eval('.flower-reveal',n=>n.length),6);await new Promise(resolve=>setTimeout(resolve,1800));await page.screenshot({path:output+'/mobile-watered.png'});check('Watering animates, ignores repeat clicks, reveals flowers and invites devotional only after completion');
 await click('#open-devotional');assert.equal(await page.$eval('#devotional-invite',n=>n.hidden),true);await page.type('#preview-journal','測試亮光，只保留這次預覽。');await click('#return-garden');await click('#primary-action');assert.equal(await page.$eval('#preview-journal',n=>n.value),'測試亮光，只保留這次預覽。');await page.keyboard.press('Escape');assert.equal(await page.$eval('#garden-dialog',n=>n.open),false);check('Devotional has one journal; closing retains draft in memory and Escape restores garden');
 await click('#makeup-button');assert.equal(await page.$$eval('.preview-calendar>*',n=>n.length),4);await click('[data-makeup="10/9"]');await click('#finish-reading');assert.match(await page.$eval('#primary-action small',n=>n.textContent),/10\/9/);await click('#primary-action');await page.waitForFunction(()=>!document.querySelector('#primary-action').disabled);await click('#makeup-button');assert.equal(await page.$eval('[data-makeup="10/9"]',n=>n.disabled),true);await page.keyboard.press('Escape');assert.equal(await page.$eval('#growth-count',n=>n.textContent),'7 / 7 天');check('Makeup keeps selected date, marks only that date complete and does not overcount milestone');
 for(const type of ['typhoon','worm','wind','trouble']){
   await page.$eval('.preview-controls',n=>n.open=true);await click(`[data-challenge="${type}"]`);assert.equal(await page.$eval('#garden-scene',n=>n.dataset.weather),type);await page.$eval('.garden-world',n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.screenshot({path:output+`/mobile-${type}.png`});const before=Number((await page.$eval('#stars-count',n=>n.textContent)).match(/\d+/)[0]);await click('#care-tool');await page.$eval('#care-tool',n=>n.click());await page.waitForFunction(()=>document.querySelector('#care-tools').hidden);assert.equal(Number((await page.$eval('#stars-count',n=>n.textContent)).match(/\d+/)[0]),before+1);assert.equal(await page.$eval('#garden-scene',n=>n.dataset.weather),'clear');check(`Contextual ${type} tool animates, restores scene and adds exactly one star`);
 }
 for(const id of ['growth-button','companions-button','collection-button','help-button']){await click('#'+id);assert(await page.$eval('#garden-dialog',n=>n.open));assert.equal(await overflow(),false);await page.keyboard.press('Escape');check(`${id} opens and closes with keyboard, without page overflow`);}
 await click('#help-button');assert.equal(await page.$eval('#guide-sound',n=>n.checked),true);await page.$eval('#guide-sound',n=>n.checked=false);await click('#start-garden');assert.equal(await page.$eval('#sound-button',n=>n.getAttribute('aria-pressed')),'false');check('Guide has checked sound default and honors opting out');
 await page.evaluate(()=>{window.__originalPlay=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=()=>Promise.reject(new DOMException('Simulated autoplay denial','NotAllowedError'));});await click('#sound-button');await page.waitForFunction(()=>document.querySelector('#audio-status').textContent.includes('重試'));assert.equal(await page.$eval('#sound-button',n=>n.getAttribute('aria-pressed')),'false');await page.evaluate(()=>HTMLMediaElement.prototype.play=window.__originalPlay);await click('#sound-button');await page.waitForFunction(()=>document.querySelector('#sound-button').getAttribute('aria-pressed')==='true');await click('#sound-button');check('Audio denial gives retry, trusted retry plays and speaker can mute');
 await page.$eval('.preview-controls',n=>n.open=true);await click('#reset-button');assert.equal(await page.$eval('#growth-count',n=>n.textContent),'6 / 7 天');assert.equal(await page.$eval('#stars-count',n=>n.textContent),'已收藏 3 枚');assert.equal(await page.$eval('#devotional-invite',n=>n.hidden),true);check('Reset clears demonstration progress and rewards');
 await click('#primary-action');await click('#finish-reading');await click('#primary-action');await page.$eval('#reset-button',n=>n.click());await new Promise(resolve=>setTimeout(resolve,3100));assert.equal(await page.$eval('#growth-count',n=>n.textContent),'6 / 7 天');assert.equal(await page.$eval('#primary-action',n=>n.disabled),false);assert.equal(await page.$eval('#devotional-invite',n=>n.hidden),true);check('Reset during animation cancels pending reward and restores actionable state');
 await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await click('#primary-action');await click('#finish-reading');await click('#primary-action');await page.waitForFunction(()=>!document.querySelector('#primary-action').disabled);assert.equal(await page.$eval('.tree-crown',n=>getComputedStyle(n).animationName),'none');check('Reduced motion completes actions with static scene');
 await open();await click('#primary-action');await click('#finish-reading');await page.goto(base+'/life-tree-garden-preview.html',{waitUntil:'networkidle0'});assert.match(await page.$eval('#primary-action',n=>n.textContent),/打開今日讀經/);assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage)),[]);check('Reload discards prototype progress and never writes browser storage');
 const small=await page.$$eval('button',nodes=>nodes.filter(n=>!n.hidden&&n.getClientRects().length&&!n.disabled).map(n=>({id:n.id,width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})).filter(n=>n.width<44||n.height<44));assert.deepEqual(small,[]);check('Visible enabled button hit targets are at least 44×44px');
 for(const [width,height] of [[320,568],[402,600]]){await open(width,height);await click('#primary-action');await click('#finish-reading');await new Promise(resolve=>setTimeout(resolve,700));const layout=await page.evaluate(()=>({top:document.querySelector('#garden-scene').getBoundingClientRect().top,bottom:document.querySelector('#primary-action').getBoundingClientRect().bottom,height:innerHeight}));assert(layout.top>=0&&layout.bottom<=layout.height,JSON.stringify(layout));check(`Short viewport shows complete tree and watering action: ${width}×${height}`);}
 await open();await click('#primary-action');await click('#finish-reading');await click('#makeup-button');await click('[data-makeup="10/9"]');await click('#finish-reading');await click('#primary-action');await page.waitForFunction(()=>!document.querySelector('#primary-action').disabled);assert.match(await page.$eval('#primary-action small',n=>n.textContent),/今日讀經已完成/);assert.equal(await page.$eval('#primary-action',n=>n.parentElement.id),'world-action-slot');assert.equal(await page.$eval('#devotional-invite',n=>n.hidden),true);check('Finishing makeup preserves previously read but unwatered today and resumes its watering action');
 assert.deepEqual(external,[]);assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);check('No external API/auth/database requests, browser errors or missing resources');
}catch(error){failed=true;console.error(error);checks.push({name:'Run failure',passed:false,error:error.stack});}finally{await browser?.close();server.close();fs.writeFileSync(output+'/results.json',JSON.stringify({checks,errors,external,missing,passed:!failed},null,2));}
if(failed)process.exitCode=1;
