import assert from 'node:assert/strict';
globalThis.window={};
const {FUNCTION_CATALOG,FUNCTION_GROUPS,availableFunctionKeys,favoriteKeys}=await import('../app-function-catalog.mjs');
const {canOpen}=await import('../admin-access.mjs?v=20261009-app-audit2');
const permissions=['members','attendance','groups','schedules','private_prayers','pastoral_chats','spaces','newcomer_care','tree_reading_admin','binding_review','notification_settings','website_weekly','website_group_resources','inventory','heat_camp'];
const full={grants:permissions.map(permission=>({church_id:'M+',permission})),featurePermissions:[]};
const home={is_owner:true,system_monitor_access:true,home_modules:Object.keys(FUNCTION_CATALOG)};
const all=availableFunctionKeys(full,'M+',home),grouped=FUNCTION_GROUPS.flatMap(g=>g.keys);
assert.equal(new Set(grouped).size,grouped.length);assert.deepEqual(new Set(grouped),new Set(Object.keys(FUNCTION_CATALOG)));assert.equal(all.length,Object.keys(FUNCTION_CATALOG).length);
assert(canOpen(full,'M+','private_prayers'));assert(canOpen(full,'M+','pastoral_chats'));
const leader={grants:[{church_id:'M+',permission:'schedules'}],featurePermissions:[]};
assert.deepEqual(new Set(availableFunctionKeys(leader,'M+',{})),new Set(['schedules','service_signups']));
assert.equal(availableFunctionKeys(full,'SHiNE',home).includes('members'),false);
assert.equal(availableFunctionKeys(full,'M+',{}).includes('school_students'),false);
assert.equal(availableFunctionKeys(full,'M+',{}).includes('admin_accounts'),false);
assert.equal(availableFunctionKeys({...full,featurePermissions:[{church_id:'M+',feature_key:'members',view:false}]},'M+',home).includes('members'),false);
assert.equal(availableFunctionKeys(full,'M+',home,{feature_modules:[{key:'members',enabled:false}]}).includes('members'),false);
const shine={...full,grants:permissions.map(permission=>({church_id:'SHiNE',permission}))};
const shineKeys=availableFunctionKeys(shine,'SHiNE',home);
assert(shineKeys.includes('members'));assert(!shineKeys.includes('service_signups'));assert(!shineKeys.includes('heat_camp'));assert(!shineKeys.includes('subtitle_library'));
const saved=favoriteKeys(['members','school_students','members'],[],all);assert.deepEqual(saved,['members','school_students']);
assert.equal(favoriteKeys([],['members'],all).length,0);
const removed=saved.filter(k=>k!=='school_students');assert(all.includes('school_students'));assert(!removed.includes('school_students'));assert(favoriteKeys([...removed,'school_students'],[],all).includes('school_students'));
console.log(JSON.stringify({checks:18,catalog:all.length,groups:FUNCTION_GROUPS.length,status:'passed'}));
