import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.102.0';

const APP='https://mscos.mchurch.online';
const MEDIA='https://aqanuwilmvdtlzuqlrau.supabase.co/storage/v1/object/public/church-website-public-media/';
const INITIAL='d066ac92-9801-46cc-9293-2932399b4e11';
const UUID=/^[0-9a-f-]{36}$/i;
const headers=(origin:string)=>({...(origin===APP?{'access-control-allow-origin':origin}:{}),'access-control-allow-headers':'authorization,content-type,apikey','access-control-allow-methods':'POST,OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'no-store','vary':'Origin'});
const json=(origin:string,status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers:headers(origin)});

function client(){
 const url=Deno.env.get('SUPABASE_URL')||'',key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY')||'';
 if(!url||!key)throw new Error('config');
 return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
}
async function staffForUser(db:any,userId:string){const r=await db.from('pastoral_staff').select('id,display_name,role').eq('app_user_id',userId).eq('is_active',true).maybeSingle();return r.data||null;}
async function finalReviewerIds(db:any){const r=await db.rpc('get_weekly_bulletin_reviewers',{p_church:'M+'});return (Array.isArray(r.data)?r.data:[]).map((x:any)=>String(x.id)).filter((id:string)=>id!==INITIAL);}
async function publicationForDraft(db:any,draftId:string){const r=await db.from('sermon_social_publication_jobs').select('status,instagram_media_id,published_at,error_code').eq('draft_id',draftId).maybeSingle();return r.data||null;}
function cleaned(body:any){const array=(value:any)=>Array.isArray(value)?value.map(x=>String(x).trim()).filter(Boolean).slice(0,12):[];return {speaker:String(body.speaker||'').trim().slice(0,100),scripture:String(body.scripture||'').trim().slice(0,300),sermon_start_seconds:Number(body.start)||null,sermon_end_seconds:Number(body.end)||null,outline:array(body.outline),key_points:array(body.keyPoints),applications:array(body.applications),caption:String(body.caption||'').trim().slice(0,2200),social_image_url:String(body.socialImageUrl||'').trim()||null,updated_at:new Date().toISOString()};}
async function subtitleState(db:any,draftId:string){const r=await db.from('sermon_subtitle_segments').select('segment_index,cues,reviewed_cues,review_status,review_error').eq('draft_id',draftId).order('segment_index');if(r.error)throw r.error;const rows=r.data||[];return {rows,ready:rows.length>0&&rows.every((x:any)=>x.review_status==='completed'),cues:rows.flatMap((x:any)=>x.review_status==='completed'&&Array.isArray(x.reviewed_cues)?x.reviewed_cues:Array.isArray(x.cues)?x.cues:[])};}
async function queueNotification(db:any,input:{draftId:string;staffId:string;stage:string;sourceKey:string;title:string;body:string;url:string}){const q=await db.from('sermon_social_notification_queue').upsert({draft_id:input.draftId,staff_id:input.staffId,stage:input.stage,source_key:input.sourceKey,title:input.title,body:input.body,target_url:input.url,deliver_after:new Date(Date.now()+180000).toISOString(),status:'pending',attempt_count:0,error_code:null,sent_at:null,updated_at:new Date().toISOString()},{onConflict:'source_key'});if(q.error)throw new Error('notification_queue_failed');}
async function queueYoutubeReview(db:any,draft:any,reviewers:string[]){const url='/sermon-social-review.html?draft='+draft.id+'#youtube';for(const id of reviewers){const key='sermon-youtube-review:'+draft.id+':'+id,task=await db.from('pastoral_tasks').upsert({entity_key:'mplus',title:'確認上稿 '+draft.service_date+' YouTube 字幕',description:'影片剪輯範圍與字幕校對都已完成，請確認後獨立上稿 YouTube 繁體中文字幕。',task_type:'document',status:'pending',assigned_to:id,idempotency_key:key,payload:{workflow:'sermon_youtube_caption_review',draft_id:draft.id,action_url:url}},{onConflict:'idempotency_key'});if(task.error)throw task.error;await queueNotification(db,{draftId:draft.id,staffId:id,stage:'youtube_caption_review',sourceKey:key,title:'YouTube 字幕等待確認',body:draft.service_date+'｜'+draft.sermon_title,url});}}
async function youtubeAction(req:Request,draftId:string,action:string,timeout=30000){const response=await fetch((Deno.env.get('SUPABASE_URL')||'')+'/functions/v1/youtube-oauth',{method:'POST',headers:{authorization:req.headers.get('authorization')||'','content-type':'application/json',origin:APP},body:JSON.stringify({action,church:'M+',draftId}),signal:AbortSignal.timeout(timeout)}),data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(String(data.error||action+'_failed'));return data;}
function validArtwork(options:any){if(!Array.isArray(options)||options.length!==3)return false;const values=options.map(String);return values.filter(x=>x.includes('/card-knees-up')).length===2&&values.filter(x=>x.includes('/card-half-body')).length===1;}

Deno.serve(async req=>{
 const origin=req.headers.get('origin')||'';
 if(req.method==='OPTIONS')return origin===APP?new Response('ok',{headers:headers(origin)}):json(origin,403,{ok:false,error:'forbidden'});
 if(req.method!=='POST'||origin!==APP)return json(origin,403,{ok:false,error:'forbidden'});
 const db=client(),token=(req.headers.get('authorization')||'').match(/^Bearer (.+)$/i)?.[1],user=token?(await db.auth.getUser(token)).data.user:null;
 if(!user)return json(origin,401,{ok:false,error:'請重新登入。'});
 const body=await req.json().catch(()=>null);
 if(!body||!UUID.test(body.draftId||''))return json(origin,400,{ok:false,error:'審核連結不正確。'});
 const staff=await staffForUser(db,user.id);
 if(!staff)return json(origin,403,{ok:false,error:'沒有審核權限。'});
 const draftResult=await db.from('sermon_social_drafts').select('id,church_id,service_date,youtube_url,sermon_title,speaker,scripture,sermon_start_seconds,sermon_end_seconds,outline,key_points,applications,caption,source_image_path,social_image_url,social_image_options,status,review_stage,initial_reviewer_id,initial_review_comment,updated_at').eq('id',body.draftId).eq('church_id','M+').maybeSingle(),draft=draftResult.data;
 if(!draft)return json(origin,404,{ok:false,error:'找不到審核內容。'});
 const finals=await finalReviewerIds(db),isFinal=finals.includes(staff.id),initial=draft.review_stage==='initial_review';
 if(!isFinal&&staff.id!==INITIAL)return json(origin,403,{ok:false,error:'這份內容目前不是由您審核。'});

 if(body.action==='get'){
  const subtitles=await subtitleState(db,draft.id);let workflow=(await db.from('sermon_youtube_workflows').select('*').eq('draft_id',draft.id).maybeSingle()).data;
  if(!workflow){const inserted=await db.from('sermon_youtube_workflows').insert({draft_id:draft.id,status:subtitles.ready?'waiting_edit':'proofreading'}).select('*').single();workflow=inserted.data||null;}
  const sourceImage=draft.source_image_path?MEDIA+draft.source_image_path.split('/').map(encodeURIComponent).join('/'):null;
  return json(origin,200,{ok:true,draft:{...draft,source_image_url:sourceImage,subtitle_cues:subtitles.cues,subtitles_ready:subtitles.ready,subtitle_segments:subtitles.rows.map((x:any)=>({segment_index:x.segment_index,review_status:x.review_status,review_error:x.review_error,cue_count:Array.isArray(x.reviewed_cues)&&x.reviewed_cues.length?x.reviewed_cues.length:Array.isArray(x.cues)?x.cues.length:0}))},publication:await publicationForDraft(db,draft.id),youtube_workflow:workflow,is_final_reviewer:isFinal});
 }
 if(body.action==='save'){const saved=await db.from('sermon_social_drafts').update(cleaned(body)).eq('id',draft.id).select('*').single();return saved.error?json(origin,503,{ok:false,error:'修改未儲存。'}):json(origin,200,{ok:true,draft:saved.data});}
 if(body.action==='confirm_youtube_edit'){
  if(!isFinal)return json(origin,403,{ok:false,error:'只有牧師或師母可以確認 YouTube 影片範圍。'});
  const mode=String(body.editMode||'');if(!['full_replay','trimmed_replay'].includes(mode))return json(origin,400,{ok:false,error:'請選擇影片保留方式。'});
  const offset=mode==='trimmed_replay'?Math.max(0,Number(body.captionOffsetSeconds)||Number(draft.sermon_start_seconds)||0):0,subtitles=await subtitleState(db,draft.id),now=new Date().toISOString(),status=subtitles.ready?'review_ready':'proofreading';
  const saved=await db.from('sermon_youtube_workflows').upsert({draft_id:draft.id,status,edit_mode:mode,caption_offset_seconds:offset,edit_confirmed_at:now,review_requested_at:subtitles.ready?now:null,error_code:null,updated_at:now},{onConflict:'draft_id'}).select('*').single();
  if(saved.error)return json(origin,503,{ok:false,error:'YouTube 剪輯狀態未儲存。'});if(subtitles.ready)await queueYoutubeReview(db,draft,finals);return json(origin,200,{ok:true,status,youtube_workflow:saved.data});
 }
 if(body.action==='approve_youtube'){
  if(!isFinal)return json(origin,403,{ok:false,error:'只有牧師或師母可以上稿 YouTube 字幕。'});const subtitles=await subtitleState(db,draft.id);if(!subtitles.ready)return json(origin,409,{ok:false,error:'字幕校對尚未完成。'});
  const workflow=(await db.from('sermon_youtube_workflows').select('*').eq('draft_id',draft.id).maybeSingle()).data;if(!workflow?.edit_confirmed_at)return json(origin,409,{ok:false,error:'請先確認 YouTube 影片是否已剪除講道前內容。'});if(!['review_ready','failed','approved'].includes(workflow.status))return json(origin,409,{ok:false,error:'YouTube 字幕目前不能上稿。'});
  const now=new Date().toISOString();await db.from('sermon_youtube_workflows').update({status:'approved',reviewed_by:staff.id,reviewed_at:now,error_code:null,updated_at:now}).eq('draft_id',draft.id);
  try{const metadata=await youtubeAction(req,draft.id,'update_sermon_metadata'),captions=await youtubeAction(req,draft.id,'publish_subtitles',60000);await db.from('sermon_youtube_workflows').update({status:'published',published_at:new Date().toISOString(),error_code:null,updated_at:new Date().toISOString()}).eq('draft_id',draft.id);await db.from('pastoral_tasks').update({status:'completed',completed_at:now,updated_at:now}).eq('status','pending').contains('payload',{workflow:'sermon_youtube_caption_review',draft_id:draft.id});return json(origin,200,{ok:true,status:'youtube_published',youtube:{metadata,captions}});}catch(error){const message=error instanceof Error?error.message:'youtube_publish_failed';await db.from('sermon_youtube_workflows').update({status:'failed',error_code:message.slice(0,500),updated_at:new Date().toISOString()}).eq('draft_id',draft.id);return json(origin,503,{ok:false,error:'YouTube 字幕上稿失敗，已保留目前字幕，可稍後重試。'});}
 }
 if(body.action==='reject'){const comment=String(body.comment||'').trim().slice(0,2000);if(!comment)return json(origin,400,{ok:false,error:'退回時請填寫意見。'});await db.from('sermon_social_drafts').update({...cleaned(body),status:'changes_requested',initial_review_comment:initial?comment:draft.initial_review_comment,final_review_comment:initial?null:comment}).eq('id',draft.id);const workflow=initial?'sermon_social_initial_review':'sermon_social_final_review';await db.from('pastoral_tasks').update({status:'completed',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('status','pending').contains('payload',{workflow,draft_id:draft.id});return json(origin,200,{ok:true,status:'changes_requested'});}
 if(body.action==='approve'){
  const existing=await publicationForDraft(db,draft.id);if(existing?.status==='published'&&existing.instagram_media_id)return json(origin,409,{ok:false,error:'already_published'});const now=new Date().toISOString();
  if(initial){const selected=String(body.socialImageUrl||'').trim(),options=Array.isArray(draft.social_image_options)?draft.social_image_options:[];if(!validArtwork(options))return json(origin,409,{ok:false,error:'請先完成兩張膝蓋以上、一張半身的 1080p M+ 主日信息圖卡。'});if(!selected||!options.includes(selected))return json(origin,400,{ok:false,error:'請先選擇一張講道講員圖，才能送牧師、師母確認。'});await db.from('sermon_social_drafts').update({...cleaned(body),status:'pending_review',review_stage:'pastoral_confirmation',initial_reviewed_at:now,initial_reviewer_id:staff.id,initial_review_comment:String(body.comment||'').trim().slice(0,2000)||null}).eq('id',draft.id);await db.from('pastoral_tasks').update({status:'completed',completed_at:now,updated_at:now}).eq('status','pending').contains('payload',{workflow:'sermon_social_initial_review',draft_id:draft.id});for(const id of finals){const key='sermon-social-final:'+draft.id+':'+id,url='/sermon-social-review.html?draft='+draft.id;await db.from('pastoral_tasks').upsert({entity_key:'mplus',title:'確認發出 '+draft.service_date+' 講道 IG',description:(staff.display_name||'初審同工')+'已完成初審，請確認圖片與貼文後發佈 Instagram。YouTube 字幕會在影片可編輯及校對完成後另行確認。',task_type:'document',status:'pending',assigned_to:id,idempotency_key:key,payload:{workflow:'sermon_social_final_review',draft_id:draft.id,review_stage:'pastoral_confirmation',action_url:url}},{onConflict:'idempotency_key'});await queueNotification(db,{draftId:draft.id,staffId:id,stage:'pastoral_confirmation',sourceKey:key,title:'講道 IG 內容等待確認',body:draft.service_date+'｜'+draft.sermon_title,url});}return json(origin,200,{ok:true,status:'pastoral_confirmation'});}
  if(!isFinal)return json(origin,403,{ok:false,error:'只有牧師或師母可以發佈 Instagram。'});const approval=await db.from('sermon_social_drafts').update({...cleaned(body),status:'approved',review_stage:'completed',final_reviewed_at:now,final_reviewer_id:staff.id,final_review_comment:String(body.comment||'').trim().slice(0,2000)||null}).eq('id',draft.id).eq('status','pending_review').eq('review_stage','pastoral_confirmation').select('id').maybeSingle();if(approval.error)return json(origin,503,{ok:false,error:'approval_failed'});if(!approval.data&&draft.status!=='approved')return json(origin,409,{ok:false,error:'conflict'});
  const setting=await db.from('media_publishing_settings').select('instagram_sermon_enabled').eq('church_id','M+').maybeSingle();if(setting.error)return json(origin,503,{ok:false,error:'內容已核准，但無法讀取發布設定。'});let instagram:any={status:'skipped',reason:'publishing_disabled'};if(setting.data?.instagram_sermon_enabled===true){const response=await fetch((Deno.env.get('SUPABASE_URL')||'')+'/functions/v1/instagram-publishing',{method:'POST',headers:{authorization:req.headers.get('authorization')||'','content-type':'application/json',origin:APP},body:JSON.stringify({action:'publish_sermon',church:'M+',draftId:draft.id}),signal:AbortSignal.timeout(60000)});instagram=await response.json().catch(()=>({}));if(!response.ok||!instagram.ok)return json(origin,503,{ok:false,error:'Instagram 發佈失敗，請稍後重試。'});}await db.from('pastoral_tasks').update({status:'completed',completed_at:now,updated_at:now}).eq('status','pending').contains('payload',{workflow:'sermon_social_final_review',draft_id:draft.id});return json(origin,200,{ok:true,status:'approved',instagram});
 }
 return json(origin,400,{ok:false,error:'不支援的操作。'});
});
