import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../../church-os-sw.js',import.meta.url),'utf8'),checks=[];
function harness(){
 const handlers={},stores=new Map(),log={fetch:[],put:[],deleted:[],skip:0,claim:0,navigate:[],focus:0,open:[],notifications:[]};let network=async()=>new Response('network');
 const key=request=>typeof request==='string'?request:request.url;
 const cache=name=>{if(!stores.has(name))stores.set(name,new Map());const store=stores.get(name);return{addAll:async files=>{log.shell=files;for(const file of files)store.set(file,new Response(file==='/app-offline.html'?'offline-page':'asset'));},put:async(request,response)=>{log.put.push(key(request));if(log.quota)throw new Error('quota');store.set(key(request),response.clone());},match:async request=>store.get(key(request))?.clone()};};
 const self={location:{origin:'https://app.example.invalid'},addEventListener:(type,handler)=>handlers[type]=handler,skipWaiting:async()=>log.skip++,clients:{claim:async()=>log.claim++,matchAll:async()=>log.windows||[],openWindow:async target=>log.open.push(target)},registration:{showNotification:async(title,payload)=>log.notifications.push({title,payload})}};
 const caches={open:async name=>cache(name),keys:async()=>[...stores.keys()],delete:async name=>{log.deleted.push(name);return stores.delete(name);},match:async request=>{for(const name of stores.keys()){const result=await cache(name).match(request);if(result)return result;}}};
 class Request{constructor(request,options){Object.assign(this,request,options);}}
 vm.runInNewContext(source,{self,caches,Request,Response,URL,fetch:async request=>{log.fetch.push(request);return network(request);}});
 async function event(type,extra={}){const pending=[],e={...extra,waitUntil:value=>pending.push(Promise.resolve(value)),respondWith:value=>e.response=Promise.resolve(value)};handlers[type](e);const response=await e.response;await Promise.all(pending);return{e,response};}
 const request=(path,options={})=>({url:'https://app.example.invalid'+path,method:'GET',mode:'cors',destination:'',...options});
 return{self,stores,log,cache,event,request,network(fn){network=fn;}};
}
async function test(name,fn){await fn();checks.push({name,status:'passed'});console.log('PASS',name);}
const h=harness();await h.event('install');
await test('install precaches recovery and shared runtime without forcing activation',()=>{assert(h.log.shell.includes('/app-offline.html'));assert(h.log.shell.some(path=>path.includes('app-runtime.mjs')));assert.equal(h.log.skip,0);});
await test('unknown message cannot activate an update',async()=>{await h.event('message',{data:{type:'other'}});assert.equal(h.log.skip,0);});
await test('explicit update message activates once',async()=>{await h.event('message',{data:{type:'CHURCH_ACTIVATE_UPDATE'}});assert.equal(h.log.skip,1);});
await test('activation removes only previous church cache namespaces',async()=>{h.stores.set('church-os-shell-old',new Map());h.stores.set('unrelated-cache',new Map());await h.event('activate');assert.deepEqual(h.log.deleted,['church-os-shell-old']);assert.equal(h.log.claim,1);assert(h.stores.has('unrelated-cache'));});
await test('successful authenticated and callback navigations never enter cache',async()=>{const before=h.log.put.length;for(const path of ['/admin-dashboard.html?church=M%2B','/admin-line-callback.html?code=synthetic','/app-auth-handoff.html?handoff=synthetic']){const result=await h.event('fetch',{request:h.request(path,{mode:'navigate'})});assert.equal(await result.response.text(),'network');assert.equal(h.log.fetch.at(-1).cache,'no-store');}assert.equal(h.log.put.length,before);});
await test('offline navigation shows recovery instead of a login screen',async()=>{h.network(async()=>{throw new Error('offline');});const {response}=await h.event('fetch',{request:h.request('/service-signup-admin.html?church=M%2B',{mode:'navigate'})});assert.equal(await response.text(),'offline-page');});
await test('server unavailable navigation uses recovery',async()=>{h.network(async()=>new Response('down',{status:503}));assert.equal(await(await h.event('fetch',{request:h.request('/members.html',{mode:'navigate'})})).response.text(),'offline-page');});
await test('not found navigation keeps actual response',async()=>{h.network(async()=>new Response('not found',{status:404}));assert.equal((await h.event('fetch',{request:h.request('/missing.html',{mode:'navigate'})})).response.status,404);});
await test('recovery cache missing still returns a readable response',async()=>{const isolated=harness();isolated.network(async()=>{throw new Error('offline');});const {response}=await isolated.event('fetch',{request:isolated.request('/members.html',{mode:'navigate'})});assert.equal(response.status,503);assert.match(await response.text(),/重新整理/);});
await test('POST and external API requests are never handled or queued',async()=>{for(const request of [h.request('/functions',{method:'POST'}),{...h.request('/auth'),url:'https://backend.supabase.co/auth/v1/user'}])assert.equal((await h.event('fetch',{request})).response,undefined);});
await test('same-origin API data is not cached',async()=>assert.equal((await h.event('fetch',{request:h.request('/api/private')})).response,undefined));
await test('scripts revalidate browser cache and remember fresh assets',async()=>{h.network(async()=>new Response('fresh'));const req=h.request('/app-runtime.mjs?v=4',{destination:'script'});assert.equal(await(await h.event('fetch',{request:req})).response.text(),'fresh');assert.equal(h.log.fetch.at(-1).cache,'no-cache');assert(h.log.put.includes(req.url));});
await test('network failure serves previously fetched script',async()=>{h.network(async()=>{throw new Error('offline');});const req=h.request('/app-runtime.mjs?v=4',{destination:'script'});assert.equal(await(await h.event('fetch',{request:req})).response.text(),'fresh');});
await test('server failure serves cached script without replacing it',async()=>{h.network(async()=>new Response('down',{status:503}));const req=h.request('/app-runtime.mjs?v=4',{destination:'script'});assert.equal(await(await h.event('fetch',{request:req})).response.text(),'fresh');});
await test('missing offline script returns an error response',async()=>{h.network(async()=>{throw new Error('offline');});const {response}=await h.event('fetch',{request:h.request('/uncached.mjs',{destination:'script'})});assert.equal(response.type,'error');});
await test('cache quota failure does not break an online response',async()=>{h.log.quota=true;h.network(async()=>new Response('fresh'));const {response}=await h.event('fetch',{request:h.request('/new.mjs',{destination:'script'})});assert.equal(await response.text(),'fresh');h.log.quota=false;});
await test('only public asset images use image cache',async()=>{assert.equal((await h.event('fetch',{request:h.request('/private-photo.jpg',{destination:'image'})})).response,undefined);h.network(async()=>new Response('image'));const req=h.request('/assets/icon.png',{destination:'image'});assert.equal(await(await h.event('fetch',{request:req})).response.text(),'image');h.network(async()=>{throw new Error('offline');});assert.equal(await(await h.event('fetch',{request:req})).response.text(),'image');});
await test('notification waits for navigation before focusing a window',async()=>{let finished=false;h.log.windows=[{navigate:async target=>{await Promise.resolve();h.log.navigate.push(target);finished=true;},focus:async()=>{assert(finished);h.log.focus++;}}];await h.event('notificationclick',{notification:{close(){},data:{url:'/members.html?church=M%2B'}}});assert.equal(h.log.navigate.at(-1),'https://app.example.invalid/members.html?church=M%2B');assert.equal(h.log.focus,1);});
await test('notification external destination falls back to home',async()=>{await h.event('notificationclick',{notification:{close(){},data:{url:'https://external.invalid'}}});assert.equal(h.log.navigate.at(-1),'/admin-dashboard.html');});
await test('closed notification window opens a replacement',async()=>{h.log.windows=[{navigate:async()=>{throw new Error('closed');},focus(){}}];await h.event('notificationclick',{notification:{close(){},data:{url:'/members.html'}}});assert.equal(h.log.open.at(-1),'https://app.example.invalid/members.html');});
await test('push payload retains existing notification contract',async()=>{await h.event('push',{data:{json:()=>({title:'測試通知',body:'隔離內容',url:'/members.html'})}});assert.equal(h.log.notifications[0].payload.data.url,'/members.html');});
fs.mkdirSync(new URL('./results/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('./results/worker.json',import.meta.url),JSON.stringify({isolated:true,checks,total:checks.length},null,2));console.log('TOTAL',checks.length);
