const {default:puppeteer}=await import(process.env.PUPPETEER_MODULE||'puppeteer-core');
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {contrastMetrics} from './contrast.mjs';
import {uid,user,session,permissions,daily,weekly,service} from './fixtures.mjs';
const base=process.env.CHURCH_TEST_ORIGIN||'http://127.0.0.1:8769',out=new URL('./results/',import.meta.url).pathname;
fs.mkdirSync(out,{recursive:true});
let items=daily(),bulletins=weekly(),services=service(),writes=[],requests=[],mode='owner',stage='initial',failWrite=false,failRead=false,afterWriteFail=false,delayWrite=0,delayId='',delaySchedule='',alerts=[],changes=[],afterWriteAction='',abortWrite=false,malformedWrite=false;
const errors=[],checks=[];let passed=false;
const browser=await puppeteer.launch({executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-sync'],userDataDir:out+'chrome'});
const page=await browser.newPage();await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await page.setBypassServiceWorker(true);
await page.evaluateOnNewDocument(session=>{localStorage.setItem('church-staging-admin-v1',JSON.stringify(session));window.sharedStyleRemovals=0;new MutationObserver(records=>{for(const record of records)for(const node of record.removedNodes)if(node.nodeType===1&&node.matches?.('link[data-app-consistency]'))window.sharedStyleRemovals++;}).observe(document,{childList:true,subtree:true});},session);
page.on('pageerror',error=>errors.push(error.message));let answers=[];page.on('dialog',async dialog=>{if(dialog.type()==='beforeunload'){await dialog.accept();return;}if(dialog.type()==='alert'){alerts.push(dialog.message());await dialog.accept();return;}const answer=answers.shift();if(answer===undefined){errors.push('Unexpected dialog: '+dialog.message());await dialog.dismiss();return;}if(answer)await dialog.accept();else await dialog.dismiss();});
await page.setRequestInterception(true);
page.on('request',async req=>{
 const url=new URL(req.url());if(url.hostname.endsWith('supabase.co')){
  let body={};try{body=JSON.parse(req.postData()||'{}');}catch{}requests.push({path:url.pathname,method:req.method(),body});let data=[],code=200;
  const write=async()=>{writes.push({path:url.pathname,method:req.method(),body,url:url.href});if(delayWrite)await new Promise(resolve=>setTimeout(resolve,delayWrite));if(failWrite){code=503;data={error:'unavailable',message:'fixture unavailable'};return false;}if(afterWriteFail&&(!afterWriteAction||body.action===afterWriteAction))failRead=true;return true;};
  if(abortWrite&&req.method()!=='OPTIONS'&&((url.pathname.includes('/functions/')&&!['content_list','list','get'].includes(body.action))||url.pathname.endsWith('/website_weekly_bulletins')&&['POST','PATCH'].includes(req.method())||url.pathname.includes('/rpc/update_service'))){writes.push({path:url.pathname,body});await req.abort('failed');return;}
  if(malformedWrite&&req.method()!=='OPTIONS'&&url.pathname.includes('/functions/')&&!['content_list','list','get'].includes(body.action)){writes.push({path:url.pathname,body});await req.respond({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:'{}'});return;}
  if(req.method()==='OPTIONS')data={};
  else if(url.pathname==='/auth/v1/user')data=user;
  else if(url.pathname==='/auth/v1/token')data=session;
  else if(url.pathname.includes('/rpc/')){
   const name=url.pathname.split('/').pop();
   if(name==='get_my_church_access')data=(mode==='denied'?[]:permissions).map(permission=>({church_id:'M+',permission}));
   else if(name==='get_my_admin_profile')data=[{display_name:'測試同工',job_title:'行政同工'}];
   else if(name==='get_my_feature_permissions')data=permissions.map(feature_key=>({church_id:'M+',feature_key,view:true,create:mode!=='readonly',edit:mode!=='readonly',delete:mode!=='readonly',approve:mode!=='readonly',manage:mode!=='readonly',export:true}));
   else if(name==='get_my_app_capabilities')data={is_owner:mode==='owner',has_line:true};
   else if(name==='get_my_home_preferences')data={home_modules:[]};
   else if(name==='get_my_system_monitor_access')data=mode==='owner';
   else if(name==='get_service_signup_scopes')data=[];
   else if(name==='get_service_signup_admin'){if(failRead||mode==='denied'){code=503;data={message:mode==='denied'?'forbidden':'unavailable'};}else data=services;}
   else if(name==='get_service_signup_change_requests')data={requests:changes,is_final_reviewer:true};
   else if(name==='get_website_weekly_data'){if(body.p_service_date===delaySchedule)await new Promise(resolve=>setTimeout(resolve,550));data={schedule:{tech_sound:'排班 '+body.p_service_date},next_schedule:null,schedule_roles:[]};}
   else if(name==='update_service_signup_slot'){if(await write()){const slot=services.slots.find(row=>row.id===body.p_slot);slot.capacity=body.p_capacity;slot.is_open=body.p_open;data=true;}}
   else if(name==='update_service_signup_season'){if(await write()){services.seasons.find(row=>row.id===body.p_season).status=body.p_status;data=true;}}
   else if(name==='create_service_signup_quarter'){if(await write())data=true;}
   else if(name==='service_signup_apply_smart_match'){if(await write()){for(const slot of services.slots)for(const person of slot.registrations)if(body.p_registrations.includes(person.id))person.status='confirmed';data={applied:body.p_registrations.length,skipped:0};}}
   else if(name==='list_church_schedules')data=[];
  }
  else if(url.pathname.includes('/functions/v1/daily-devotional-admin')){
   if(body.action==='content_list'){if(failRead){code=503;data={ok:false,error:'unavailable'};}else{const records=body.from?.startsWith('2027-02')?Array.from({length:28},(_,n)=>({...daily()[0],id:'f'+n,devotional_date:`2027-02-${String(n+1).padStart(2,'0')}`,devotional_title:`二月測試 ${n+1}`})):items;data={ok:true,items:records.filter(row=>row.devotional_date>=body.from&&row.devotional_date<=body.to),reviewerStage:stage};}}
   else if(await write()){const row=items.find(item=>item.id===body.id);if(body.action==='content_update'){Object.assign(row,body.values);row.review_status='initial_review';}else row.review_status=body.toStatus;data={ok:true};}
  }
  else if(url.pathname.includes('/functions/v1/weekly-bulletin-review')){
   if(body.action==='list'){if(failRead){code=503;data={error:'unavailable'};}else data={ok:true,items:bulletins};}
   else if(body.action==='get'){const row=structuredClone(bulletins.find(row=>row.id===body.bulletinId));if(body.bulletinId===delayId)await new Promise(resolve=>setTimeout(resolve,550));data={ok:true,bulletin:row};}
   else if(await write()){const row=bulletins.find(row=>row.id===body.bulletinId);row.status=body.action==='approve'?'published':body.action==='request_changes'?'changes_requested':'pending_review';row.version++;data={ok:true,recipientCount:2};}
  }
  else if(url.pathname.includes('/functions/v1/service-signup-admin')){if(await write()){for(const slot of services.slots)for(const row of slot.registrations)if(row.id===body.registrationId)row.status=body.status;data={ok:true};if(body.action==='change_review'){changes=changes.filter(row=>row.id!==body.requestId);data.status=body.decision==='approve'?'admin_review':'rejected';}}}
  else if(url.pathname.endsWith('/website_weekly_bulletins')){
   if(['POST','PATCH'].includes(req.method())){if(await write()){const row=bulletins.find(row=>row.id===body.id);if(row)Object.assign(row,body);else bulletins.unshift(body);data={...body};}}
   else if(failRead){code=503;data={message:'fixture unavailable'};}else data=bulletins;
  }
  else if(url.pathname.endsWith('/church_customizations'))data={church_id:'M+',feature_modules:[],welcome_fields:[],catalogs:{},version:1};
  else if(url.pathname.endsWith('/church_public_settings'))data={church_id:'M+',brand_color:'#AD3C2A',logo_url:'',service_info:'每週主日聚會'};
  else if(url.pathname.endsWith('/service_schedules'))data=[];
  else if(url.pathname.endsWith('/instagram_reel_music'))data=[];
  else if(url.pathname.startsWith('/storage/v1/object/')&&req.method()==='POST'){if(await write())data={Key:'fixture',Id:'fixture'};}
  else if(url.pathname.startsWith('/storage/')){code=404;data={message:'fixture media unavailable'};}
  else if(url.pathname.includes('/functions/'))data={ok:true,items:[],settings:{},people:[]};
  await req.respond({status:code,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','access-control-allow-headers':'*','content-range':'0-0/1'},body:JSON.stringify(data)});return;
 }
 if(url.origin!==base&&url.protocol!=='data:'){await req.abort();return;}await req.continue();
});
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const text=selector=>page.$eval(selector,n=>n.textContent);
const value=selector=>page.$eval(selector,n=>n.value);
async function input(selector,value,event='input'){await page.$eval(selector,(n,{value,event})=>{n.value=value;n.dispatchEvent(new Event(event,{bubbles:true}));},{value,event});}
async function click(selector){await page.$eval(selector,async n=>{const animations=[];for(let parent=n;parent;parent=parent.parentElement)animations.push(...parent.getAnimations().filter(animation=>animation.effect.getComputedTiming().iterations!==Infinity));await Promise.all(animations.map(animation=>animation.finished.catch(()=>{})));n.scrollIntoView({block:'center',behavior:'instant'});});await pause(80);assert(await page.$eval(selector,n=>{const r=n.getBoundingClientRect();return n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),selector+' is covered');await page.click(selector);await pause(40);}
async function waitIdle(){await page.waitForFunction(()=>!document.querySelector('[aria-busy=true],#devotional-reload:disabled,#review-reload:disabled,#service-reload:disabled'));await pause(100);}
async function visit(file,{role='owner',reviewStage='initial',pending=false,fail=false}={}){items=daily();bulletins=weekly();services=service();mode=role;stage=reviewStage;failRead=fail;failWrite=false;afterWriteFail=false;delayWrite=0;delayId='';delaySchedule='';changes=[];afterWriteAction='';abortWrite=false;malformedWrite=false;writes=[];requests=[];answers=[];if(pending)bulletins.forEach(row=>{if(row.status==='draft')row.status='pending_review';});await page.goto(base+'/'+file+'?church=M%2B',{waitUntil:'networkidle0'});await waitIdle();}
async function test(name,fn){await fn();checks.push({name,status:'passed'});console.log('PASS',name);}
async function modalAccept(){await page.waitForSelector('.workflow-dialog[open]');await click('.workflow-dialog button[type=submit]');await waitIdle();}
try{
 await visit('daily-devotional-admin.html');
 await test('iOS setup preserves loaded shared stylesheet and header rules',async()=>{assert.equal(await page.evaluate(()=>window.sharedStyleRemovals),0);assert.equal(await page.$eval('.page-header',n=>n.getBoundingClientRect().height),164);});
 await test('devotional master detail shows workflow and one selected article',async()=>{assert.match(await text('#workflow'),/初審/);assert.equal(await page.$$eval('.devotional-choice',ns=>ns.length),3);assert.equal(await page.$$eval('.devotional-item',ns=>ns.length),1);assert.equal(await page.$eval('.devotional-choice',n=>getComputedStyle(n).backgroundImage),'none');});
 await test('devotional February month shows 28 dates with correct end date and no write',async()=>{await input('#devotional-month','2027-02','change');await waitIdle();assert.equal(await page.$$eval('.devotional-choice',ns=>ns.length),28);assert.match(await text('#devotional-month-title'),/2 月 · 28 篇/);assert.equal(requests.filter(r=>r.body.action==='content_list').at(-1).body.to,'2027-02-28');assert.equal(writes.length,0);});
 await test('devotional unimported month has clear empty state',async()=>{await input('#devotional-month','2027-03','change');await waitIdle();assert.equal(await page.$$eval('.devotional-choice',ns=>ns.length),0);assert.match(await text('#devotional-records'),/目前月份尚無/);assert.equal(await page.$('.devotional-item'),null);});
 await test('devotional month failure clears stale records and retries selected month',async()=>{failRead=true;await input('#devotional-month','2027-02','change');await waitIdle();assert.match(await text('#status'),/重新載入/);assert.equal(await page.$$eval('.devotional-choice',ns=>ns.length),0);assert.equal(await page.$eval('#devotional-month',n=>n.disabled),false);failRead=false;await click('#devotional-reload');await waitIdle();assert.equal(await page.$$eval('.devotional-choice',ns=>ns.length),28);await input('#devotional-month','2027-01','change');await waitIdle();assert.equal(await page.$$eval('.devotional-choice',ns=>ns.length),3);assert.equal(writes.length,0);});
 await test('devotional search and status filter do not write',async()=>{await input('#devotional-search','平安');assert.equal(await page.$$eval('.devotional-choice',ns=>ns.length),1);await input('#devotional-search','');await input('#devotional-filter','approved','change');assert.equal(await page.$$eval('.devotional-choice',ns=>ns.length),1);await input('#devotional-filter','','change');assert.equal(writes.length,0);});
 await click('[data-edit]');await input('[name=devotional_title]','保留我的修改');
 await test('devotional editing uses labeled groups and protects dirty switch',async()=>{assert.equal(await page.$$eval('.devotional-editor fieldset',ns=>ns.length),3);answers.push(false);await click('.devotional-choice[data-id=d2]');assert.equal(await value('[name=devotional_title]'),'保留我的修改');assert.equal(writes.length,0);});
 await test('devotional dirty month switch cancellation preserves editor and month',async()=>{const before=requests.length;answers.push(false);await input('#devotional-month','2027-02','change');assert.equal(await value('#devotional-month'),'2027-01');assert.equal(await value('[name=devotional_title]'),'保留我的修改');assert.equal(requests.length,before);});
 await test('unsaved devotional cannot be reviewed over edited values',async()=>{await click('[data-review=spouse_review]');assert.match(await text('#status'),/先儲存/);assert.equal(writes.length,0);});
 await test('failed devotional save keeps input and permits retry',async()=>{failWrite=true;await click('.devotional-editor button[type=submit]');await waitIdle();assert.equal(await value('[name=devotional_title]'),'保留我的修改');assert.equal(await page.$eval('.devotional-editor button[type=submit]',n=>n.disabled),false);});
 await test('rapid devotional save sends once and restores selected content',async()=>{failWrite=false;delayWrite=180;const before=writes.length;await page.$eval('.devotional-editor',form=>{form.requestSubmit();form.requestSubmit();});await waitIdle();assert.equal(writes.length,before+1);assert.match(await text('.devotional-head'),/保留我的修改/);assert.equal(await page.$('.devotional-editor'),null);});
 await click('[data-edit]');await input('[name=devotional_title]','已儲存待確認');
 await test('devotional saved but refresh failed locks writes until readonly reload',async()=>{afterWriteFail=true;await click('.devotional-editor button[type=submit]');await waitIdle();assert.match(await text('#status'),/操作已完成/);assert.equal(await page.$eval('[data-edit]',n=>n.disabled),true);const count=writes.length;failRead=false;afterWriteFail=false;await click('#devotional-reload');await waitIdle();assert.equal(writes.length,count);assert.match(await text('.devotional-head'),/已儲存待確認/);});
 await test('devotional return requires note and reviewer stage limits actions',async()=>{await click('[data-review=returned]');assert.match(await text('#status'),/退回原因/);const count=writes.length;await input('.review-note','請補充經文');await click('[data-review=returned]');await waitIdle();assert.equal(writes.length,count+1);await click('.devotional-choice[data-id=d2]');assert.equal(await page.$('[data-review]'),null);});
 await visit('daily-devotional-admin.html',{fail:true});await test('devotional initial load failure has retry',async()=>{assert.match(await text('#status'),/重新載入/);failRead=false;await click('#devotional-reload');await waitIdle();assert(await page.$('[data-edit]'),JSON.stringify({url:page.url(),status:await text('#status'),errors,requests:requests.slice(-8)}));});
 await visit('daily-devotional-admin.html',{role:'readonly'});await test('devotional view permission does not grant content edits or review',async()=>{assert.equal(await page.$eval('[data-edit]',n=>n.hidden),true);assert.equal(await page.$('[data-review]'),null);assert.equal(writes.length,0);});
 await visit('daily-devotional-admin.html',{reviewStage:'final'});items[0].review_status='final_review';await click('#devotional-reload');await waitIdle();await test('devotional final publication requires confirmation',async()=>{await click('[data-review=approved]');await page.waitForSelector('.workflow-dialog[open]');await page.keyboard.press('Escape');assert.equal(writes.length,0);await click('[data-review=approved]');await modalAccept();assert.equal(items[0].review_status,'approved');});
 await visit('weekly-bulletin-review.html',{pending:true});
 await test('weekly reviewer search and required return comment',async()=>{await input('#review-search','恩典');assert.equal(await page.$$eval('.review-choice',ns=>ns.length),1);await input('#review-search','');await click('#request-changes');assert.match(await text('#status'),/填寫退回/);assert.equal(writes.length,0);});
 await test('late weekly read cannot replace new selection',async()=>{delayId='b1';await click('.review-choice:nth-child(1)');await click('.review-choice:nth-child(2)');await pause(700);assert.match(await text('#preview h2'),/恩典/);delayId='';});
 await test('weekly reviewer protects unsubmitted comments',async()=>{await input('#review-comment','請調整圖片');answers.push(false);await click('.review-choice:nth-child(1)');assert.equal(await value('#review-comment'),'請調整圖片');assert.match(await text('#preview h2'),/恩典/);});
 await test('publication confirmation traps background and restores focus on cancel',async()=>{await click('#approve');await page.waitForSelector('.workflow-dialog[open]');assert.equal(await page.$eval('body',n=>n.style.position),'fixed');await page.keyboard.press('Escape');await pause(50);assert.equal(await page.$('.workflow-dialog'),null);assert.equal(await page.$eval('body',n=>n.style.position),'');assert.equal(await page.evaluate(()=>document.activeElement.id),'approve');assert.equal(writes.length,0);});
 await test('weekly failed decision retains comment and unlocks both decisions',async()=>{failWrite=true;await click('#approve');await modalAccept();assert.equal(await value('#review-comment'),'請調整圖片');assert.equal(await page.$eval('#request-changes',n=>n.disabled),false);});
 await test('weekly saved decision refresh failure blocks duplicates and reload only reads',async()=>{failWrite=false;afterWriteFail=true;delayWrite=120;await click('#approve');await modalAccept();assert.match(await text('#status'),/審核已完成/);assert.equal(await page.$eval('#review-actions',n=>n.hidden),true);const count=writes.length;failRead=false;afterWriteFail=false;await click('#review-reload');await waitIdle();assert.equal(writes.length,count);assert.match(await text('#workflow'),/已發布/);assert.equal(await page.$eval('.review-choice',n=>n.disabled),false);});
 await visit('weekly-bulletin-review.html',{role:'readonly',pending:true});await test('weekly reviewer permission is required',async()=>{assert.equal(await page.$eval('#review-actions',n=>n.hidden),true);assert.match(await text('#status'),/核准權限/);assert.equal(writes.length,0);});
 await visit('service-signup-admin.html');
 await test('service manager scopes and status filters guide work',async()=>{assert.match(await text('#workflow'),/1 筆待確認/);await input('#registration-filter','waiting','change');assert.equal(await page.$$eval('.slot-row',ns=>ns.length),1);await input('#registration-filter','','change');await input('#ministry-filter','media','change');assert.equal(await page.$$eval('.slot-row',ns=>ns.length),2);await input('#ministry-filter','','change');});
 await test('failed service open toggle restores original display and model',async()=>{failWrite=true;const label=await page.$eval('.slot-row>button',n=>n.textContent);await click('.slot-row>button');await waitIdle();assert.equal(await page.$eval('.slot-row>button',n=>n.textContent),label);assert.equal(services.slots[0].is_open,true);});
 await test('failed service capacity restores original value and allows retry',async()=>{await input('.slot-row input','2','change');await waitIdle();assert.equal(await value('.slot-row input'),'1');failWrite=false;await input('.slot-row input','2','change');await waitIdle();assert.equal(await value('.slot-row input'),'2');assert.equal(await page.$eval('.season-tabs button',n=>n.disabled),false);});
 await test('invalid service capacity never writes',async()=>{const count=writes.length;await input('.slot-row input','0','change');await waitIdle();assert.equal(writes.length,count);assert.match(await text('#status'),/1 到 20/);assert.equal(await value('.slot-row input'),'2');});
 await test('confirmed service refresh failure has safe reload without second confirmation',async()=>{afterWriteFail=true;await click('.review-actions button');await waitIdle();assert.match(await text('#status'),/操作已完成/);assert.equal(await page.$eval('.slot-row input',n=>n.disabled),true);const count=writes.length;failRead=false;afterWriteFail=false;await click('#service-reload');await waitIdle();assert.equal(writes.length,count);assert.equal(await page.$('.review-actions button'),null);assert.equal(services.slots[0].registrations[0].status,'confirmed');});
 await visit('service-signup-admin.html');await test('service decline confirmation cancellation never releases place',async()=>{await click('.review-actions button:last-child');await page.waitForSelector('.workflow-dialog[open]');await click('.workflow-dialog button.secondary');assert.equal(writes.length,0);assert.equal(services.slots[0].registrations[0].status,'registered');});
 await visit('service-signup-admin.html');await test('service change review uses labeled note dialog and requires return reason',async()=>{changes=[{id:201,season_id:'s1',member_name:'測試同工',service_date:'2027-01-03',ministry_key:'media',role_key:'sound',request_type:'cancel',member_note:'時間需要調整',status:'leader_review'}];await click('#service-reload');await waitIdle();await click('.change-actions button:last-child');await page.waitForSelector('.workflow-dialog[open]');await input('.workflow-dialog textarea','   ');await click('.workflow-dialog button[type=submit]');assert.equal(writes.length,0);assert(await page.$('.workflow-dialog[open]'));await input('.workflow-dialog textarea','請先與領袖協調');await modalAccept();assert.equal(writes.at(-1).body.note,'請先與領袖協調');});
 await visit('service-signup-admin.html');await test('service suggestions keep own choices and confirm before applying',async()=>{await click('.smart-match-button');await waitIdle();assert.match(await text('#smartPanel'),/測試同工/);const count=writes.length;await click('.smart-actions button:last-child');await page.waitForSelector('.workflow-dialog[open]');assert.equal(writes.length,count);await modalAccept();assert.equal(writes.length,count+1);assert.equal(services.slots[0].registrations[0].status,'confirmed');});
 await visit('service-signup-admin.html');await test('service leader scope limits available filters and controls',async()=>{services.can_manage=false;services.scopes=['media'];services.slots[1].registrations=[{id:102,status:'registered',name:'測試老師'}];await click('#service-reload');await waitIdle();assert.deepEqual(await page.$$eval('#ministry-filter option',ns=>ns.map(n=>n.value)),['','media']);assert.equal(await page.$eval('#create',n=>n.hidden),true);assert.equal(await page.$$eval('.review-actions',ns=>ns.length),1);});
 await visit('service-signup-admin.html');await test('revoked service access clears working data and prevents writes',async()=>{mode='denied';await click('#service-reload');await waitIdle();assert.equal(await page.$$eval('.slot-row',ns=>ns.length),0);assert.match(await text('#status'),/權限/);assert.equal(writes.length,0);});
 await visit('website-maintenance.html');
 await test('weekly editor shows collapsed preview and clear section shortcuts',async()=>{assert.equal(await page.$eval('.website-preview-disclosure',n=>n.open),false);assert.equal(await page.$eval('.bulletin-choice',n=>getComputedStyle(n).backgroundImage),'none');assert.equal(await page.$$eval('.workflow-section-nav a',ns=>ns.length),5);assert.match(await text('#workflow'),/編輯與儲存/);});
 await input('#sermon-topic','未儲存主題');
 await test('weekly dirty switch can be cancelled without losing values',async()=>{answers.push(false);await click('.bulletin-choice:nth-child(2)');assert.equal(await value('#sermon-topic'),'未儲存主題');assert.equal(writes.length,0);});
 await test('weekly failed save preserves inputs and optimistic version checks',async()=>{failWrite=true;await click('#save-bulletin');await waitIdle();assert.equal(await value('#sermon-topic'),'未儲存主題');assert.equal(await page.$eval('#save-bulletin',n=>n.disabled),false);const write=writes.at(-1);assert.match(write.url,/version=eq.1/);assert.match(write.url,/church_id=eq.M/);});
 await test('weekly double save creates one write and saved feedback',async()=>{failWrite=false;delayWrite=150;const count=writes.length;await page.$eval('#bulletin-form',form=>{form.requestSubmit();form.requestSubmit();});await waitIdle();assert.equal(writes.length,count+1);assert.match(await text('#status'),/已儲存/);assert.equal(await page.$eval('#draft-state',n=>n.dataset.dirty),'false');});
 await test('late schedule lookup cannot overwrite selected Sunday',async()=>{delaySchedule='2027-02-07';await input('#service-date','2027-02-07','change');await input('#service-date','2027-02-14','change');await pause(700);assert.match(await text('#schedule-preview'),/排班 2027-02-14/);assert.doesNotMatch(await text('#schedule-preview'),/排班 2027-02-07/);});
 await test('thematic promo generates both previews and marks unsaved draft',async()=>{await click('#generate-home-promo');await waitIdle();assert.equal(await page.$eval('#image-preview',n=>n.hidden),false);assert.equal(await page.$eval('#reel-cover-preview',n=>n.hidden),false);assert.match(await text('#draft-state'),/尚未儲存/);});
 await test('weekly saved but reload failed preserves acknowledgement and blocks repeat',async()=>{afterWriteFail=true;await click('#save-bulletin');await waitIdle();assert.match(await text('#status'),/週報已儲存/);assert.equal(await page.$eval('#save-bulletin',n=>n.disabled),true);const count=writes.length;failRead=false;afterWriteFail=false;await click('#reload-bulletins');await waitIdle();assert.equal(writes.length,count);assert.equal(await page.$eval('#save-bulletin',n=>n.disabled),false);});
 await test('weekly submit has confirmation and locks published draft editing after server result',async()=>{await click('#submit-review');await modalAccept();assert.equal(bulletins[0].status,'pending_review');assert.equal(await page.$eval('#sermon-topic',n=>n.disabled),true);assert.equal(await page.$eval('#submit-review',n=>n.hidden),true);assert.match(await text('#workflow'),/等待核准/);});
 await visit('website-maintenance.html');await test('weekly acknowledged submission refresh failure cannot send another notice',async()=>{afterWriteFail=true;afterWriteAction='submit';await click('#submit-review');await modalAccept();assert.match(await text('#status'),/週報已送審/);const count=writes.length;assert.equal(await page.$eval('#sermon-topic',n=>n.disabled),true);failRead=false;afterWriteFail=false;await click('#reload-bulletins');await waitIdle();assert.equal(writes.length,count);assert.equal(await page.$eval('#submit-review',n=>n.hidden),true);});
 await visit('website-maintenance.html',{role:'readonly'});await test('weekly view-only permission does not grant edit or create',async()=>{assert.equal(await page.$eval('#sermon-topic',n=>n.disabled),true);assert.equal(await page.$eval('#new-bulletin',n=>n.disabled),true);assert.equal(await page.$eval('#save-bulletin',n=>n.hidden),true);assert.equal(writes.length,0);});
 for(const kind of ['daily','review','service','weekly']){const file={daily:'daily-devotional-admin.html',review:'weekly-bulletin-review.html',service:'service-signup-admin.html',weekly:'website-maintenance.html'}[kind];await visit(file,{pending:kind==='review'});await test(kind+' interrupted write requires readonly verification before retry',async()=>{abortWrite=true;if(kind==='daily'){await click('[data-edit]');await input('[name=devotional_title]','連線中斷測試');await click('.devotional-editor button[type=submit]');}else if(kind==='review'){await click('#approve');await modalAccept();}else if(kind==='service')await input('.slot-row input','2','change');else await click('#save-bulletin');await waitIdle();assert.match(await text('#status'),/連線中斷|尚無法確認/);const count=writes.length;abortWrite=false;const retry={daily:'#devotional-reload',review:'#review-reload',service:'#service-reload',weekly:'#reload-bulletins'}[kind];if(kind==='daily'||kind==='weekly')answers.push(true);await click(retry);await waitIdle();assert.equal(writes.length,count);});}
 for(const kind of ['daily','review','service','weekly']){const file={daily:'daily-devotional-admin.html',review:'weekly-bulletin-review.html',service:'service-signup-admin.html',weekly:'website-maintenance.html'}[kind];await visit(file,{pending:kind==='review'});await test(kind+' missing acknowledgement cannot report success or resend',async()=>{malformedWrite=true;if(kind==='daily'){await click('[data-edit]');await input('[name=devotional_title]','缺少回應測試');await click('.devotional-editor button[type=submit]');}else if(kind==='review'){await click('#approve');await modalAccept();}else if(kind==='service')await click('.review-actions button');else {await click('#submit-review');await modalAccept();}await waitIdle();assert.match(await text('#status'),/尚無法確認|重新載入/);const count=writes.length;malformedWrite=false;const retry={daily:'#devotional-reload',review:'#review-reload',service:'#service-reload',weekly:'#reload-bulletins'}[kind];if(kind==='daily')answers.push(true);await click(retry);await waitIdle();assert.equal(writes.length,count);});}
 for(const file of ['daily-devotional-admin.html','weekly-bulletin-review.html','service-signup-admin.html','website-maintenance.html']){
  await visit(file,{pending:file==='weekly-bulletin-review.html'});
  for(const width of [375,390,430,1280,1440,1920]){
   await page.setViewport({width,height:900,isMobile:width<800,hasTouch:width<800});await pause(100);await waitIdle();await page.waitForSelector('#workflow h2');
   await test(file+' layout at '+width+'px',async()=>{const metrics=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,head:document.querySelector('.page-header').getBoundingClientRect().height,short:[...document.querySelectorAll('.workflow-toolbar button,.workflow-toolbar select,.workflow-toolbar input,.workflow-section-nav a,.devotional-choice,.review-actions button')].filter(n=>n.getBoundingClientRect().width&&n.getBoundingClientRect().height<43.5).map(n=>n.outerHTML.slice(0,150))}));assert(metrics.scroll<=metrics.width+1,JSON.stringify(metrics));assert.equal(metrics.short.length,0,JSON.stringify(metrics.short));assert.equal(Math.round(metrics.head),164);});
   if([390,1440].includes(width)){const disclosures=await page.$$eval('details',nodes=>nodes.map(n=>n.open));const contrast=await page.evaluate(contrastMetrics);await test(file+' text contrast at '+width+'px',async()=>assert.deepEqual(contrast.failures,[]));fs.writeFileSync(out+file.replace('.html','')+'-contrast-'+width+'.json',JSON.stringify(contrast,null,2));await page.$$eval('details',(nodes,states)=>nodes.forEach((n,i)=>n.open=states[i]),disclosures);}
   if([390,1440].includes(width))await page.screenshot({path:out+file.replace('.html','')+'-'+width+'.png',fullPage:true});
  }
 }
 await test('workflow pages have no uncaught browser errors or unexpected dialogs',async()=>assert.deepEqual(errors,[]));
 fs.writeFileSync(out+'checks.json',JSON.stringify({origin:base,api_mode:'isolated_synthetic',checks,total:checks.length},null,2)+'\n');console.log('TOTAL',checks.length);passed=true;
}finally{const chromeProcess=browser.process();await Promise.race([browser.close(),pause(5000)]);browser.disconnect();if(chromeProcess?.exitCode===null)chromeProcess.kill('SIGTERM');if(passed)process.exit(0);}
