create table if not exists public.daily_devotionals (
  id uuid primary key default gen_random_uuid(),
  church_id text not null check (church_id in ('M+', 'SHiNE')),
  devotional_date date not null,
  day_number integer not null check (day_number between 1 and 366),
  weekday text not null,
  month_theme text not null,
  tree_stage text not null,
  week_number integer not null check (week_number between 1 and 53),
  week_theme text not null,
  devotional_title text not null,
  selected_scripture_reference text not null,
  roots_reading text not null,
  branches_reading text,
  fruit_reading text,
  chapter_count integer not null check (chapter_count between 1 and 20),
  scripture_text text not null,
  scripture_is_excerpt boolean not null default false,
  scripture_version text,
  scripture_source text,
  scripture_license_note text,
  context_summary text not null,
  key_points text not null,
  reflection_questions text not null,
  life_application text not null,
  response_prayer text not null,
  review_status text not null default 'draft'
    check (review_status in ('draft','initial_review','final_review','approved','returned','archived')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  published_at timestamptz,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (church_id, devotional_date)
);

create index if not exists daily_devotionals_publication_idx
  on public.daily_devotionals (church_id, devotional_date, review_status, published_at);

create table if not exists public.daily_devotional_progress (
  church_id text not null check (church_id in ('M+', 'SHiNE')),
  line_subject text not null,
  devotional_date date not null,
  completed_at timestamptz not null default now(),
  reflection_note text check (reflection_note is null or char_length(reflection_note) between 1 and 1000),
  note_updated_at timestamptz,
  primary key (church_id, line_subject, devotional_date),
  foreign key (church_id, devotional_date)
    references public.daily_devotionals (church_id, devotional_date) on delete restrict
);

create index if not exists daily_devotional_progress_subject_idx
  on public.daily_devotional_progress (church_id, line_subject, devotional_date desc);

create table if not exists public.daily_devotional_reviews (
  id bigint generated by default as identity primary key,
  devotional_id uuid not null references public.daily_devotionals(id) on delete restrict,
  reviewer_id uuid not null references auth.users(id) on delete restrict,
  from_status text not null,
  to_status text not null,
  comment text,
  created_at timestamptz not null default now()
);

create index if not exists daily_devotional_reviews_item_idx
  on public.daily_devotional_reviews (devotional_id, created_at desc);

alter table public.daily_devotionals enable row level security;
alter table public.daily_devotional_progress enable row level security;
alter table public.daily_devotional_reviews enable row level security;

revoke all on public.daily_devotionals from anon, authenticated;
revoke all on public.daily_devotional_progress from anon, authenticated;
revoke all on public.daily_devotional_reviews from anon, authenticated;
grant select, insert, update, delete on public.daily_devotionals to service_role;
grant select, insert, update, delete on public.daily_devotional_progress to service_role;
grant select, insert, update, delete on public.daily_devotional_reviews to service_role;
grant usage, select on sequence public.daily_devotional_reviews_id_seq to service_role;

create policy "Service role manages daily devotionals"
  on public.daily_devotionals for all to service_role using (true) with check (true);
create policy "Service role manages daily devotional progress"
  on public.daily_devotional_progress for all to service_role using (true) with check (true);
create policy "Service role manages daily devotional reviews"
  on public.daily_devotional_reviews for all to service_role using (true) with check (true);

comment on table public.daily_devotionals is
  'Versioned daily devotional content. Member clients access approved publications only through verified Edge Functions.';
comment on table public.daily_devotional_progress is
  'Private LINE member completion and reflection records. Never expose directly through the Data API.';
comment on table public.daily_devotional_reviews is
  'Append-only audit trail for the two-stage devotional review workflow.';

create or replace function public.update_daily_devotional_content(
  p_id uuid,
  p_editor uuid,
  p_values jsonb
) returns public.daily_devotionals
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare result public.daily_devotionals;
begin
  if p_values is null or p_values = '{}'::jsonb then raise exception 'empty_update'; end if;
  if exists (select 1 from jsonb_object_keys(p_values) key where key not in (
    'devotional_title','selected_scripture_reference','scripture_text','scripture_version','scripture_source','scripture_license_note','context_summary',
    'key_points','reflection_questions','life_application','response_prayer'
  )) then raise exception 'invalid_field'; end if;
  update public.daily_devotionals set
    devotional_title=coalesce(nullif(btrim(p_values->>'devotional_title'),''),devotional_title),
    selected_scripture_reference=coalesce(nullif(btrim(p_values->>'selected_scripture_reference'),''),selected_scripture_reference),
    scripture_text=coalesce(nullif(btrim(p_values->>'scripture_text'),''),scripture_text),
    scripture_version=coalesce(nullif(btrim(p_values->>'scripture_version'),''),scripture_version),
    scripture_source=coalesce(nullif(btrim(p_values->>'scripture_source'),''),scripture_source),
    scripture_license_note=coalesce(nullif(btrim(p_values->>'scripture_license_note'),''),scripture_license_note),
    context_summary=coalesce(nullif(btrim(p_values->>'context_summary'),''),context_summary),
    key_points=coalesce(nullif(btrim(p_values->>'key_points'),''),key_points),
    reflection_questions=coalesce(nullif(btrim(p_values->>'reflection_questions'),''),reflection_questions),
    life_application=coalesce(nullif(btrim(p_values->>'life_application'),''),life_application),
    response_prayer=coalesce(nullif(btrim(p_values->>'response_prayer'),''),response_prayer),
    scripture_is_excerpt=position('…' in coalesce(p_values->>'scripture_text',scripture_text))>0,
    review_status='initial_review',reviewed_by=null,reviewed_at=null,approved_by=null,approved_at=null,published_at=null,
    version=version+1,updated_at=now()
  where id=p_id and church_id='M+'
  returning * into result;
  if result.id is null then raise exception 'not_found'; end if;
  insert into public.daily_devotional_reviews(devotional_id,reviewer_id,from_status,to_status,comment)
  values(p_id,p_editor,'content_edit','initial_review','內容修改後自動退回初審');
  return result;
end $$;

create or replace function public.review_daily_devotional(
  p_id uuid,
  p_reviewer uuid,
  p_to_status text,
  p_comment text default null
) returns public.daily_devotionals
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare current_row public.daily_devotionals; result public.daily_devotionals;
begin
  select * into current_row from public.daily_devotionals where id=p_id and church_id='M+' for update;
  if current_row.id is null then raise exception 'not_found'; end if;
  if p_to_status='final_review' and current_row.review_status not in ('draft','initial_review','returned') then raise exception 'invalid_transition'; end if;
  if p_to_status='approved' and current_row.review_status<>'final_review' then raise exception 'invalid_transition'; end if;
  if p_to_status='approved' and current_row.reviewed_by=p_reviewer then raise exception 'different_reviewer_required'; end if;
  if p_to_status='approved' and (current_row.scripture_version is null or current_row.scripture_source is null or current_row.scripture_license_note is null) then raise exception 'licensing_required'; end if;
  if p_to_status='returned' and current_row.review_status not in ('initial_review','final_review') then raise exception 'invalid_transition'; end if;
  if p_to_status='returned' and nullif(btrim(p_comment),'') is null then raise exception 'comment_required'; end if;
  if p_to_status not in ('final_review','approved','returned') then raise exception 'invalid_transition'; end if;
  update public.daily_devotionals set
    review_status=p_to_status,
    reviewed_by=case when p_to_status='final_review' then p_reviewer when p_to_status='returned' then null else reviewed_by end,
    reviewed_at=case when p_to_status='final_review' then now() when p_to_status='returned' then null else reviewed_at end,
    approved_by=case when p_to_status='approved' then p_reviewer else null end,
    approved_at=case when p_to_status='approved' then now() else null end,
    published_at=case when p_to_status='approved' then now() else null end,
    updated_at=now()
  where id=p_id returning * into result;
  insert into public.daily_devotional_reviews(devotional_id,reviewer_id,from_status,to_status,comment)
  values(p_id,p_reviewer,current_row.review_status,p_to_status,nullif(btrim(p_comment),''));
  return result;
end $$;

revoke all on function public.update_daily_devotional_content(uuid,uuid,jsonb) from public,anon,authenticated;
revoke all on function public.review_daily_devotional(uuid,uuid,text,text) from public,anon,authenticated;
grant execute on function public.update_daily_devotional_content(uuid,uuid,jsonb) to service_role;
grant execute on function public.review_daily_devotional(uuid,uuid,text,text) to service_role;
