begin;

create table public.love_share_scenarios(
  id bigint generated by default as identity primary key,
  church_id text not null references public.churches(id) on update cascade on delete restrict,
  name text not null,
  icon text not null default '💛',
  is_active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint love_share_scenarios_church check(church_id in ('M+','SHiNE')),
  constraint love_share_scenarios_name check(char_length(btrim(name)) between 1 and 60),
  constraint love_share_scenarios_icon check(char_length(btrim(icon)) between 1 and 12),
  constraint love_share_scenarios_order check(sort_order between 0 and 9990),
  unique(church_id,name)
);

create index love_share_scenarios_active_order_idx
on public.love_share_scenarios(church_id,sort_order)
where is_active;

alter table public.love_share_scenarios enable row level security;
revoke all on public.love_share_scenarios from anon,authenticated;
grant select,insert,update,delete on public.love_share_scenarios to authenticated;
grant usage,select on sequence public.love_share_scenarios_id_seq to authenticated;

create policy love_share_scenarios_church_permission
on public.love_share_scenarios
for all
to authenticated
using((select church_auth.allowed(church_id,'pastoral_chats')))
with check((select church_auth.allowed(church_id,'pastoral_chats')));

insert into public.love_share_scenarios(church_id,name,icon,is_active,sort_order)
select church_id,category,'💛',true,row_number() over(partition by church_id order by category)*10
from (
  select distinct church_id,btrim(category) as category
  from public.share_greeting_cards
  where btrim(coalesce(category,''))<>''
) existing
on conflict(church_id,name) do nothing;

insert into public.love_share_scenarios(church_id,name,icon,is_active,sort_order)
select church_id,name,icon,true,sort_order
from (values
  ('M+'::text,'同事打拼','💼',110),('M+','低潮陪伴','🌧️',120),('M+','家人問候','🏡',130),('M+','信心得勝','☀️',140),
  ('SHiNE','同事打拼','💼',110),('SHiNE','低潮陪伴','🌧️',120),('SHiNE','家人問候','🏡',130),('SHiNE','信心得勝','☀️',140)
) defaults(church_id,name,icon,sort_order)
on conflict(church_id,name) do nothing;

commit;
