begin;

create table if not exists public.line_share_assets(
  id bigint generated by default as identity primary key,
  church_id text not null references public.churches(id),
  line_user_id text not null,
  object_path text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now()+interval '14 days'),
  constraint line_share_assets_church check(church_id in ('M+','SHiNE')),
  constraint line_share_assets_user check(line_user_id ~ '^U[0-9a-f]{32}$')
);

alter table public.line_share_assets enable row level security;
revoke all on public.line_share_assets from anon,authenticated;

create index if not exists line_share_assets_rate_idx
  on public.line_share_assets(line_user_id,created_at desc);
create index if not exists line_share_assets_expiry_idx
  on public.line_share_assets(expires_at);
create index if not exists line_share_assets_church_idx
  on public.line_share_assets(church_id);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('line-share-cards','line-share-cards',true,2621440,array['image/png','image/jpeg'])
on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists line_share_cards_public_read on storage.objects;
create policy line_share_cards_public_read on storage.objects for select to anon,authenticated
using(bucket_id='line-share-cards');

commit;
