create table if not exists public.sermon_subtitle_knowledge (
  id bigint generated by default as identity primary key,
  church_id text not null default 'M+',
  knowledge_type text not null check (knowledge_type in ('glossary','correction','speaker_term','approved_example')),
  wrong_text text,
  correct_text text not null,
  context_hint text,
  speaker text,
  source_draft_id uuid references public.sermon_social_drafts(id) on delete set null,
  source_segment_index integer check (source_segment_index is null or source_segment_index >= 0),
  verified boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sermon_subtitle_knowledge enable row level security;
revoke all on public.sermon_subtitle_knowledge from anon, authenticated;
grant all on public.sermon_subtitle_knowledge to service_role;

create index if not exists sermon_subtitle_knowledge_lookup_idx
  on public.sermon_subtitle_knowledge (church_id, active, verified, knowledge_type, updated_at desc);

create unique index if not exists sermon_subtitle_knowledge_term_unique_idx
  on public.sermon_subtitle_knowledge (church_id, knowledge_type, coalesce(wrong_text, ''), correct_text)
  where knowledge_type <> 'approved_example';

create unique index if not exists sermon_subtitle_knowledge_example_unique_idx
  on public.sermon_subtitle_knowledge (source_draft_id, source_segment_index)
  where knowledge_type = 'approved_example';

insert into public.sermon_subtitle_knowledge
  (church_id, knowledge_type, wrong_text, correct_text, context_hint, verified, active)
values
  ('M+','glossary',null,'GOOD TV','機構英文名稱，不可拆字',true,true),
  ('M+','glossary',null,'MIS 工程師','英文縮寫與職稱',true,true),
  ('M+','glossary',null,'M+ 大雅教會','教會正式名稱',true,true),
  ('M+','glossary',null,'吳俊璋牧師','講員姓名與職稱',true,true),
  ('M+','glossary',null,'馬可福音','聖經書卷',true,true),
  ('M+','glossary',null,'五餅二魚','聖經用語',true,true),
  ('M+','correction','QTU','GOOD TV','英文機構名稱',true,true),
  ('M+','correction','QCU','GOOD TV','英文機構名稱',true,true),
  ('M+','correction','福市','服事','教會用語',true,true),
  ('M+','correction','傳覆音','傳福音','教會用語',true,true),
  ('M+','correction','礦也','曠野','聖經用語',true,true),
  ('M+','correction','退休會','退修會','教會活動',true,true),
  ('M+','correction','門讀','門徒','聖經用語',true,true),
  ('M+','correction','南丁','男丁','聖經用語',true,true),
  ('M+','correction','五餅二餘','五餅二魚','聖經用語',true,true),
  ('M+','correction','五個餅二魚','五餅二魚','聖經用語',true,true),
  ('M+','correction','聯名','憐憫','聖經語境',true,true),
  ('M+','correction','木人','牧人','聖經語境',true,true),
  ('M+','correction','3節到35節','33節到35節','經文章節',true,true)
on conflict do nothing;

insert into public.sermon_subtitle_knowledge
  (church_id, knowledge_type, wrong_text, correct_text, context_hint, speaker, source_draft_id, source_segment_index, verified, active)
select
  d.church_id,
  'approved_example',
  left((select string_agg(replace(coalesce(cue->>'text',''), E'\n', ' '), ' ' order by ord)
        from jsonb_array_elements(coalesce(s.cues, '[]'::jsonb)) with ordinality as x(cue, ord)), 12000),
  left((select string_agg(replace(coalesce(cue->>'text',''), E'\n', ' '), ' ' order by ord)
        from jsonb_array_elements(coalesce(s.reviewed_cues, '[]'::jsonb)) with ordinality as x(cue, ord)), 12000),
  '已正式發布的講道字幕片段',
  d.speaker,
  s.draft_id,
  s.segment_index,
  true,
  true
from public.sermon_subtitle_segments s
join public.sermon_social_drafts d on d.id = s.draft_id
join public.youtube_caption_publications p on p.draft_id = s.draft_id and p.status = 'published'
where s.review_status = 'completed'
  and jsonb_array_length(coalesce(s.reviewed_cues, '[]'::jsonb)) > 0
on conflict (source_draft_id, source_segment_index)
  where knowledge_type = 'approved_example'
do nothing;

do $block$
begin
  perform cron.unschedule(jobid)
  from cron.job
  where jobname = 'sermon-subtitle-proofreading';

  perform cron.schedule(
    'sermon-subtitle-proofreading',
    '*/2 * * * *',
    $job$
    with candidate as (
      select draft_id, segment_index
      from public.sermon_subtitle_segments
      where status = 'completed'
        and coalesce(review_status, 'pending') <> 'completed'
      order by updated_at, segment_index
      limit 1
    )
    select net.http_post(
      url := (select decrypted_secret from vault.decrypted_secrets where name = 'pastoral-care-project-url') || '/functions/v1/youtube-oauth',
      headers := jsonb_build_object(
        'content-type', 'application/json',
        'x-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'pastoral-care-cron-secret')
      ),
      body := jsonb_build_object(
        'action', 'rewrite_subtitle_segment',
        'church', 'M+',
        'draftId', candidate.draft_id,
        'segmentIndex', candidate.segment_index
      ),
      timeout_milliseconds := 120000
    )
    from candidate;
    $job$
  );
end
$block$;
